### ISSUE TITLE
tests dis_transpose: test passed 

### ISSUE THREAD

**Issue by WeiLiPenguin** [sourceryinstitute/opencoarrays#1]
the line: [test passed](https://github.com/sourceryinstitute/opencoarrays/blob/master/src/tests/integration/dist_transpose/coarray_distributed_transpose.F90#L205) should be Test passed? 

```
2/12 Test  #2: distributed_transpose ............***Failed  Required regular expression not found.Regex=[Test passed.
```

Thanks for your cool project!

**Comment by WeiLiPenguin** [comment]
seems some of the test Makefile not give the right "opencoarrays_dir",
If the tests should run in the src/tests/xxxx .

opencoarrays_dir=../../../../mpi/

**Comment by WeiLiPenguin** [comment]
tests/integration/pde_solvers/navier-stokes seems not have a "Test passed" to used by ctest?

**Comment by WeiLiPenguin** [comment]
navier-stokes/CMakeLists.txt:

[mpi-shear.F90 should change to mpi-shear.f90](https://github.com/sourceryinstitute/opencoarrays/blob/master/src/tests/integration/pde_solvers/navier-stokes/CMakeLists.txt#L19) ?
and add [target_link_libraries( mpi_navier_stokes ${CMAKE_CURRENT_SOURCE_DIR}/lib${fft_library}.a ) after line 26](https://github.com/sourceryinstitute/opencoarrays/blob/master/src/tests/integration/pde_solvers/navier-stokes/CMakeLists.txt#L26)?

**Comment by sourceryinstitute** [comment]
Hi Weili,

Thanks for downloading and building OpenCoarrays.  We're working on the tests. For now, it is safe to ignore test failures. All current failures are trivial failures in the sense that we just need to insert a statement printing out the string CTest expects to see in the test output to indicate a successful. I will likely do this next week.  We will also be adding several additional tests soon. 

If you reached the point of running the tests, then presumably OpenCoarrays built successfully and you're ready to start using it.  

Damian

**Comment by WeiLiPenguin** [comment]
Thank you and nice to see a new commit, 

is that possible to use intel compile for opencoarrays? 
by using a "home made" fortran translator? or do you have any plan related to that?

**Comment by sourceryinstitute** [comment]
Hi WeiLi,

It should be possible to compile OpenCoarrays with the Intel compiler.  Although the Intel compiler won’t generate any calls to OpenCoarrays directly, you can probably invoke some of the OpenCoarrays procedures in your source code using Fortran’s C-interoperability features.  When you mentioned a homemade Fortran translator, were you referring to translating the C header files into Fortran interface blocks?  Presumably that would be the way to go.  

OpenCoarrays supports most or all of the collective subroutines that are proposed to become part of Fortran 2015 but are not yet supported by the Intel compiler.  These collectives could be of use to you.  We have found that the OpenCoarrays collectives outperform even reasonably sophisticated collective communication procedures that a competent parallel programmer would write manually in Fortran 2008 to accomplish various reductions and broadcasts, for example.  See the link to the draft Technical Specification 18508 on www.opencoarrays.org <http://www.opencoarrays.org/> for more information on the Fortran 2015 collective subroutines.

We would very much like to see compiler vendors employ OpenCoarrays so it would be great for you to let Intel know you’re interested and why.  We have had interactions with most Fortran compiler vendors and are hopeful that several will eventually adopt OpenCoarrays, but we are much more likely to convince the ones who don’t yet support coarray Fortran (CAF) than those that have already invested resources into supporting it.  

Besides the fact that OpenCoarrays has helped GNU leapfrog existing CAF implementations in terms of certain features (such as the collectives), one aim of OpenCoarrays is also to make a design statement that application developers are well-served by allowing them to decided which communication library (e.g., MPI, GASNet, etc.) best suits the needs their application and their hardware platform. 

If any of the above interests you, please let Intel know by submitting a feature request via Intel’s Premier Support and/or the Intel Developer Forum.

________________________________
Damian Rouson, Ph.D., P.E.
Founder & President, Sourcery, Inc.
510-600-2992 (mobile)
http://www.sourceryinstitute.org
http://rouson.youcanbook.me

**Comment by sourceryinstitute** [comment]
Hi WeiLi,

It should be possible to compile OpenCoarrays with the Intel compiler.  Although the Intel compiler won’t generate any calls to OpenCoarrays directly, you can probably invoke some of the OpenCoarrays procedures in your source code using Fortran’s C-interoperability features.  When you mentioned a homemade Fortran translator, were you referring to translating the C header files into Fortran interface blocks?  Presumably that would be the way to go.  

OpenCoarrays supports most or all of the collective subroutines that are proposed to become part of Fortran 2015 but are not yet supported by the Intel compiler.  These collectives could be of use to you.  We have found that the OpenCoarrays collectives outperform even reasonably sophisticated collective communication procedures that a competent parallel programmer would write manually in Fortran 2008 to accomplish various reductions and broadcasts, for example.  See the link to the draft Technical Specification 18508 on www.opencoarrays.org for more information on the Fortran 2015 collective subroutines.

We would very much like to see compiler vendors employ OpenCoarrays so it would be great for you to let Intel know you’re interested and why.  We have had interactions with most Fortran compiler vendors and are hopeful that several will eventually adopt OpenCoarrays, but we are much more likely to convince the ones who don’t yet support coarray Fortran (CAF) than those that have already invested resources into supporting it.  

Besides the fact that OpenCoarrays has helped GNU leapfrog existing CAF implementations in terms of certain features (such as the collectives), one aim of OpenCoarrays is also to make a design statement that application developers are well-served by allowing them to decided which communication library (e.g., MPI, GASNet, etc.) best suits the needs their application and their hardware platform. 

If any of the above interests you, please let Intel know by submitting a feature request via Intel’s Premier Support and/or the Intel Developer Forum.

**Comment by WeiLiPenguin** [comment]
Thank you for the reply. 
"home made" fortran translator. I mean like the gfortran parsing the source file to generate the calling _gfortran_caf_co_xxx, If I am right. Can I get the gfortran parsed source file? could you please try to explain how it worked in gfortran, but maybe I am not clever to understand it.

**Comment by afanfa** [comment]
What you are trying to do makes totally sense. I used to do it when the
compiler didn't have support for some features. If you want to see what GNU
Fortran does just compile your file with the -fdump-tree-original flag.
You'll see the parsed code and the invocations to opencoarrays.

On Mon, Jun 1, 2015 at 9:58 PM, WeiLi <notifications@github.com> wrote:

> Thank you for the reply.
> "home made" fortran translator. I mean like the gfortran parsing the
> source file to generate the calling _gfortran_caf_co_xxx, If I am right.
> Can I get the gfortran parsed source file? could you please try to explain
> how it worked in gfortran, but maybe I am not clever to understand it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/1#issuecomment-107688226>
> .
>



-- 

Alessandro Fanfarillo
