### ISSUE TITLE
Teach `check_version.sh` about MPI version numbers

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#104]
See https://github.com/sourceryinstitute/opencoarrays/commit/74debcba9ccf073128b8ed78a70371e6d8fe6c49 for more details.

> TODO: handle version numbers in the major.minor format and then
use check_version.sh to verify the version number returne dby
"mpif90 -v".  Currently install.sh instead uses "mpif90 --version"
which returns the version number of the Fortran compiler that mpif90
wraps. No check on the version number of the MPI implementation itself
is performed.

**Comment by zbeekman** [comment]
@rouson: Is this issue still relevant? If not let's close it.

**Comment by rouson** [comment]
I guess not.
