### ISSUE TITLE
CMAKE_Fortran_COMPILER_VERSION becomes unset after second configuring

### ISSUE THREAD

**Issue by raullaasner** [sourceryinstitute/opencoarrays#11]
In the top-most [CMakeLists.txt](https://github.com/sourceryinstitute/opencoarrays/blob/master/CMakeLists.txt), line 45, `CMAKE_Fortran_COMPILER_VERSION` is used in the comparison. However, this variable [becomes unset with the second configuring](http://stackoverflow.com/questions/31805891/cmake-fortran-compiler-version-becomes-unset-after-second-configuring) (second run of `cmake`). Thus, when I change some variables after the first configuring, e.g., `CMAKE_BUILD_TYPE`, `CMAKE_Fortran_COMPILER_VERSION` becomes unset and the conditional becomes false. As a result, `opencoarrays_aware_compiler` is set to false, even though this is not true. I'm not sure if that changes anything but I thought I'd let you know.

Also, as a small note, perhaps it's better to change line 43 to

```
if (NOT CMAKE_VERSION VERSION_LESS 3.3)
```

in case version 3.2.4 comes out?
Thanks and keep up the good work!

**Comment by rouson** [comment]
Hi Raul,

Thanks for your suggestions.  Would you be willing to clone the repository and submit a pull request with your suggested changes?  If so, that would be very helpful and make the source of the edits more clear in the git log.  

Damian
