### ISSUE TITLE
Finalize CUDA MPI

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#118]
for 2.x release

 - [x] additional testing

**Comment by rouson** [comment]
@afanfa, is there anything left to do on this or is this feature ready for release once we merge devel into master?

**Comment by zbeekman** [comment]
Just waiting on release notes from @afanfa

**Comment by afanfa** [comment]
The CUDA support provided by OpenCoarrays is based on the function registernc. This function simply registers the host memory stored during the normal allocation into the CUDA memory address space. This simple allocation delegates all the data transfers from/to host/gpu to the CUDA runtime.
