### ISSUE TITLE
ftp fails on Linux

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#123]
The current ftp command inside [build](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build) works on OS X but fails on Linux. Possible fixes: (1) revert to wget or (2) use a more involved multi-line ftp such as explained [here](http://www.stratigery.com/scripting.ftp.html)

**Comment by zbeekman** [comment]
I can confirm this bug exists

**Comment by rouson** [comment]
I'm closing this pull request and will submit a new one with a few more fixes later today. I am now able to build in a nearly bare Linux virtual machine after installing only the packages mentioned in my comment on issue #125.

**Comment by zbeekman** [comment]
This isn't a pull request, it's an issue 🤓

**Comment by zbeekman** [comment]
btw, I think we should mirgrate to curl, away from wget. curl is much more ubiquitous on *nix systems
