### ISSUE TITLE
`tar xf ___________.tar.xz`  fails on some old linux systems

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#125]
I am trying to install OC on my work machine, which is in all kinds of bad shape due to a backdated kernel to support our terrible lustre-fs implementation.... anyway, `tar xf m4-x.y.z.tar.xz` fails because `tar` doesn't understand how to extract .xz files. We should probably try to use gzip compression for everything, because it's my impression that gzip is the most ubiquitous compression program available. Better yet, for some of the smaller stuff maybe we can download uncompressed tarballs?

**Comment by rouson** [comment]
I'm fine with switching to .gz files.  Just keep in mind that the files will be bigger and therefore slower to download.  Also, my understanding is that "tar xf" is general so the following should all work

tar xf foo.tar.gz
tar xf foo.tar.xz
tar xf foo.tar.z2

Would you like to make the required edits to [build](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build) or would you prefer that I do it?

**Comment by zbeekman** [comment]
I would say bz2 or  gz over xz. If you can get to the edits, I say go for it. My workstation in the lab is in sad shape... Currently, after tricking `build` into thinking m4 is xz when it's actually a gz file, I choke on m4 installation: 

```
/usr/bin/ld: Dwarf Error: found dwarf version '4', this reader only handles version 2 information.
```

**Comment by zbeekman** [comment]
I will say, it may not be possible, i've tried installing gcc 5.3 before and failed, but thought that armed with `build` I might have better luck

**Comment by rouson** [comment]
I'll have the xz --> bz2 switch complete shortly. I just tested it and it works fine for m4.  My m4 build completed inside a recent download of the latest Lubuntu disk image, which I booted inside a VirtualBox virtual machine and did a few minimal installs:

    sudo apt-get install git
    sudo apt-get install vim
    sudo apt-get install make
    sudo apt-get install ftp
    sudo apt-get install g++

I also installed the Intel Fortran compiler (which by the way is free for use in contributing to open-source projects if the contributions are not compensated monetarily), but hopefully the Intel installation didn't provide anything that made the m4 build work.  I think all that was required are the above apt-get installations (modulo git and vim).

**Comment by zbeekman** [comment]
yes my problem is  I'm on RHEL 5 with an old kernel and glibc. It seems my  `ld` doesn't like dwarf v4 and can only handle dwarf v2... still investigating.

**Comment by zbeekman** [comment]
got m4 built via 

```
./configure --prefix=/my/install/path CC="$(which gcc) -gdwarf-2 -gstrict-dwarf" CXX="$(which g++) -gdwarf-2 -gstrict-dwarf"
```

I don't know if it's reasonable to try to support systems as out of shape as my lab workstation, but I'll keep documenting the steps I needed to take here, just in case they are ever useful.

**Comment by rouson** [comment]
As long as we can detect the need for this robustly, it doesn't seem hard to support this.

**Comment by zbeekman** [comment]
It seems like I was able to successfully compile all the gcc-5.3 pre-reqs but now it's failing on the GCC build.

I think my issue is that the `/bin/ld` on my workstation is super old and can't understand some of the newer output of gcc 4.8.3 (being used to attempt to compiler 5.3 and prereqs) I need to hunt around and see if there's a way that I can use a different `ld`, like the one used to compile gcc-4.8.3 (stored in a mounted NFS drive, but seems to compile and run code without problems....)

**Comment by zbeekman** [comment]
OK, it looks like `ld` is part of GNU binutils. I'm going to see if I can compile and update that.... wish me luck.

**Comment by zbeekman** [comment]
> I'll have the xz --> bz2 switch complete shortly. I just tested it and it works fine for m4. My m4 build completed inside a recent download of the latest Lubuntu disk image

It [looks like](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build#L229-L241) `build` is still fetching .xz files. I was---perhaps mistakenly---under the impression that PR #133 had content to address this. I'd be happy to try to tackle this today, but I just wanted to check in with @rouson first.

**Comment by rouson** [comment]
That's bizarre.  I definitely made the xz -> bz2 switch and tested it. I'm not sure what happened, but feel free to switch anything that still shows up at tar.xz. 

Damian

**Comment by zbeekman** [comment]
I know that, for some reason, you started one PR, then threw it out and submitted a different one. Perhaps those changes slipped through the cracks there.... I'll see what I can do.

**Comment by rouson** [comment]
@zbeekman, an excellent deduction.I'll be out for most of the evening but will plan to fix this tonight if I'm not too tired and you haven't already committed a fix.  All that is needed is to change a few file extensions in lines [231](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build#L231)-[236](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build#L236) of the [build](https://github.com/sourceryinstitute/opencoarrays/blob/master/install_prerequisites/build) script and then to test the script for each change.  The test only needs to be run up to the point where the tar ball downloads so it should be only a few minutes of work.
