### ISSUE TITLE
Copyright  2015 --> 2016 update

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#130]
A lot of references to 2015 need to be updated now that its 2016. I have posted a gist of all of them, found using [ag](https://github.com/ggreer/the_silver_searcher) a faster version of [ack](http://beyondgrep.com/). If you download the file in the gist linked below, you can open it in Emacs and then `M-x compilation-mode` to go visit each file and line mentioned. YMMV with other editors.

https://gist.github.com/zbeekman/a09504020f6689e5a43d

**Comment by rouson** [comment]
Thanks for doing this.  I suppose we'll need to do a refresh annually.  I don't use emacs, but I did take a look at the file online.

**Comment by zbeekman** [comment]
@rouson Who said I was doing it?! :stuck_out_tongue_closed_eyes: 

However, I would be happy to do it, it should be pretty quick. A question for you though:

 Should I update the copyright year for source code, etc. files that have not been edited yet in the new year? Or should I just update everything?

**Comment by rouson** [comment]
@zbeekman  Thanks for letting me volunteer you!  I honestly don't have a clue what the appropriate practice is.  I generally assume that it's best to update the date on files only if the file has an internal copyright date range that does not extend through the year of the file's time stamp.  My theory is that it matches the practice for copyrighting books, which I think only get updated when a new edition is published.  But this is guesswork for me.  Maybe there's a good reference online the describes the best practice.  I suppose this could be another "git hook" -- assuming that's the right terminology and it's feasible to implement.

**Comment by zbeekman** [comment]
I'll ponder the git-hook issue... And try to google/ask around

**Comment by szaghi** [comment]
@zbeekman please, share such a git-hook if you find any :smile:

**Comment by zbeekman** [comment]
It seems that the convention is to update only when the file in question is edited. The following command will give a list of files and lines containing the string '2015' that have changed since 2015-12-31:

```
git grep --name-only 2015 $(git log --pretty=format:%H --since="12/31/2015") | cut -d : -f 2 | sort | uniq | while read line; do grep -Hn 2015 $line; done
```

A number of these have already been taken care of.

**Comment by rouson** [comment]
Nice.  Thanks!
