### ISSUE TITLE
OpenCoarrays installation bug issue

### ISSUE THREAD

**Issue by MichaelSiehl** [sourceryinstitute/opencoarrays#140]
Hi,
I got another installation bug on a fresh Linux Ubuntu 14.04 LTS 64bit, shared memory. I attach the install-opencoarrays.log file.
[install-opencoarrays.txt](https://github.com/sourceryinstitute/opencoarrays/files/120698/install-opencoarrays.txt)

cheers
Michael

**Comment by zbeekman** [comment]
Is my understanding correct that the failure occurs while installing GCC 5.3, during the configure phase?

**Comment by rouson** [comment]
@zbeekman, Not quite.  The configure step completes.  The failure happens during the build phase.  I'll send an email to the gfortran developers sometime today.

**Comment by rouson** [comment]
This message is a test.  Please ignore this message.  I will delete it from the Issues page once it appears.

**Comment by rouson** [comment]
@MichaelSiehl, could you tell us what steps you took before running the OpenCoarrays installer and what version of gcc/g++ was installed before launching the OpenCoarrays installer? 

In the discussion thread for issue #125, I reported success 9 days ago with a fresh download of the last Lubuntu Linux disk image (which is based on Ubuntu 15.10).  The only steps I took before installing OpenCoarrays were

    sudo apt-get install git
    sudo apt-get install vim
    sudo apt-get install make
    sudo apt-get install ftp
    sudo apt-get install g++

where of course the vim and git installations should not be necessary.  The last step above resulted in apt-get installing g++ 5.2.1. 

Before installing OpenCoarrays, I also installed the Intel Fortran compiler, but hopefully the Intel installation didn't provide anything that influenced whether OpenCoarrays would build.

**Comment by zbeekman** [comment]
I uploaded [the install log as a gist](https://gist.github.com/c64a2b99ed8dc8438153) so we can more easily reference individual lines.

**Comment by rouson** [comment]
Searching [install-opencoarrays.txt](https://github.com/sourceryinstitute/opencoarrays/files/120698/install-opencoarrays.txt) on the string "GNU C", it appears that every check for the GNU C compiler succeeds, but every check for the GNU C++ compiler fails.  I suspect g++ is missing or too old or something.  It's a requirement for building gfortran. Here are the relevant lines:

    $ grep -n "GNU C" install-opencoarrays.txt 
    95:checking whether we are using the GNU C compiler... yes
    251:checking whether we are using the GNU C Library >= 2.1 or uClibc... yes
    2242:checking whether we are using the GNU C compiler... yes
    2249:checking whether we are using the GNU C++ compiler... no 
    2428:checking whether we are using the GNU C Library >= 2.1 or uClibc... yes
    3369:checking whether we are using the GNU C compiler... yes
    3453:checking whether we are using the GNU C compiler... (cached) yes
    3457:checking whether we are using the GNU C++ compiler... no
    4051:checking whether we are using the GNU C compiler... yes
    4054:checking whether we are using the GNU C++ compiler... no
    4176:checking whether we are using the GNU C compiler... yes
     5590:checking whether we are using the GNU C compiler... yes
     5679:checking whether we are using the GNU C++ compiler... no
     6414:checking whether we are using the GNU C compiler... yes
     6753:checking whether we are using the GNU C compiler... yes
     6759:checking whether we are using the GNU C++ compiler... no
     7223:checking whether we are using the GNU C compiler... yes
     7308:checking whether we are using the GNU C compiler... yes
     8001:checking whether we are using the GNU C compiler... yes
     8031:checking whether we are using the GNU C Library 2.1 or newer... yes
     8123:checking whether we are using the GNU C compiler... yes
     8126:checking whether we are using the GNU C++ compiler... no

Damian

**Comment by MichaelSiehl** [comment]
You are right, g++ was not installed. I will retry shortly on another fresh Ubuntu.

**Comment by rouson** [comment]
@MichaelSiehl, thanks for letting us know.  I'll close this issue. I recently created issue #141 to ensure that we address this in an upcoming release.
