### ISSUE TITLE
Add automatic use of package management if detected by the OpenCoarrays installer

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#141]
Recent tests suggest that [install.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/install.sh) will successfully install OpenCoarrays and any required prerequisites on a fresh download of Lubuntu Linux 15.10 after the following steps:

    sudo apt-get install make
    sudo apt-get install ftp
    sudo apt-get install g++

If wget is not present, then the following will also be needed:

    sudo apt-get install wget

A future release of install.sh should check for common package management software (e.g., apt-get, yum, port, or brew) and, if found, use the package manager to install the make, ftp, g++, and wget.

**Comment by zbeekman** [comment]
I will also note that Homebrew and the Linuxbrew fork have a tap [Homebrew/bundle](https://github.com/Homebrew/homebrew-bundle) which allows you to specify dependencies/packages in a `Brewfile` like Ruby's `Gemfile` or Pythons `requirements.txt` which may all be installed with a simple `brew bundle`. Additionally Linuxbrew lives in userland, so no sudo is required.

**Comment by rouson** [comment]
The fact that sudo is not required is HUGE.  We have to keep the barriers to installation as low as conceivably possible.  Many users will be installing on systems on which they do not have sudo privileges. Let's talk about this more on Tuesday's call.

**Comment by zbeekman** [comment]
@rouson Should we close this issue as a won't fix/implement? It seems our installation logic works quite well right now, and other alternative means of installing OpenCoarrays are in the works... Package managers usually require `sudo` so my thinking on this matter is that either the user needs to do a user-space install (non-sudo), and we need to help them get and build the prerequisites in user land, OR they have SUDO and a functioning package manager, so they can just install all of OpenCoarrays via their package manager.... We have support for some package managers, but obviously should try to expand this.

I'm going to close this issue, if you feel like it is still worthwhile to pursue, then feel free to re-open it.

**Comment by rouson** [comment]
LGTM
