### ISSUE TITLE
Linux brew for Travis-CI dependencies

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#150]
I am going to look into using [LinuxBrew](http://linuxbrew.sh) to manage Travis-CI dependencies. This may allow us to compile bottled GCC 5.3 and 5.4 in an ubuntu VM and then download and install from the bottle on Travis-CI. Right now using the whitelisted packages and PPAs on ubuntu to get non-ancient gfortran are a real pain.

**Comment by rouson** [comment]
:+1:

**Comment by zbeekman** [comment]
I've revised my thinking on this matter, and I'm not entirely sure Linuxbrew is stable/mature enough to fit the bill here... I think that newish compilers are available with enough frequency through the additional PPAs, and short of that, a docker container would probably be a better alternative if we're going to roll our own solution
