### ISSUE TITLE
coverage for shell scripts?

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/OpenCoarrays#152]
I'm wondering if it might be useful to have coverage data for the various shell scripts we use, whether it's the installation shell scripts, or the caf wrapper scripts. This may help us narrow down bugs more quickly if we can identify which portions of scripts are executed under the CI test environment and which are not executed. Do you think this would be a worthwhile addition?

Two options for this are [kcov](https://github.com/SimonKagstrom/kcov) and it's simpler, python only, predecessor, [shcov](https://github.com/SimonKagstrom/shcov). I know at least [kcov can output coverage data](http://simonkagstrom.github.io/kcov/index.html) in the [Cobertura XML](http://cobertura.sf.net/) format, which [codecov.io can understand](https://github.com/junit-team/junit/pull/1002#issuecomment-65936636).

**Comment by rouson** [comment]
Absolutely!

**Comment by zbeekman** [comment]
It seems like kcov has made progress towards being functional on OS X. It might be worth looking into this again.

**Comment by zbeekman** [comment]
I'm going to close this as won't fix. kcov and shcov are prohibitively challenging to install during our CI workflow.
