### ISSUE TITLE
Non-sudo OFP installation

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#154]
The caffeinate-opencoarrays branch now contains a first-draft [install-ofp.sh](https://github.com/sourceryinstitute/opencoarrays/blob/caffeinate-opencoarrays/install_prerequisites/install-ofp.sh) script for installing the Open Fortran Parser (OFP) and its prerequisites aterm, sf2-bundle, and Stratego/XT.  The script currently installs only on OS X and only by downloading and moving binaries into /opt because one or more binaries contains explicit references to the /opt directory.  

A future version of the OFP installation script should allow for building from OFP and its prerequisites from source in order to facilitate
1. Installation of OFP and its prerequisites into directories other than /opt and
2. Installation on platforms other than OS X. 

A preliminary draft of a script for building the OFP prerequisites from source is in  [installStrategoXT.sh](https://github.com/sourceryinstitute/opencoarrays/blob/caffeinate-opencoarrays/install_prerequisites/installStrategoXT.sh), which currently builds aterm successfully but fails on building sf2-bundle on OS X and Linux.  Once this script can be fixed, building OFP is trivial and as detailed [here](https://github.com/sourceryinstitute/opencoarrays/blob/caffeinate-opencoarrays/install_prerequisites/install-ofp.sh#L197).

**Comment by zbeekman** [comment]
> Installation on platforms other than Linux.

Did you mean other than OS X?

**Comment by rouson** [comment]
Sent from my iPhone

> On Mar 3, 2016, at 7:56 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> Installation on platforms other than Linux.
> 
> Did you mean other than OS X?
> 
Yes.

**Comment by zbeekman** [comment]
I updated your comment to reflect this

**Comment by rouson** [comment]
@rasmussn, I'll remove this issue from blocking the 2.0 release targeted for May 30 and assume we'll work on it afterward.

**Comment by scrasmussen** [comment]
Hi, is anyone working on a StrategoXT installation script for Linux users? If no one is and you guys don't mind I'd like to help with that. It'll target the non-binary package installation of aterm, sdf2-bundle, and StrategoXT since I have experience with that problem. I'll attempt to code in a similar style like you guys have done in [install-ofp.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/install-ofp.sh) so as to keep things consistent.

**Comment by zbeekman** [comment]
@scrasmussen That would be wonderful help. I think the rest of us are somewhat flummoxed by the current state of StrategoXT... Any progress in being able to build from source on Linux and OS X would be much appreciated...

**Comment by scrasmussen** [comment]
Glad to hear I can be of some help, the StrategoXT installation can be quite a pain at times... I'll get started on it right away.

**Comment by rouson** [comment]
@scrasmussen  Bravo!  Your offer of assistance is very much appreciated. This is a high-priority item. Sometime in the coming weeks, we will release version 2.0.0 and the option to use OFP for source transformation will be one of the most significant new features.  That feature is currently enabled only on the caffeinate-opencoarrays branch.  Currently, we can only offer to install OFP on OS X and even then only for users with sudo privileges because the prerequisite binaries have to go in /opt.  Adding Linux along with an ability to build the OFP prerequisites from source would be a major step forward.
