### ISSUE TITLE
Arch Linux package build

### ISSUE THREAD

**Issue by szaghi** [sourceryinstitute/opencoarrays#16]
Hi all,

I am starting a new adventure with OpenCoarrays. My favorite environment is [Arch Linux](https://www.archlinux.org/), it being a GNU Linux distribution. I found an *aur* package build for easily installing OpenCoarrays, that is https://aur.archlinux.org/packages/opencoarrays/

It seems up-to-date (presently the build is the v1.1.0-1 github hosted), thus (due to my laziness...) I wish to use it, but reading your installation [instructions](https://github.com/sourceryinstitute/opencoarrays/blob/master/INSTALL.md#linux) there is no mention to this *aur* package, thus I guess this is an unofficial package. 

Can I safely use this *aur* build? Are you aware about it?

Thank you very much for this great project!

**Comment by rouson** [comment]
I have never heard of Arch Linux or our so it's great that they are redistributing OpenCoarrays. Please try it and report your experience to us.  

Also, if you happen to have any advice on how we could get OpenCoarrays to be installed by apt-get or yum, please let us know.   

Lastly, could you please contact the maintainer of the OpenCoarrays air package to ask whether they are able to provide us with download statistics. These are an important component of future funding proposals.

Damian

**Comment by szaghi** [comment]
@rouson 

Ok, I am trying the AUR way. Unfortunately, I am now on Arch, thus I cannot help with deb (apt like) or rpm (yum like) packages. 

I try to contact the AUR maintainer to ask give you some feedback reports.

I am leaving this issue open just to report the maintainer replay.

Stefano

**Comment by szaghi** [comment]
@rouson Just a remark: I was in doubt to use this AUR package build because it is based on OpenMPI rather than MPICH as you suggest. I am trying to contact the maintainer to ask also why he/she selects OpenMPI.

**Comment by szaghi** [comment]
@rouson 

I have asked the maintainer to help you for the required statistics, I hope in a quick replay, see it here https://aur.archlinux.org/packages/opencoarrays/#news

Stefano

**Comment by sourceryinstitute** [comment]
Thanks!

D

**Comment by sourceryinstitute** [comment]
My guess is OpenMPI will be fine. We ran into one problem with OpenMPI when one attempts to overwrite a coarray with itself:

x[1] = x[1]

I don't recall any other issues and I think the above issue was resolved. @afanfa can confirm.  I think MPICH might perform better too, but I wouldn't worry much about this. Just let us know if you encounter problems. 

D

**Comment by szaghi** [comment]
:+1:

**Comment by szaghi** [comment]
After setting up MPICH (I use module tool to manage many MPI libraries...) the AUR package is installed correctly (that in Arch's world means download and compile, do not rely on binary packages):

```shell
stefano@zaghi(11:25 AM Tue Oct 20)
~ 35 files, 27Mb
→ caf -v

OpenCoarrays Coarray Fortran Compiler Wrapper (caf version 1.1.0)
Copyright (C) 2015 Sourcery, Inc.

OpenCoarrays comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of OpenCoarrays under the terms of the
BSD 3-Clause License.  For more information about these matters, see
the file named COPYRIGHT-BSD3.
```

**Comment by szaghi** [comment]
The simple workflow [example](https://github.com/sourceryinstitute/opencoarrays/blob/master/GETTING_STARTED.md#a-sample-basic-workflow) compiles and runs smoothly:

```shell
stefano@zaghi(11:25 AM Tue Oct 20)
~ 35 files, 27Mb
→ vim tally.f90

stefano@zaghi(12:05 PM Tue Oct 20)
~ 36 files, 27Mb
→ caf tally.f90 -o tally

stefano@zaghi(12:05 PM Tue Oct 20)
~ 37 files, 27Mb
→ cafrun -np 4 ./tally
 Test passed
```

**Comment by szaghi** [comment]
@rouson From James (the maintainer of AUR package)

> I am not sure about exact download statistics, but in the information above there is a "votes" and "popularity" section.

He refers to the package details that now shows
```
Votes:	1
Popularity:	0.000000
```
Obviously the first vote is mine :-)

Feel free to close this issue. I will report my feedbacks in other more specific topics if necessary.

**Comment by rouson** [comment]
Thanks for investigating this!

:D

**Comment by szaghi** [comment]
@rouson you are welcome! 

P.S. if you want to increase the aur package popularity maybe you can cite it into the install instruction.

**Comment by rouson** [comment]
> On Oct 20, 2015, at 8:52 PM, Stefano Zaghi <notifications@github.com> wrote:
> 
> @rouson <https://github.com/rouson> you are welcome!
> 
> P.S. if you want to increase the aur package popularity maybe you can cite it into the install instruction.
> 
> 

Great idea!

D

**Comment by sourceryinstitute** [comment]
> On Oct 20, 2015, at 8:52 PM, Stefano Zaghi <notifications@github.com> wrote:
> 
> @rouson <https://github.com/rouson> you are welcome!
> 
> P.S. if you want to increase the aur package popularity maybe you can cite it into the install instruction.
> 
> 

I’m finally editing the installation instructions to mention Arch.  I will be posting release 1.2.0 shortly that will for the first time include an installation script that attempts to download, build, and install all prerequisites if necessary, and build OpenCoarrays using CMake.  On my Linux and OS X platforms, all of this happens after simply typing “./install.sh” at the top level in the source tree.

D
