### ISSUE TITLE
FoBiS now supports OpenCoarrays

### ISSUE THREAD

**Issue by szaghi** [sourceryinstitute/opencoarrays#17]
Hi all,

this is just to inform you that [FoBiS](https://github.com/szaghi/FoBiS) supports automatic building of complex problem by means of OpenCoarrays (for the moment with GNU gfortran back-end).

FoBiS OpenCoarrays enabled version is v1.7.5+.

Feel free to close this issue as soon as you will be aware of this.

My best regards.

P.S. the OpenCoarrays support is not still documented into FoBiS main documentation: it will be amended soon.

**Comment by rouson** [comment]
Great news.  Thanks for the update.  I tend to learn best from video tutorials. Any chance you might put together a short presentation and record it.  I think most presentation software supports this these days, including possibly OpenOffice: https://www.youtube.com/watch?v=LtL9tq0gbjk.  I just found this link on a quick search and  haven't viewed all of it.

**Comment by szaghi** [comment]
Hi Damian, yes some screencasts will come soon, however my spoken English is so bad that I will not add any audio sources, maybe I will try to add subtitles :-)

**Comment by rouson** [comment]
Fascinating.  I know someone who used a speech synthesizer to generate the spoken English automatically from written English.  I never realized why he did that until just now.  He’s not a native English speaker and was probably concerned about his accent.  You might consider speech synthesis — although you probably speak English much better than most native English speakers speak any other language!  

I often find that non-English speakers will say they don’t speak English and yet are quite fluent in conversation.  Conversely I find that many native English speakers (well, Americans in particular) will say they speak another language and can barely hold a conversation in that language.  I guess it’s all a matter of perspective. 

:D

**Comment by szaghi** [comment]
:-) Unfortunately, my spoken English is really bad (I have few occasions to exercise with native English people), but the synthetic-voice alternative is cool... it will seem that Stephen Hawking is illustrating the examples :-)
