### ISSUE TITLE
undefined reference to `_gfortran_caf_co_reduce'

### ISSUE THREAD

**Issue by WeiLiPenguin** [sourceryinstitute/opencoarrays#2]
I build the libcaf_mpi by the cmake, I can run some of the test, but when I use co_reduce, it can not find it. 
I try:
```bash
$ strings libcaf_mpi.a |grep -i reduce
co_reduce_1
MPI_Allreduce
MPI_Reduce
```
but 
```bash
$ strings libcaf_mpi.a |grep -i sum
_gfortran_caf_co_sum
CO_SUM failed with %s
_gfortran_caf_co_sum
```
Is that means I did not compile the libcaf_mpi.a in a right way?

**Comment by sourceryinstitute** [comment]
Please email questions to opencoarrays@googlegroups.com.  I'm not sure that anyone else is monitoring issues posted on GitHub and I don't know the answer to your question.  Most likely Alessandro Fanfarillo or Tobias Burnus will be able to help you.  They both subscribe to the aforementioned mailing list.

**Comment by sourceryinstitute** [comment]
Hi We Li,

FYI, I made some commits yesterday that significantly simplify the process for building with CMake.  I recommend pulling these changes or doing a fresh clone and building again. The new build process is described in an updated INSTALL file in the top directly.  It should now be possible to build by issuing commands such as the following in a bash shell anywhere completely _outside_ of the OpenCoarrays folder:

mkdir build-opencoarrays
cd build-opencoarrays
CC=mpicc FC=mpif90 cmake <path-to-opencoarrays>  -DCMAKE_INSTALL_PREFIX=${PWD}
make
make install
ctest

where of course you can change the install prefix to the directory of your choice.  I tested the new set up on OS X and Lubuntu.  Please let me know if it doesn’t work for you.  

Damian 
510-600-2992 (mobile)

**Comment by WeiLiPenguin** [comment]
Hi, 
I  used your new commits follow the INSTALL file, same as I mentioned, can not find any string with '_gfortran_caf_co_reduce' in the libcaf_mpi.a. could you please, check it for me, or try explain to me where I can find them in the src?
Thanks!

**Comment by sourceryinstitute** [comment]
Hopefully you saw the email Alessandro just sent to the OpenCoarrays Google Group.  CO_REDUCE is not yet supported.

Damian 
510-600-2992 (mobile)

**Comment by WeiLiPenguin** [comment]
Thank you! just saw it.
Should be closed this issue, or leave it until Alessandro implement it. also thanks to Alessandro.

**Comment by sourceryinstitute** [comment]
You can leave it open.  Alessandro agrees that having issues submitted via GitHub is a good system.

D

**Comment by afanfa** [comment]
Hi,

today I pushed a partial support for co_reduce (it works only for integer). I should be able to cover almost every datatype in the next few days. I also found a bug in GFortran, I posted a patch on the gfortran mailing list but I cannot estimate when (ad if) it will be merged in the trunk.

**Comment by afanfa** [comment]
The GFortran patch has been merged into the trunk and the GCC5.x branch. The library supports co_reduce for integers, logical,  reals (single and double precision).
