### ISSUE TITLE
Missing ctest when building with cmake slightly differently

### ISSUE THREAD

**Issue by mathomp4** [sourceryinstitute/opencoarrays#203]
All,

This might be a "Matt is not great at cmake" issue, but... Namely, I didn't want to install my build of OpenCoarrays in a directory in the src directory (as INSTALL.md shows), so I did this, following along with INSTALL.md:

```
  $ tar xvzf OpenCoarrays-1.6.0.tar.gz
  $ cd OpenCoarrays-1.6.0
  $ mkdir BUILD-gfortran_6.1.0-openmpi_1.10.2
  $ cd BUILD-gfortran_6.1.0-openmpi_1.10.2
  $ env CC=mpicc FC=mpifort cmake .. -DCMAKE_INSTALL_PREFIX=/ford1/share/gmao_SIteam/OpenCoarrays/1.6.0/gcc_6.1.0-openmpi_1.10.2
  $ make
  $ ctest
  $ make install
```

Well, I tried to. After I issued the `make` (and `make install`), `ctest` was nowhere to be found:

```
(407) $ find /ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2 -iname '*ctest*'
/ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2/CTestTestfile.cmake
(408) $ find /ford1/share/gmao_SIteam/OpenCoarrays/1.6.0/gcc_6.1.0-openmpi_1.10.2 -iname '*ctest*'
(409) $
```

Now, if I build with `-DCMAKE_INSTALL_PREFIX=${PWD}`, I do get `ctest` so there must be some magic I'm missing.

I will say, though, that caf and cafrun do seem to work. That's a plus!

(Also, as an aside, if I build with `${PWD}`, `ctest` fails in the navier test much like Issue #42. If I figure out this cmake issue, I might reopen or something an Issue on that.)

**Comment by zbeekman** [comment]
Hi @mathomp4,

First of all, `ctest` is a program distributed with CMake. So I'm a bit confused as to why you're looking for it with `find`... It should be installed in `/usr/local/bin` or similar. Try `which ctest` or `type -a ctest`... It shouldn't matter which install prefix you use...

Secondly, a number of tests in our test suite fail when building with OpenMPI, depending on your system. (If you have enough cores available, then OpenMPI *should* be able to run all the tests without issue...) A number of our tests intentionally over subscribe, and MPICH handles this just fine, but, even with `--oversubscribe` and making a hosts file, etc. OpenMPI doesn't seem to like this, and will fail non-deterministically during the execution of some of the oversubscribed tests. I am currently investigating this and working on a way for the tests to detect OpenMPI and avoid oversubscribing when OpenMPI is in use.

I believe we only "officially" support MPICH, as it is what we use and test with most of the time, but OpenMPI should work fine, provided you don't oversubscribe, and it is a recent enough version to support the MPI-3 features used by OpenCoarrays.

**Comment by zbeekman** [comment]
Let me know how you make out with CTest, and if there is anything I can do to help you sort out the issues you're encountering...

**Comment by mathomp4** [comment]
Well, I'll be. Mea culpa. It turns out *cmake* itself didn't install correctly on one machine but did on another. I did the ${PWD} version on the "good" machine and the full-path on the other (one is RHEL6 the other RHEL7 and I have to build canonical packages on the older box).

Time to make a cmake module and use that so everyone is happy.

**Comment by mathomp4** [comment]
Oh. Nuts. Here is my issue:

```
(442) $ ctest
Test project /ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2
      Start  1: initialize_mpi
 1/23 Test  #1: initialize_mpi ...................   Passed    0.18 sec
      Start  2: register
 2/23 Test  #2: register .........................   Passed    0.14 sec
      Start  3: register_rename_me
 3/23 Test  #3: register_rename_me ...............   Passed    0.13 sec
      Start  4: register_rename_me_too
 4/23 Test  #4: register_rename_me_too ...........   Passed    0.13 sec
      Start  5: allocate_as_barrier
 5/23 Test  #5: allocate_as_barrier ..............   Passed    1.13 sec
      Start  6: allocate_as_barrier_proc
 6/23 Test  #6: allocate_as_barrier_proc .........   Passed    1.13 sec
      Start  7: get_array
 7/23 Test  #7: get_array ........................   Passed    0.17 sec
      Start  8: send_array
 8/23 Test  #8: send_array .......................   Passed    0.19 sec
      Start  9: get_with_offset_1d
 9/23 Test  #9: get_with_offset_1d ...............   Passed    0.12 sec
      Start 10: whole_get_array
10/23 Test #10: whole_get_array ..................   Passed    0.13 sec
      Start 11: strided_get
11/23 Test #11: strided_get ......................   Passed    0.13 sec
      Start 12: co_sum
12/23 Test #12: co_sum ...........................   Passed    0.13 sec
      Start 13: co_broadcast
13/23 Test #13: co_broadcast .....................   Passed    0.15 sec
      Start 14: co_min
14/23 Test #14: co_min ...........................   Passed    0.14 sec
      Start 15: co_max
15/23 Test #15: co_max ...........................   Passed    0.14 sec
      Start 16: syncall
16/23 Test #16: syncall ..........................   Passed    1.83 sec
      Start 17: syncimages
17/23 Test #17: syncimages .......................   Passed    0.91 sec
      Start 18: duplicate_syncimages
18/23 Test #18: duplicate_syncimages .............   Passed    0.21 sec
      Start 19: co_reduce
19/23 Test #19: co_reduce ........................   Passed    0.16 sec
      Start 20: hello_multiverse
20/23 Test #20: hello_multiverse .................   Passed    0.13 sec
      Start 21: coarray_burgers_pde
21/23 Test #21: coarray_burgers_pde ..............   Passed    0.14 sec
      Start 22: co_heat
22/23 Test #22: co_heat ..........................   Passed    0.89 sec
      Start 23: coarray_navier_stokes
23/23 Test #23: coarray_navier_stokes ............***Failed  Required regular expression not found.Regex=[Test passed.
]  0.07 sec

96% tests passed, 1 tests failed out of 23

Total Test time (real) =   8.61 sec

The following tests FAILED:
	 23 - coarray_navier_stokes (Failed)
Errors while running CTest
```

**Comment by mathomp4** [comment]
Should I open a new issue for this?

**Comment by afanfa** [comment]
Hi @mathomp4 , I have seen this problem with the coarray_navier_stokes test several times (even with MPICH) but I haven't had enough time to investigate.
I think there is a problem with that specific code, not with your installation.

**Comment by zbeekman** [comment]
This could also be cause by a problem with the build system that I fixed in https://github.com/sourceryinstitute/opencoarrays/commit/5e816e4144fab02674bd498ecac9187b40785606 which has not yet made it into a release... we should have a release in the next few days.

**Comment by mathomp4** [comment]
Okay, I see a few issues. One is that there are a couple tests that might just be too big for my 8-core build box:

```
16: Test command: /ford1/share/gmao_SIteam/MPI/openmpi-1.10.2-gcc-6.1.0/bin/mpiexec "-np" "32" "/ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2/src/tests/unit/sync/syncall"
16: Test timeout computed to be: 9.99988e+06
16:  Test passed.
16: --------------------------------------------------------------------------
16: A system call failed during shared memory initialization that should
16: not have.  It is likely that your MPI job will now either abort or
16: experience performance degradation.
16: 
16:   Local host:  janus.gsfc.nasa.gov
16:   System call: unlink(2) /tmp/openmpi-sessions-mathomp4@janus_0/47886/1/shared_window_4.janus
16:   Error:       No such file or directory (errno 2)
16: --------------------------------------------------------------------------
16/23 Test #16: syncall ..........................   Passed    1.93 sec
17: Test command: /ford1/share/gmao_SIteam/MPI/openmpi-1.10.2-gcc-6.1.0/bin/mpiexec "-np" "32" "/ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2/src/tests/unit/sync/syncimages"
17: Test timeout computed to be: 9.99988e+06
17:  Test passed.
17: --------------------------------------------------------------------------
17: A system call failed during shared memory initialization that should
17: not have.  It is likely that your MPI job will now either abort or
17: experience performance degradation.
17: 
17:   Local host:  janus.gsfc.nasa.gov
17:   System call: unlink(2) /tmp/openmpi-sessions-mathomp4@janus_0/48077/1/shared_window_4.janus
17:   Error:       No such file or directory (errno 2)
17: --------------------------------------------------------------------------
17/23 Test #17: syncimages .......................   Passed    0.83 sec
```

The other one is the navier job:
```
23: Test command: /ford1/share/gmao_SIteam/MPI/openmpi-1.10.2-gcc-6.1.0/bin/mpiexec "-np" "2" "/ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2/src/tests/integration/pde_solvers/navier-stokes/coarray_navier_stokes"
23: Test timeout computed to be: 9.99988e+06
23: --------------------------------------------------------------------------
23: mpiexec was unable to launch the specified application as it could not access
23: or execute an executable:
23: 
23: Executable: /ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-gfortran_6.1.0-openmpi_1.10.2/src/tests/integration/pde_solvers/navier-stokes/coarray_navier_stokes
23: Node: janus
23: 
23: while attempting to start process rank 0.
23: --------------------------------------------------------------------------
23: 2 total processes failed to start
23/23 Test #23: coarray_navier_stokes ............***Failed  Required regular expression not found.Regex=[Test passed.
]  0.07 sec
```
As that is only 2 processes, I figure that is something more fundamental.

**Comment by mathomp4** [comment]
@zbeekman I can confirm that 5e816e4 solves my navier issue.

**Comment by mathomp4** [comment]
And, actually, the other two '-np 32' failures are intermittent:

```
17: Test command: /ford1/share/gmao_SIteam/MPI/openmpi-1.10.2-gcc-6.1.0/bin/mpiexec "-np" "32" "/ford1/share/gmao_SIteam/src/OpenCoarrays-1.6.0/BUILD-inplace/src/tests/unit/sync/syncimages"
17: Test timeout computed to be: 9.99988e+06
17:  Test passed.
17/23 Test #17: syncimages .......................   Passed    0.82 sec

```

**Comment by zbeekman** [comment]
@mathomp4 glad to hear that the issues are more or less resolved... I just pushed https://github.com/sourceryinstitute/opencoarrays/commit/9aa434fc22c2a325797fb8aa38dc52a6c87a76ce which should resolve the OpenMPI over subscribed tests once it's merged. I think this is an OpenMPI bug, the same as https://www.open-mpi.org/community/lists/users/2016/04/28936.php

I'll close this ticket, reopen it if you feel anything is unresolved...

**Comment by zbeekman** [comment]
@mathomp4 We have just release 1.6.2 which includes the fixes to the issues surrounding erroneously trying to run the Navier-Stokes code on unsupported architectures, FYI
