### ISSUE TITLE
undefined reference to `_gfortran_caf_stop_str'

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/opencoarrays#207]
Please see this GCC PR:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71839

I now think there is something wrong with how OpenCoarrays
add symbols in user created libraries.

I build a static library with caf (-c -Wall -g -fbacktrace -fcheck-array-temporaries -O2).
Some OpenCoarrays symbols are added to it,
but not _gfortran_caf_stop_str, e.g.:

$ nm libcgpack.a |grep stop
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str

Is this as expected?

Then even giving the caf_mpi library explicitly to the linker, does not help:

caf -o testAAF.x testAAF.o testaux.o -L/panfs/panasas01/mech/mexas/lib -lcgpack -L/OpenCoarrays-1.6.0/opencoarrays-build/lib -lcaf_mpi
testAAF.o: In function `MAIN__':
/panfs/panasas01/mech/mexas/nobkp/cgpack/head/tests/testAAF.f90:101: undefined reference to `_gfortran_caf_stop_str'
collect2: error: ld returned 1 exit status
make: *** [testAAF.x] Error 1

Thanks

Anton

**Comment by afanfa** [comment]
Hi Anton,
which version of your library are you using? There are several versions on the repository.

**Comment by mexas** [comment]
I'm always using head. You'd want to use Makefile-bc3-oca.
Thank you for looking into this.
Anton

**Comment by afanfa** [comment]
Interesting, I can reproduce the problem, plus I've got undefined reference for caf_init and caf_finalize:
/tmp/ccTLbDkm.o: In function `MAIN__':
testAnton.f90:(.text+0xf): undefined reference to `_gfortran_caf_stop_str'
/tmp/ccTLbDkm.o: In function `main':
testAnton.f90:(.text+0x31): undefined reference to `_gfortran_caf_init'
testAnton.f90:(.text+0x5b): undefined reference to `_gfortran_caf_finalize'
collect2: error: ld returned 1 exit status

**Comment by afanfa** [comment]
Ok, I've found the problem. Your caf wrapper points to the right OpenCoarrays library when you compile your library, but not when you compile (and link) your actual program.
Using the following string:
mpif90 -fcoarray=lib testAnton.f90 -L. -lcgpack -L /path/to/opencoarrays/src/mpi -lcaf_mpi -o anton
I don't get any errors.

**Comment by mexas** [comment]
Sorry, that's not the issue.
The error occurs if my library is *relocated*,
e.g. if I put it under ~/lib/, and try to link to its new location using -L ~/lib/.

If the library stays where it was built, I see no issue:

caf -c testAAF.f90 -Wall -I. -I/panfs/panasas01/mech/mexas/mod -g -fbacktrace -fcheck-array-temporaries -O2 
caf -o testAAF.x testAAF.o testaux.o -L.. -lcgpack -L/panfs/panasas01/mech/mexas/OpenCoarrays-1.6.0/opencoarrays-build/lib -lcaf_mpi

But I get the error if I put the library somewhere else:

caf -c testAAF.f90 -Wall -I. -I/panfs/panasas01/mech/mexas/mod -g -fbacktrace -fcheck-array-temporaries -O2 
caf -o testAAF.x testAAF.o testaux.o -L/panfs/panasas01/mech/mexas/lib -lcgpack -L/panfs/panasas01/mech/mexas/OpenCoarrays-1.6.0/opencoarrays-build/lib -lcaf_mpi
testAAF.o: In function `MAIN__':
/panfs/panasas01/mech/mexas/nobkp/cgpack/head/tests/testAAF.f90:101: undefined reference to `_gfortran_caf_stop_str'

However, I just discovered, that if I switch the order of the libraries, then it does work:

caf -c testAAF.f90 -Wall -I. -I/panfs/panasas01/mech/mexas/mod -g -fbacktrace -fcheck-array-temporaries -O2 
caf -o testAAF.x testAAF.o testaux.o -L/panfs/panasas01/mech/mexas/OpenCoarrays-1.6.0/opencoarrays-build/lib -lcaf_mpi -L/panfs/panasas01/mech/mexas/lib -lcgpack
caf -c testAAG.f90 -Wall -I. -I/panfs/panasas01/mech/mexas/mod -g -fbacktrace -fcheck-array-temporaries -O2 

So the opencoarrays library must come first, followed by the user library?
Why would that be?
Is it expected that opencoarray symbols are added to the user library built with opencoarrays?
In this case, why do I need to link against the opencoarrays library?
It would be sufficient to link just against the user library built with opencoarrays?

Indeed, if I don't move my library, and leave it where it was built,
I can successfully build all tests without linking to the opencoarrays lib
explicitly, i.e.:

caf -c testACB.f90 -Wall -I. -I/panfs/panasas01/mech/mexas/mod -g -fbacktrace -fcheck-array-temporaries -O2 
caf -o testACB.x testACB.o testaux.o -L.. -lcgpack 

I still think something is not right.

Thanks

Anton

**Comment by zbeekman** [comment]
Interesting issue! Back from vacation later today, I'll try to take a look soon. 

@mexas what OS are you on?

**Comment by afanfa** [comment]
Hi Anton,
apparently I cannot reproduce the issue by switching the two libraries (it works for me either with OpenCoarrays placed as first or second library). Furthermore, I moved libcgpack from where I created it and I don't see any issue.
When you compile OpenCoarrays no linking action is performed (when I compile libcgpack I don't provide the path to OpenCoarrays, I just use -fcoarray=lib in order to parse correctly the coarray syntax). That's why you need to link against OpenCoarrays when you create your executable (static libraries don't link with other static libraries).

**Comment by mexas** [comment]
Alessandro
Please show the output from 
nm libcgpack.a |grep stop

Thanks
Anton

**Comment by afanfa** [comment]
alex@alex-Latitude-E7440:~/Documents$ nm libcgpack.a |grep stop
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str
                 U _gfortran_caf_error_stop_str

**Comment by mexas** [comment]
So what I can't understand is why _gfortran_caf_stop_str is not in my static library,
while _gfortran_caf_error_stop_str is.

Anton

**Comment by afanfa** [comment]
Because in your library you don't use STOP but only ERROR STOP.

**Comment by mexas** [comment]
ok, I think I got it.
Please don't close this issue yet.
Our cluster has just been shut down due to failed cooling.
I'll to double check this tomorrow and update the issue.

Many thanks!

Anton

**Comment by afanfa** [comment]
Sure, let us know how it goes.
Cheers,
Alessandro

**Comment by rouson** [comment]
@mexas, I haven't fully digested this whole thread so I hope the following comment is helpful and I apologize if it is not:

`error stop` halts all images
`stop` only halts whichever image executes the statement

Because error stop is inherently parallel (in the case of multi-image execution), it must be executed in the OpenCoarrays library, whereas stop is local to the executing image and need be implemented only in the compiler.

Damian

**Comment by mexas** [comment]
probably some misconfig. on my linux cluster.
I can work around it by putting caf_mpi before my library
on linking:

caf -o testACE.x testACE.o testaux.o -L/panfs/panasas01/mech/mexas/OpenCoarrays-1.6.0/opencoarrays-build/lib -lcaf_mpi -L/panfs/panasas01/mech/mexas/lib -lcgpack

I still get the error otherwise, but since you cannot reproduce it,
I have to conclude something is wrong my end.
Many thanks and please close this PR.

Anton
