### ISSUE TITLE
Update CMake minimum for better Fortran 2008 submodule support

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#210]
Sometime between versions 3.4.0 and 3.6.1, cmake support for features related to submodules improved.  I suggest we increment the minimum CMake requirement accordingly.  I will make a branch for this and submit a pull request soon.

**Comment by rasmussn** [comment]
OK, let me know.

-craig

**Comment by rouson** [comment]
I got this wrong.  I'm not sure what made it seem at one point that things had changed, but I've now confirmed that the relevant features are still unsupported by CMake 3.6.1 on OS X and inside the Sourcery Institute Linux virtual machine and on Cray Linux. I'll close this issue.
