### ISSUE TITLE
Build failure on Linux Lubuntu 12 and 16

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#214]
@zbeekman I've observed the same installation failure in two Linux Lubuntu virtual machines: one running Lunbuntu 12 and one running Lubuntu 16.  The one running Lubuntu 12 is available in the Sourcery Institute [store](https://www.sourceryinstitute.org/store).  The attached OpenCoarrays installation log file is attached showing that the installation terminates with the following error message:

[  1%] Building Fortran object src/mpi/CMakeFiles/caf_mpi.dir/__/extensions/opencoarrays.F90.o
f951: Fatal Error: Reading module ‘mpi’ at line 6 column 3: Expected right parenthesis
compilation terminated.
make[2]: *** [src/mpi/CMakeFiles/caf_mpi.dir/__/extensions/opencoarrays.F90.o] Error 1
make[1]: *** [src/mpi/CMakeFiles/caf_mpi.dir/all] Error 2
make: *** [all] Error 2

[install-opencoarrays.log.txt](https://github.com/sourceryinstitute/opencoarrays/files/455546/install-opencoarrays.log.txt)

**Comment by rouson** [comment]
I get the same error with OpenCoarrays release 1.6.2 on both Linux virtual machines also.

**Comment by rouson** [comment]
Closing as resolved.

**Comment by zbeekman** [comment]
So was this a false positive or how was it resolved?
