### ISSUE TITLE
Installer fails to pick up some long-form arguments 

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#216]
@zbeekman, the installer fails to detect the "--branch trunk" argument in the following:
```
./install.sh -p gcc --branch trunk
```
Presumably the problem is in [parse_command_line.sh](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/use-case/parse_command_line.sh).

**Comment by zbeekman** [comment]
hmmm I'll poke around.

**Comment by zbeekman** [comment]
@rouson is this happening on master? Or another branch?

**Comment by zbeekman** [comment]
I don't think there's any issue in parsing long arguments. I suspect that they just aren't getting passed correctly between different parts of the script, if there is an error. I confirmed that there's no issue in the parser by doing the following:

I added the info and exit statements in install.sh

```shell
### Validation (decide what's required for running your script and error out)
#####################################################################

[ -z "${LOG_LEVEL:-}" ] && emergency "Cannot continue without LOG_LEVEL. "

info "arg_p is ${arg_p:-}"

info "arg_b is ${arg_b:-}"

exit 0

# shellcheck disable=SC2154
if [[ "${arg_v}" == "${__flag_present}" || "${arg_l}" == "${__flag_present}" || ! -z "${arg_P:-${arg_U:-${arg_V:-${arg_D:-${arg_B}}}}}" ]]; then
   print_debug_only=7
   if [ "$(( LOG_LEVEL < print_debug_only ))" -ne 0 ]; then
     debug "Supressing info and debug messages: one of {-l, -v, -P, -U, -V, -D} present."
     suppress_info_debug_messages
   fi
fi
```

and this is the result:

```
517 20:59 IBB-MBP:opencoarraysCI:🍻 [master|…837⚑ 3] $ ./install.sh -p gcc --branch trunk
2016-09-12 01:01:52 UTC [     info] arg_p is gcc
2016-09-12 01:01:52 UTC [     info] arg_b is trunk
2016-09-12 01:01:52 UTC [     info] Cleaning up. Done
```

**Comment by zbeekman** [comment]
In terms of hunting this down it would be helpful to have a starting place where arg_b doesn't have the correct value and work backwards
