### ISSUE TITLE
pthreads interop question

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#220]
Hi @afanfa and @rouson,

Marco was wondering if he could safely use CAF with pthreads. Please see his initial question below. I don't foresee any issue, as long as the MPI implementation is interoperable, right?

> Hi, 
> I am an aerospace engineer from Milan, and I have a question about coarrays. 
> 
> In particular I wrote a fortran interface to pthread and I plan to use pthread with coarrays. Have you got any suggestion. Is there something to know about code portability?
> 
> Best regards,
> Mirco valentini

**Comment by afanfa** [comment]
There might be problems. Using OpenMP, my recommendation would be to avoid CAF statements withing OpenMP constructs. Pthreads are more general than OpenMP and bad things may happen.

**Comment by zbeekman** [comment]
Closing issue because due to inactivity.
