### ISSUE TITLE
Support Windows 10 builds

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#227]
Windows 10 includes an option to install a beta-version Windows Subsystem for Linux, which  is a full Ubuntu Linux image, obviating the need for virtualization or emulation.  I'm submitting this issue to track progress toward building OpenCoarrays inside the Windows 10 Subsystem for Linux.

Based on a fresh installation of Windows 10, I have verified that Microsoft's [instructions for installing Ubuntu](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) work.  After installing Ubuntu on Windows 10, the following script progresses to the point of downloading and uncompressing the [GCC 6.1.0 tar ball]():

```
#/bin/bash

sudo apt-get install g++  # As of October 2016, this installs gcc 4.8

# Install GCC prerequisites:
sudo apt-get install automake   # As of October 2016, this installs m4 1.4.17 and aclocal 1.14.1
sudo apt-get install flex       # As of October 2016, this installs flex 2.5.35
sudo apt-get install bison      # As of October 2016, this installs bison 3.0.2
sudo apt-get install texinfo    # This installs makeinfo as required for building GCC documentation
sudo apt-get install gfortran   # As of October 2016, this installs gfortran 4.8 
sudo apt-get install subversion # Required only for building an unreleased gfortran branch

# Launching the OpenCoarrays installer via `./install.sh` even with no arguments should progress
# through building GCC, MPICH, CMake, and then OpenCoarrays but it currently fails on MPICH.
# I show the CMake build step below only to record that it works:

tar xvzf OpenCoarrays-1.8.0.tar.gz
cd OpenCoarrays-1.8.0
./install.sh --package cmake

# The following step builds GCC 6.1.0 and then attempts to build MPICH and OpenCoarrays
./install.sh --yes-to-all

# To build an unreleased branch such as the trunk (currently 7.0.0), instead use
./install.sh --package gcc --install-branch trunk
```

I'll post more as the build progresses.   If this approach succeeds, we can drop the minimum required  [flex version](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/build-functions/set_or_print_default_version.sh#L33) and [bison version](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/build-functions/set_or_print_default_version.sh#L34) to those listed above.  

```
#### The steps below either didn't work or didn't provide sufficiently recent versions:
if [ ]; then
  echo "The above unconditional conditional statement that blocks broken steps didn't work"
  exit 1
  sudo apt-get install mpich      # Windows claims this is already installed but I can't find it
  sudo apt-get install cmake      # As of October 2016, this installs cmake 2.8 (we require >=3.4.0)
  ./install.sh --package automake # This installs aclocal 1.15 as required for building MPICH
  if [[ -z ${PATH} ]]; then
    PATH=${PWD}/prerequisites/installations/automake/1.15/bin/
  else
    PATH=${PWD}/prerequisites/installations/automake/1.15/bin/:${PATH}
  fi 
fi
```

**Comment by rouson** [comment]
So far, so good.  The installer has progressed through the GCC build, which succeeds but is exruciatingly long.  I didn't run the build continuously in one sitting and had to put the laptop to sleep several times so it's hard to estimate how long it took, but I'm guessing it was on the order of 8 hours, give or take a couple of hours.   @zbeekman, this probably makes the strongest case for having a binary payload -- at least for Windows.   Any chance of reviving that idea for the 2.0 milestone?

**Comment by zbeekman** [comment]
Hmmm.... a binary payload is an interesting idea... In the past, though, I think we were mostly talking about:

1. A self extracting install script (you can append a binary compressed tarball to a script that will extract the tarball from itself, then run an install script within the tarball
2. Homebrew and Linuxbrew "bottles" for OpenCoarrays

I actually was working on setting up automatic building of MPICH against the latest stable GCC via Homebrew, then uploading to bintray to host the binaries using Travis-CI, nightli.es and bintray. (This way I don't have to manually rebuild MPICH bottles to use for our Travis-CI overtime a stable GCC or MPICH is released or the "formula" is revised/patched-it will be taken care of automatically. Without the custom MPICH bottles, MPICH bottles distributed with Homebrew use clang as the C compiler.)

It is possible that we could do something similar with OpenCoarrays (pretty easy, could use Travis-CI, once the Homebrew/Linuxbrew formula is finalized) but GCC proves more challenging. In order to automate it, we would need to find an alternate CI provider, that won't time out the GCC builds. We could build latest GCC HEAD via homebrew/linuxbrew, and their bottles, and upload to bintray.

Another alternative, is to investigate @jlinford's ptpkg freeze capability for packaging binaries. I have yet to try this, so I don't know if it will suit our needs.

I'd be curious to see if you could install linuxbrew on Win10/Ubuntu

```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
PATH="$HOME/.linuxbrew/bin:$PATH"
echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
```

And then try something like:

```bash
brew install --HEAD --build-bottle gcc
```

**Comment by rouson** [comment]
@zbeekman,

I thought the GCC build would be the hardest part, but the MPICH build is failing with the error message below.  I think the problem is that apt-get installs automake-1.14.1; whereas MPICH appears to want 1.15.  I tried building automake-1.15, but that build fails too.  I'm wondering if linuxbrew could build MPICH 3.1.4 for me.  I'm also considering going with an earlier version of MPICH in case it accepts automake-1.14.1. @afanfa, if you could let me know how far back I can go with MPICH versions safely, that might be helpful.

```
CDPATH="${ZSH_VERSION+.}:" && cd /home/rouson/Desktop-shortcut/opencoarrays/prerequisites/downloads/mpich-3.1.4 && /bin/bash /home/rouson/Desktop-shortcut/opencoarrays/prerequisites/downloads/mpich-3.1.4/confdb/missing aclocal-1.15 -I confdb
/home/rouson/Desktop-shortcut/opencoarrays/prerequisites/downloads/mpich-3.1.4/confdb/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [/home/rouson/Desktop-shortcut/opencoarrays/prerequisites/downloads/mpich-3.1.4/aclocal.m4] Error 127
```

**Comment by rouson** [comment]
I have confirmed that the install script is able to build the default version of CMake (3.4.0) so the only remaining barrier to building OpenCoarrays on in the native Windows 10 Ubuntu Subsystem is the above problem with building MPICH.

**Comment by afanfa** [comment]
Every MPICH 3.x should work correctly (excluding bugs).

**Comment by rouson** [comment]
All,

In my attempts to build OpenCoarrays on the Ubuntu bash shell provided by the Windows 10 Subsystem for Linux, the OpenCoarrays installation script correctly builds GCC 6.1.0 and CMake 3.4.0, which leaves the building of MPICH as the only known stumbling block.  I just sent the email below to the MPICH mailing list.    Any suggestions are welcome.  

Damian


> Begin forwarded message:
> 
> From: Damian Rouson <damian@sourceryinstitute.org>
> Subject: [mpich-discuss] Errors building MPICH on Windows 10 Ubuntu subsystem
> Date: October 10, 2016 at 9:33:51 AM PDT
> To: discuss@mpich.org
> Reply-To: discuss@mpich.org
> 
> All,
> 
> In attempting to build MPICH 3.1.4 or 3.2 in the Windows 10 Subsystem for Linux, which provides a full Ubuntu bash shell, I receive the following error message after configuring:
> 
> mpich-3.2/confdb/missing: line 81: aclocal-1.15: command not found
> WARNING: 'aclocal-1.15' is missing on your system.
>          You should only need it if you modified 'acinclude.m4' or
>          'configure.ac <http://configure.ac/>' or m4 files included by 'configure.ac <http://configure.ac/>'.
>          The 'aclocal' program is part of the GNU Automake package:
>          <http://www.gnu.org/software/automake <http://www.gnu.org/software/automake>>
>          It also requires GNU Autoconf, GNU m4 and Perl in order to run:
>          <http://www.gnu.org/software/autoconf <http://www.gnu.org/software/autoconf>>
>          <http://www.gnu.org/software/m4/ <http://www.gnu.org/software/m4/>>
>          <http://www.perl.org/ <http://www.perl.org/>>
> make: *** [/home/rouson/Desktop-shortcut/opencoarrays/prerequisites/downloads/mpich-3.2/aclocal.m4] Error 127
> 
> Prior to configuring, I installed aclocal installed via “sudo apt-get install automake,” which provided aclocal-1.14. I attempted unsuccessfully to build aclocal-1.15, but the discussion at the following URL suggests that the problem might relate to time stamps on file MPICH tar ball:
> 
> http://stackoverflow.com/questions/18769770/user-of-autotools-generated-tarball-gets-error-message-aclocal-1-13-command-no <http://stackoverflow.com/questions/18769770/user-of-autotools-generated-tarball-gets-error-message-aclocal-1-13-command-no>
> 
> I tried several of the steps suggested at the above link, but each leads to the following error message during the make step:
> 
> $ make
> ( cd ./src/binding/fortran/mpif_h && ./buildiface )
> Replacing mpif.h.in <http://mpif.h.in/>
> ( cd ./src/binding/fortran/use_mpi && ./buildiface )
> Replacing mpi_base.f90.in <http://mpi_base.f90.in/>
> Replacing mpi_constants.f90.in <http://mpi_constants.f90.in/>
> Replacing mpi_t1.f90
> ( cd . && rm -f .err unusederr.txt ; rm -rf .tmp )
> ( cd . && \
>           ./maint/extracterrmsgs -careful=unusederr.txt \
>                                  -skip=src/util/multichannel/mpi.c \
>                                  `cat maint/errmsgdirs` > .tmp 2>.err )
> ( cd . && if test -s .err ; then rm -f .tmp ; cat .err ; exit 1 ; fi )
> Warning: attempt to redefine **fail.  Duplicate ignored.
> make: *** [src/mpi/errhan/defmsg.h] Error 1
> 
> Can anyone advise me about how to resolve this problem? Information on the Windows 10 Ubuntu distribution is here: 
> 
> http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/ <http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/>
> 
> My goa is to support users of OpenCoarrays (https://github.com/sourceryinstitute/opencoarrays <https://github.com/sourceryinstitute/opencoarrays>), which uses MPICH to build and execute coarray Fortran codes with the GNU Fortran compiler (gfortran).
> 
> Best Regards,
> ________________________________
> Damian Rouson, Ph.D., P.E.
> President, Sourcery Institute
> http://www.sourceryinstitute.org <http://www.sourceryinstitute.org/>
> +1-510-600-2992 (mobile)
> 
> _______________________________________________
> discuss mailing list     discuss@mpich.org
> To manage subscription options or unsubscribe:
> https://lists.mpich.org/mailman/listinfo/discuss

________________________________
Damian Rouson, Ph.D., P.E.
President, Sourcery Institute
http://www.sourceryinstitute.org
+1-510-600-2992 (mobile)

**Comment by rouson** [comment]
Hi Damian,
I can't directly help myself, but did just some web searching, leading to 
this:
http://stackoverflow.com/questions/33278928/how-to-overcome-aclocal-1-15-is-missing-on-your-system-warning-when-compilin
There, the last entry points to a script for installing the latest aclocal: 
https://github.com/gp187/nginx-builder/blob/master/fix/aclocal.sh
Not sure if this may help.
cheers
Michael


Am Montag, 10. Oktober 2016 21:08:13 UTC+2 schrieb Damian Rouson:
>
> All,
>
> In my attempts to build OpenCoarrays on the Ubuntu bash shell provided by 
> the Windows 10 Subsystem for Linux, the OpenCoarrays installation script 
> correctly builds GCC 6.1.0 and CMake 3.4.0, which leaves the building of 
> MPICH as the only known stumbling block.  I just sent the email below to 
> the MPICH mailing list.    Any suggestions are welcome.  
>
> Damian
>
>
> Begin forwarded message:
>
> *From: *Damian Rouson <dam...@sourceryinstitute.org <javascript:>>
> *Subject: **[mpich-discuss] Errors building MPICH on Windows 10 Ubuntu 
> subsystem*
> *Date: *October 10, 2016 at 9:33:51 AM PDT
> *To: *dis...@mpich.org <javascript:>
> *Reply-To: *dis...@mpich.org <javascript:>
>
> All,
>
> In attempting to build MPICH 3.1.4 or 3.2 in the Windows 10 Subsystem for 
> Linux, which provides a full Ubuntu bash shell, I receive the following 
> error message after configuring:
>
> mpich-3.2/confdb/missing: line 81: aclocal-1.15: command not found
> WARNING: 'aclocal-1.15' is missing on your system.
>          You should only need it if you modified 'acinclude.m4' or
>          'configure.ac' or m4 files included by 'configure.ac'.
>          The 'aclocal' program is part of the GNU Automake package:
>          <http://www.gnu.org/software/automake>
>          It also requires GNU Autoconf, GNU m4 and Perl in order to run:
>          <http://www.gnu.org/software/autoconf>
>          <http://www.gnu.org/software/m4/>
>          <http://www.perl.org/>
> make: *** 
> [/home/rouson/Desktop-shortcut/opencoarrays/prerequisites/downloads/mpich-3.2/aclocal.m4] 
> Error 127
>
> Prior to configuring, I installed aclocal installed via “sudo apt-get 
> install automake,” which provided aclocal-1.14. I attempted unsuccessfully 
> to build aclocal-1.15, but the discussion at the following URL suggests 
> that the problem might relate to time stamps on file MPICH tar ball:
>
>
> http://stackoverflow.com/questions/18769770/user-of-autotools-generated-tarball-gets-error-message-aclocal-1-13-command-no
>
> I tried several of the steps suggested at the above link, but each leads 
> to the following error message during the make step:
>
> $ make
> ( cd ./src/binding/fortran/mpif_h && ./buildiface )
> Replacing mpif.h.in
> ( cd ./src/binding/fortran/use_mpi && ./buildiface )
> Replacing mpi_base.f90.in
> Replacing mpi_constants.f90.in
> Replacing mpi_t1.f90
> ( cd . && rm -f .err unusederr.txt ; rm -rf .tmp )
> ( cd . && \
>           ./maint/extracterrmsgs -careful=unusederr.txt \
>                                  -skip=src/util/multichannel/mpi.c \
>                                  `cat maint/errmsgdirs` > .tmp 2>.err )
> ( cd . && if test -s .err ; then rm -f .tmp ; cat .err ; exit 1 ; fi )
> Warning: attempt to redefine **fail.  Duplicate ignored.
> make: *** [src/mpi/errhan/defmsg.h] Error 1
>
> Can anyone advise me about how to resolve this problem? Information on the 
> Windows 10 Ubuntu distribution is here: 
>
>
> http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
>
> My goa is to support users of OpenCoarrays (
> https://github.com/sourceryinstitute/opencoarrays), which uses MPICH to 
> build and execute coarray Fortran codes with the GNU Fortran compiler 
> (gfortran).
>
> Best Regards,
> ________________________________
> Damian Rouson, Ph.D., P.E.
> President, Sourcery Institute
> http://www.sourceryinstitute.org
> +1-510-600-2992 (mobile)
>
> _______________________________________________
> discuss mailing list     dis...@mpich.org <javascript:>
> To manage subscription options or unsubscribe:
> https://lists.mpich.org/mailman/listinfo/discuss
>
>
> ________________________________
> Damian Rouson, Ph.D., P.E.
> President, Sourcery Institute
> http://www.sourceryinstitute.org
> +1-510-600-2992 (mobile)
>
>  
>
>

**Comment by rouson** [comment]
@jeffhammond out of curiosity, do you have any advice on this issue.  I'm asking because I see that you're active on the MPICH mailing list and building MPI is the one step that blocked me from building OpenCoarrays in the Windows Subsystem for (Ubuntu) Linux.  I got the same 'aclocal-15' error in building MPICH and OpenMPI.   I tried emailing the MPICH list, but didn't receive any solutions.  I haven't tried the OpenMPI list.

**Comment by jeffhammond** [comment]
@rouson 

Neither MPICH nor Open-MPI support Windows any more.  It's a huge effort for them and they derive zero professional benefit from it.

The MPICH response to all Windows-related queries since version 1.4 is to link to [Why can't I build MPICH on Windows anymore?](https://wiki.mpich.org/mpich/index.php/Frequently_Asked_Questions#Q:_Why_can.27t_I_build_MPICH_on_Windows_anymore.3F).

Just to give an idea of the effort level required, when MPICH supported Windows, they had a full-time developer for it and it alone.  Eventually that guy decided to move on to more interesting things.

Microsoft MPI is freely available, although I don't know how usable it is.  Intel MPI likely requires a commercial license but I expect it is usable, because I have very good experiences with it on Linux platforms.  In particular, the Intel MPI team has been very responsive to RMA-related issues that I have reported to them.

Both Microsoft MPI and Intel MPI are based on MPICH.

As you probably know, Windows 10 has something resembling Linux.  There has been a bit of interest in trying to get MPICH working there, but I have not seen anything happen yet.  I was interested in trying to get MPICH working there so that I could write MPI code on a Surface notebook but it remains below ZBB line.

**Comment by zbeekman** [comment]
> As you probably know, Windows 10 has something resembling Linux.  There has been a bit of interest in trying to get MPICH working there, but I have not seen anything happen yet.  I was interested in trying to get MPICH working there so that I could write MPI code on a Surface notebook but it remains below ZBB line.

Yeah that's what we had been trying. 

@rouson: I wonder if Sameer has a windows machine with MSMPI or IntelMPI we could try?

FYI I'm planning to creat a Docker image with OpenCoarrays that could be a "work around" solution FTTB

**Comment by zbeekman** [comment]
If no one objects, I propose closing this issue as a "won't fix", at least for the time being, since we can't figure out how to get an upstream dependency (i.e. MPICH) installed on windows. If no one objects, or I don't hear back by Tuesday's call, I'll close this. ⌛️

**Comment by jeffhammond** [comment]
I waste quite a bit of time over the past two weeks trying to get WSL working on a Windows 10 VM but could never get it to connect to the network (i.e. `apt-get update -y` timed out on every server).  This is likely because I'm behind a firewall, but the Ubuntu host running the VM works just fine and I can SSH from the Windows 10 VM to the host IP.  Given what I observe on https://github.com/Microsoft/BashOnWindows/issues, it's not worth my time trying to debug.  The networking stack appears to be woefully inadequate.

**Comment by zbeekman** [comment]
@jeffhammond :bow: many many thanks for your input! Might save us all a whole bunch of time!

**Comment by zbeekman** [comment]
In fact, I'm going to close this... if anyone objects they can reopen.

**Comment by jeffhammond** [comment]
@zbeekman I'm still really curious about MPICH in WSL but sadly have no computer on which to test it and I refuse to buy something just to solve Microsoft's problems.

**Comment by milancurcic** [comment]
FYI, opencoarrays build and pass all tests on my WSL. This is true for both the master trunk (bb1b8ee) and the 1.8.2 release. I don't use `install.sh`, I install all dependencies via `apt-get` and do `cmake .. && make && ctest`.

I noticed Damian's issue here and a few folks on comp.lang.fortran reporting that they get `gcc-4.x` in WSL out of the box. I am wondering whether there are multiple branches of WSL because I had `gcc-5.4.0` out of the box since I enabled WSL for the first time. It may be important that I am on their Windows Insider Preview update cycle (current build is `14986.rs_prerelease.161202-1928`).

The versions of dependencies (all obtained via `apt-get install`) are:

* automake-1.15
* bison-3.0.4
* flex-2.6.0
* cmake-3.5.1
* make-4.1
* gcc-5.4.0
* mpich-3.2

**Comment by zbeekman** [comment]
FYI, you only really need CMake, MPICH and GCC.... those other packages are build dependencies of one or more of CMake, GCC, MPICH.

**Comment by rouson** [comment]
@milancurcic , this is wonderful news!  Thank you for informing us.  You win the first-known WSL Build Prize.  🏆  

If I recall correctly, I installed WSL by following [these instructions](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).  I built GCC 6.1.0 from source, but `sudo apt-get install mpich` installed only limited components of MPICH, e.g.,`mpiexec`but not `mpif90`, `mpifort`, or `mpicc`.  Did you use a command other than `sudo apt-get install mpich` to get the MPI compiler wrappers?  Also, are you booting into Windows or using virtualization.  For now, I have a macOS system set up for dual-boot with Windows as the other option.  In the long run, I'd like to have Windows in a virtual machine, but @jeffhammond reported difficulties with that approach and I can't invest too much time in it.  I'd just like to get something working.

I've never heard of Windows Insider Preview. I'll research how to install it.  If you have any links or other advice, please let us know.

**Comment by rouson** [comment]
@milancurcic I think I just signed up for Windows Insider Preview, but it's not clear how to update my Windows installation nor how to tell my current installation revision number.  `sudo apt-get install` still returns only gcc/g++/gfortran version 4.8.4.

**Comment by milancurcic** [comment]
@rouson:

1. I am using a regular (non-VM) install of Windows 10 Home edition 64-bit. I have no experience with Windows in VMs.
 
2. At the time when I was working to enable bash on Windows (October 2016), installation guides (I don't recall which one I used) said I needed at least build 14316. The only way I could bump my version above that number was that I enroll in Windows Insider Program. I remember there was a choice of few update tiers, I chose the fastest one. Currently, my system settings say I'm on the Insider Program level "Fast". Practically this means my Windows updates (whole OS) every few weeks ago. It is slower than before, and one of the updates broke my screen dimming function keys.

3. I think that once you enroll in the program, your OS needs to update to see any changes. After an update, your destop screen will have full version number in the bottom right corner. Unfortunately I am not very proficient with Windows and I wish I knew more but this is it.

4. I installed MPICH via `sudo apt-get install mpich` and I got working wrappers (`mpicc`, `mpif90`, `mpiexec`) available out of the box.

5. Check your Ubuntu version (`lsb_release -a`). This package/gcc availability may have to do something with the OS version. I remember that Win10 originally enabled Ubuntu 14.x, but [after some update a developer build included Ubuntu 16.x](http://www.omgubuntu.co.uk/2016/10/windows-10-linux-subsystem-ubuntu-16-04). My `lsb_release -a` says `16.04.1`.

**Comment by rouson** [comment]
@milancurcic This is very helpful.

> 1. I am using a regular (non-VM) install of Windows 10 Home edition 64-bit. 

Same for me. 

> At the time when I was working to enable bash on Windows (October 2016), installation guides (I don't > recall which one I used) said I needed at least build 14316. 

My OS Build is 14393.693

> The only way I could bump my version above that number was that I enroll in Windows Insider Program. I remember there was a choice of few update tiers, I chose the fastest one. Currently, my system settings say I'm on the Insider Program level "Fast". 

Apparently I was set on "Release Preview."  I just switched to "Fast."

> I think that once you enroll in the program, your OS needs to update to see any changes. After an 
> update, your destop screen will have full version number in the bottom right corner.  

Ok. I'll leave the machine powered on and connected to the Internet in hopes it will update itself.  I haven't discovered a way to update proactively.

> Unfortunately I am not very proficient with Windows and I wish I knew more but this is it.

Ditto

> Check your Ubuntu version (lsb_release -a). This package/gcc availability may have to do with the OS 
> version. I remember that Win10 originally enabled Ubuntu 14.x, but after some update a developer build > included Ubuntu 16.x. My lsb_release -a says 16.04.1.

This was extremely helpful information.  The above command shows that I'm on Ubuntu 14, which  I'm reasonably confident explains why you apt-get installs GCC 5.4.0 for you whereas it installs GCC 4.8.3 for me.  If I can figure out how to update to Ubuntu 16 and if `sudo apt-get install mpich` gives me the compiler wrappers, then it's highly likely I'll be able to build OpenCoarrays too.  At that point, I'll add a `windows-install.sh` script to OpenCoarrays.  Thanks tons!!

@zbeekman I'll reopen this in anticipation that this issue will be resolved reasonably soon via the steps above.

**Comment by milancurcic** [comment]
> My OS Build is 14393.693

I think this may be the key. The article I linked above says Ubuntu 16.04 was introduced in build 14936. 

> Ok. I'll leave the machine powered on and connected to the Internet in hopes it will update itself. I haven't discovered a way to update proactively.

Try rebooting. It may trigger an update.

**Comment by jeffhammond** [comment]
Control panel has a section with Updates in the title.  I trigger updates manually this way.

**Comment by milancurcic** [comment]
> Control panel has a section with Updates in the title. I trigger updates manually this way.

Very interesting, my control panel does not have any section related to Updates, only Windows Settings does (called Update & Security). I see no options to manually update.

**Comment by zbeekman** [comment]
@rouson, OK, so you'll close this, once you confirm it's working? I'm not sure I see the utility of reopening, because this seems like the only thing for us to do is confirm that it works or it doesn't: the rest is out of our hands.

**Comment by rouson** [comment]
@milancurcic @zbeekman @jeffhammond @afanfa 

I have now added a draft [windows-install.sh](https://github.com/sourceryinstitute/opencoarrays/blob/windows-build/windows-install.sh) script on a new windows-build branch.  The script completes the OpenCoarrays build process without error, but 33 of 34 tests fail.  The only test that passes is the one containing unit tests for our installation scripts, which is the only test that does not require MPI.

Even the simple MPI program below produces the same error as our CAF tests:
```
program main
  use mpi
  implicit none
  integer error
  call MPI_Init(ierror)
  call MPI_Finalize(ierror)
end program
```
The error message is the same as what is listed [here](http://lists.mpich.org/pipermail/discuss/2014-February/002271.html) except for the machine name.  Any advice?

**Comment by rouson** [comment]
All,

Never mind. The advice at [this page](http://stackoverflow.com/questions/31057694/gethostbyname-fail-after-switching-internet-connections) worked, except that I had to substitute my host name where the page shows `macbook-pro.local`.  I'll edit the script to suggest this to the user and then submit a pull request that finally closes this issue.   Hooray!!!   Thanks, everyone, for all the input and especially thank you, @milancurcic, for providing the critical advice that got us over the hump.  Sometime soon, I'll update our documentation and update  OpenCoarrays

**Comment by zbeekman** [comment]
testing on Travis-CI will require a docker image most likely; Travis-CI provides 12.04 and 14.04 out of the box so we'll have to roll our own docker image to emulate WSL 16.04
