### ISSUE TITLE
Installation fails if gfortran version < 4.9 is in PATH

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#229]
If gfortran exists in the users's PATH, then the OpenCoarrays installation scripts invoke gfortran [here](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/install-functions/find_or_install.sh#L167) or [here](https://github.com/sourceryinstitute/opencoarrays/blob/master/prerequisites/install-functions/find_or_install.sh#L264) to compile a simple program that prints the compiler version using the Fortran 2003 "compiler_version" function.  Older versions of gfortran do not support this function so compilation fails and the installation script dies.  Probably a few applications of "|| true" would make this more robust so that the installation simply treats an inability to compile the test program as an indication of an insufficiently recent version of gfortran.

**Comment by zbeekman** [comment]
Without looking at the code, that sounds like a viable solution.
