### ISSUE TITLE
bitdeli analytics

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#23]
Hi Damian,
I don't think I can enable bitdeli for you, I think you need to do from your own account. Otherwise, if I fork and then submit a PR it will be collecting data on my fork, and not on your branch, if I'm not mistaken. I think you need to go to https://bitdeli.com and log in with your github credentials there to give it some sort of github API permissions. There should then be a button to enable analytics for opencoarrays. When you do that, there will be another button to either automatically make a PR (from bitdeli) to add a badge to the README (this will get added to the very bottom at first) or a different button to manually ad it. Once the badge is on the README, then you can start collecting analytics via battled. If you want to do this but get stuck I can try to help figure it out.

**Comment by zbeekman** [comment]
it sounds like @szaghi was unimpressed with bitdeli and found it buggy/unreliable... At any rate, I can't add it unless I'm added to the sourceryinstitute group, AFAICT. Should be pretty easy to add without me how

**Comment by rouson** [comment]
I'll add you. 

D

**Comment by zbeekman** [comment]
@rouson thanks, that would be great

**Comment by rouson** [comment]
I see that you're already listed on the Members page:
https://github.com/sourceryinstitute/opencoarrays/network/members
Does that mean you have commit rights?  If not, I'll need some guidance regarding how to add you.  Alternatively, I'd be fine with giving you a temporary password for the sourceryinstitute account.  I simply say you should limit the number of commits you do from that account (as should I) to keep authorship more clear.

**Comment by zbeekman** [comment]
No the network members just show people who contribute (forks, PRs etc.) I'll look up the details to add a new member in the morning.

**Comment by zbeekman** [comment]
I think this is what you can do:

Go to https://github.com and ensure that you're viewing as sourceryinstitute by using the drop down menu on the upper left-hand side.

Next try clicking this link, as sourceryinstitute: https://github.com/orgs/sourceryinstitute/people?utf8=✓&query=zbeekman you should get taken to the sourceryinstitute people tab and have the option to click the "invite" button to invite me.

If that fails go back to https://github.com, make sure that you're still viewing as sourceryinstitute. There should be a button on the upper right-hand side that says something like "view organization", click that. Then click the people tab. Then search for zbeekman and press the invite button.

**Comment by zbeekman** [comment]
hmmm, it seems as though bitdeli is no longer functioning correctly, and may never again. I'm going to close this issue.
