### ISSUE TITLE
./install.sh -p gcc -b trunk has download issue with SI VM

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#238]
`svn: invalid option: --no-verbose` when trying to install prerequisites.

**Comment by rouson** [comment]
I'm aware of this issue and have mostly completed a fix.  Due to other commitments, it could be several days before I can test the fix and submit a pull request.

**Comment by zbeekman** [comment]
@rouson is this a duplicate of #234?

**Comment by zbeekman** [comment]
I'm closing this since I think it's a duplicate of #234, we can reopen if I'm mistaken.
