### ISSUE TITLE
Test for uncommented code

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#240]
This [stackoverflow page](http://stackoverflow.com/questions/2394017/remove-comments-from-c-c-code) shows a combination of gcc flags that can remove all comments from a C program:
```
gcc -fpreprocessed -dD -E -P test.c
```
@zbeekman assuming the same flags work for gfortran, I'd like to add a simple test to the repository that performs a diff on submitted source versus the output of the above command.  If the diff returns a file of zero length, then there are no comments and the test should fail.  Such a test could presumably be summarized in a very brief bash script.  This would at least be a step in the direction of requiring documentation in all pull requests.  Obviously, this is the most minimal of tests so we could refine it going forward.  For example, we could compare divide some measure of the size of the diff output by some measure of the size of the original code (e.g., SLOC) and reject code that doesn't at least have enough comments to pass some threshold, e.g., at least 1 out of every 25 lines should be a comment for acceptable code.

**Comment by zbeekman** [comment]
@rouson I guess for now this should be implemented to only look at files touched in the commit range being tested, right? Otherwise the codebase may start failing, as it is.

**Comment by rouson** [comment]
As much as I love the idea of this (not that I'm biased), it seems clearly to be one of those seemingly nice ideas that will never float to the top of the daily priority list.  Also, I believe that our contributors have adopted practices that make this specific fix unlikely to be especially useful. (It is now common practice to includes at least one comment with submitted new code.) I'm going to mark this as "won't fix" and close it.
