### ISSUE TITLE
Add option to disable building/running tests with assembly code dependencies

### ISSUE THREAD

**Issue by opoplawski** [sourceryinstitute/opencoarrays#244]
Attempting to create a Fedora package for OpenCoarrays but I'm getting:
```
/usr/bin/gfortran   -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules/mpich -DNDEBUG CMakeFiles/hello_multiverse.dir/hello_multiverse.F90.o  -o hello_multiverse  ../../../mpi/libcaf_mpi.a 
../../../mpi/libcaf_mpi.a(mpi_caf.c.o): In function `error_stop':
/builddir/build/BUILD/OpenCoarrays-1.7.4/src/mpi/mpi_caf.c:3776: undefined reference to `MPI_Abort'
```

Full build log:
[build.txt](https://github.com/sourceryinstitute/opencoarrays/files/577213/build.txt)

It seems that the binary isn't being linked to the mpi library.

**Comment by zbeekman** [comment]
How are you building it? Invoking CMake directly? If so you need to set CC=mpicc and FC=mpif90. Also which MPI are you building against?

**Comment by opoplawski** [comment]
Ah, I see the error now - I wasn't actually passing in CC=mpicc and FC=mpif90 although I thought I was.

Now I get:
```
/usr/lib64/mpich/bin/mpif90   -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fs
tack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules/mpich
 -DNDEBUG CMakeFiles/coarray_navier_stokes.dir/coarray-shear_coll.F90.o  -o coarray_navier_stokes  ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_
sse.a ../../../../mpi/libcaf_mpi.a
make[2]: Leaving directory '/builddir/build/BUILD/OpenCoarrays-1.7.4/build-mpich'
/usr/bin/ld: ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a(trig.o): relocation R_X86_64_32 against `.rodata' can not be used when making a
shared object; recompile with -fPIC
/usr/bin/ld: ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a(plan.o): relocation R_X86_64_32 against `.rodata.str1.4' can not be used when ma
king a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

**Comment by opoplawski** [comment]
Ah, I see libfft_sse.a/_avx.a are pre-built.  That won't work for us.

**Comment by zbeekman** [comment]
Those files are both only used for the Navier Stokes test, and not actually needed for the correct functioning of OpenCoarrays. (It's actually an FFT library written in assembly...) 

Is there some system introspection that we can do to determine that this won't work for your system or should I just add a CMake flag to exclude them from the build? (They already get excluded on non Linux and non x86_64 systems)

**Comment by opoplawski** [comment]
If we can just exclude them from the build (perhaps if the files aren't present?  I could deleted them), that would be fine.  Thanks.

**Comment by zbeekman** [comment]
Probably easier to just add a CMake cache Boolean variable to turn thus off.

**Comment by zbeekman** [comment]
Just add `-DSKIP_ASSEMBLY_DEPS` to the CMake invocation. I need to test this on linux to confirm there aren't any typos, since this is disabled on TRAVIS-CI and on OS X.  If you want to do this sooner, you could just set the enironment variable TRAVIS to have the same intended effect. (i.e., `export TRAVIS=1; cmake .. ...`
