### ISSUE TITLE
Install script bails if TERM is unset

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#249]
This is a very uncommon scenario, and it may end up being a "won't fix" but due to `set -o nounset` the one of the install scripts bails due to TERM being unset. This happens after 

```
2016-11-10 18:45:33 UTC [     info] Checking whether I can create /home/travis/opt/opencoarrays ... 
2016-11-10 18:45:33 UTC [     info] yes.
```

On the Travis-CI Linux container infrastructure. I manually added a TERM environment variable to the build to circumvent this deficiency.

**Comment by rouson** [comment]
It sounds like "won't fix" is appropriate.

**Comment by zbeekman** [comment]
I'm going to file a bug report with Travis-CI. See https://twitter.com/travisci/status/796800110491500552

I have a decent work around for now....

**Comment by zbeekman** [comment]
Travis-CI have fixed this problem.
