### ISSUE TITLE
Use --oversubscribe not --oversubscribe with openmpi

### ISSUE THREAD

**Issue by amckinstry** [sourceryinstitute/opencoarrays#265]
Tests fail on building open-coarrays 1.7.4 on Debian unstable with openmpi 2.0.1 +.
When testing in a VM, CMakeLists.txt adds "--oversubscribed" where numcores is not enough.
The correct syntax on openmpi is "--oversubscribe"

**Comment by zbeekman** [comment]
Thanks for pointing this out! I'll fix it asap

**Comment by zbeekman** [comment]
This is fixed on master now... There are some more bug fixes and enhancements, but we're aiming to get a release out ASAP.
