### ISSUE TITLE
failing tests

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#27]
There is probably an issue with my MPICH and OpenMPI installations, but I'm going to ask this question anyway:

Is there any reason why when building and testing OpenCoarrays tests 6, "allocate_as_barier_proc" and 18, "co_reduce" are failing yet all the other tests pass? I think/hope I've gotten a working [OCA Homebrew Formula](https://github.com/Homebrew/homebrew/pull/46547), but I'm also have been having trouble building OCA from source and via the Homebrew formula on my local mac. I can't tell if this is a problem with my toolchain or a larger issue. The CI tests haven't finished yet for the OCA formula, so we'll see what happens there; my first attempt [failed because cmake couldn't find a working mpif90 compiler](https://travis-ci.org/Homebrew/homebrew/jobs/94237438#L660), which was odd.

**Comment by sourceryinstitute** [comment]
> On Dec 1, 2015, at 2:00 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> There is probably an issue with my MPICH and OpenMPI installations, but I'm going to ask this question anyway:
> 
> Is there any reason why when building and testing OpenCoarrays tests 6, "allocate_as_barier_proc" and 18, "co_reduce" are failing yet all the other tests pass? 
> 
> 

See bullet 4 at https://github.com/sourceryinstitute/opencoarrays/blob/master/STATUS.md#compiler-issues-gnu.  If your compiler version is lower than the (pre-release) 5.3.0 or the (pre-release) 6.0.0, then co_reduce will fail.  Hopefully 5.3.0 will release relative soon and 6.0.0 will release next Spring. 

D

**Comment by zbeekman** [comment]
What about the test "allocate_as_barrier_proc"?

**Comment by rouson** [comment]
> On Dec 1, 2015, at 2:11 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> What about the test "allocate_as_barrier_proc"?
> 
> 
Good question.  If you haven’t already, please create an issue report and hopefully Alessandro can investigate this.

D

**Comment by zbeekman** [comment]
OK, making good progress on the Homebrew formula, I have it more or less building except for failing these tests. I'll close this issue for now, since it has been superseded by #28, for which we're just waiting for @afanfa's input. This seems to be the only thing breaking the build now that I have made some restrictions on compilers (telling homebrew it can't use clang or llvm).
