### ISSUE TITLE
check_remote_alloced_comp_1.f90 hangs in VM

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#279]
@vehre 

Test #9 [check_remote_alloced_comp_1.f90](https://github.com/sourceryinstitute/opencoarrays/blob/master/src/tests/unit/init_register/check_remote_alloced_comp_1.f90) hangs in the current version of the virtual machine, which has a gfortran build from 2 days ago.  This appears to be a new test that you created 3 days ago.  

I just uploaded the latest version of the virtual machine today.  It has GCC compilers dated 20161215.

**Comment by vehre** [comment]
@zbeekman, @afanfa this test should only be active, when #260 is done.

**Comment by rouson** [comment]
@vehre In that case, 

1. The feature should not be enabled on the OpenCoarrays master branch, or
2. There should be a compiler error message tha blocks use of the broken features,  or 
3. OpenCoarrays should give a generate a runtime error message whenever a code tries to access the broken feature.  

listed in order from most preferred to least preferred solution.  Up until this allocatable components work, we've held to a very high standard of not knowingly letting broken features hit the master branch.  This causes a great deal of confusion and wasted time.  Just yesterday, I uploaded a new copy of the virtual machine with a GCC trunk build from 20161215 and notified my class of it because it includes several fixes to bugs my students and I discovered during the course.   Once one of the above happens, I'll have to rebuild GCC and/or OpenCoarrays, then export and post a new virtual machine, and notify everyone.  

I tested OpenCoarrays before posting the virtual machine, but I think my local repository most have been a day or two behind master so I didn't catch this test failure until after releasing.

**Comment by zbeekman** [comment]
@rouson this is entirely my fault. @vehre told me about this, and I neglected to disable it. I'll make the fix right now.

**Comment by zbeekman** [comment]
to elaborate, I was short sighted in that I thought that no one would be using GCC trunk "in production" and that the `if GCC >= 7` guards around the test would be sufficient.

**Comment by zbeekman** [comment]
In ~20 minutes CI tests should be done for PR #280 and we can merge the change to fix this.

@rouson 
> listed in order from most preferred to least preferred solution.

Did you mean "listed in order from least preferred to most preferred solution"?

**Comment by zbeekman** [comment]
> OpenCoarrays should generate a runtime error message whenever a code tries to access the broken feature.

Some sort of quick stub routine in the OpenCoarrays library that would error stop rather than just hang would be nice.

**Comment by zbeekman** [comment]
> Did you mean "listed in order from least preferred to most preferred solution"?

OK I'll be quiet now, I misunderstood your point 1 above...

>The _**feature**_ should not be enabled on the OpenCoarrays master branch, or

**Comment by rouson** [comment]
@zbeekman  Thanks for looking into this. Any of the three solutions listed above are preferable to simply disabling the test.  Probably I should have committed any ordering of the options.   If @vehre handles it, then a compiler error message would be great.  If @afanfa handles it, then a runtime error message from the library would be fine.  If you handle it and there are specific commits that enabled whatever feature is broken, then those commits could be reverted.  In the interim, until of these three options happens, I'll modify the test so that it stays active and fails.  Even a test failure is better than having a broken feature on the master branch for which there is neither an associated compile-time error message, runtime error message, and even a test failure is better than a test that hangs.

**Comment by zbeekman** [comment]
@rouson OK, so if I'm understanding you correctly, we should leave the test on indicating the feature that doesn't work? In that case, DO NOT merge #280

**Comment by vehre** [comment]
The compiler can not know, that the test will fail. And for the runtime it is hard to analyze that not all images will join the alloc. So imho it's best to disable the test. 

The test is, when the remember correctly, doing conditional allocation of a component depending on the number of the image. How the front end of the compiler is to analyze this, given the data I have there, is lost to me. So basically it comes down to the runtime, but that would need to know that not all images will participate in the same alloc, which for the runtime is undecidable, too. This leaves deactivation until @afanfa has implemented asynchronous allocation.

**Comment by rouson** [comment]
@vehre, deactivation is not the only remaining option. A test that reports failure is preferable to a hanging test and a hanging test is preferable to a deactivated test.  I suppose the fact that this issue relates to performance rather than correctness might be the only thing that might make it ok to deactivate the test, but it's a sufficiently severe performance concern that I wouldn't want anyone to use the feature without warning and go away with the wrong impression. I've watched this happen with the Intel compiler for years.  Roughly five years ago, Intel released coarray support that was technically correct but offered poor performance for all communication of non-scalar data or communication of any data in distributed memory.  They only began to address the issue in releases approximately a year ago.   In the interim, I've sadly watched comments in public forums and heard comments in private that indicated to me that people who were first introduced to CAF by the Intel compiler came away with the impression that CAF performs poorly when the real problem was just that Intel's implementation of CAF performed poorly.   Even for contiguous arrays, Intel was doing element-by-element puts and gets and it's not like Intel didn't know this was a problem.  I first heard about the poor design choice from an Intel engineer in August 2012 so I think they knew they were releasing a low-performing CAF implementation from the beginning.  That really hurt CAF in the eyes of a lot of people.

Alessandro did a great job of ensuring that gfortran/OpenCoarrays offered great performance from the very beginning of the project.  If we're adding a feature on our master branch that we know hurts performance in a significant way, we need to warn users.  We can warn them with very clear documentation (which is probably more work than it's worth if this will be fixed soon) or we can warn them with a failing test that is named in an obvious way to communicate the issue, which is why I'll probably rename the test too when I edit it. 

Or the best solution of all would have been to keep this capability off of the master branch so that it doesn't end up in the hands of most people other than the developers working on it.

**Comment by rouson** [comment]
@zbeekman Yes, that's correct.  The test should stay in and I'll edit it so that ctest reports a failure rather than hanging.  

@vehre I should probably also make it clear that the user impressions that concern me include several specific users.  I can point to at least five users or potential users who have named this feature as necessary for them to evaluate CAF with gfortran/OpenCoarrays.  Some of these users have deep experience in  parallel programming.  I wouldn't want them to stumble into a significant performance problem without warning.  Some of the users have even funded work on gfortran or OpenCoarrays or have funded my work.  A couple of them are on the Fortran committee.  I only began to appreciate the importance of derived type coarrays with allocatable components a few months ago .  If/when these specific users decide to evaluate CAF with gfortran/OpenCoarrays, we only have one chance to make a first impression.  And as you know, I think the people who will speak up and tell us about a problem are outnumbered 10-to-1 by the ones who will silently walk away.

**Comment by vehre** [comment]
Well, then go with the last. We are currently spending a lot time on a testcase that was not meant to be in the commit. It should have been on the #260 to give Alessandro a testcase. So can we just move it there, stop the fruitless discussion and get to something productive?

When we always take so much time on discussing testcases that don't yet work, then I will have to spent significantly more time on deciding whether I submit a testcase to prevent this waste of time.

**Comment by zbeekman** [comment]
> @zbeekman Yes, that's correct. The test should stay in and I'll edit it so that ctest reports a failure rather than hanging.

@rouson OK I can do it too... I think there's a time-out property on tests that could be significantly lowered, and then also a will-fail property... but that indicates success on failure. I.E., a `.not.` operator on the test output. Not entirely sure how to get extra warnings into CTest output at the moment or code up special CTest behavior.

**Comment by rouson** [comment]
@vehre Other people's time matters too.  I wasted time exporting and uploading the virtual machine and notifying my students that it was ready for use only to find out that a recent commit causes a test to hang, preventing the execution of any tests thereafter.  If the ability to compile code that doesn't work as intended (and I do include significant performance problems as not working as intended) never makes it onto the master branch, discussions such as this one never have to happen.  By that, I mean if allocatable components support had not made it onto the master branch until it was in a releasable, this could never have happened. The same statement applies to the original allocatable components "support" that was committed to the gcc trunk, breaking the link to OpenCoarrays, and putting us in the difficult situation of not having access to several unrelated features for some time.

**Comment by vehre** [comment]
Damian your project is the more agile one. Comparing gfortran to opencoarrays is like comparing a freight train to a Ferrari. There was enough time while the work on gfortran was done to get opencoarrays to a reasonable state, IMO.

One could still switch off allocatable components on opencoarrays by simply avoiding to register them, but that would probably have side effects as well. Gfortran on the other hand needs a time consuming process of pre-review, final review commit tests and so on. And please always take into account: there is *no* official gcc-7 release yet. Gcc-7 is and will change in the next two weeks significantly. So any complaints about code compiled with gcc-7 is not working as expected are void. There is *no* release. Gcc is slow and we are in active development. So when you advertise it always keep in mind you are encouraging people to use pre-alpha software. So in the light of not wanting to waste folks you should wait with advertising the use of allocatable components in derived typed coarrays until both gcc-7 is stable and opencoarrays has made the necessary implementation.

**Comment by rouson** [comment]
@vehre That is very good advice.  I will follow it.  In this specific case (which I won't repeat), I really wanted my students to learn the latest and greatest features at the bleeding edge of the language.  I should have recognized that bleeding edges are named that way for a reason.  This class is only offered every other year so my next opportunity to teach students this material is two years away and there were so many goodies that were almost ready now.  I should have waited.

**Comment by vehre** [comment]
I don't think you should have waited. It would have been sufficient to tell them that they are working with alpha grade software and are to expect failure and unexpected behavior.

**Comment by rouson** [comment]
With Zaak's help, I just pushed a commit that instructs cmake to time-out on this test so the rest of the tests can progress.  We'll keep the best active with GCC 7 builds but deactivate it with GCC < 7.
