### ISSUE TITLE
Optimize caf_sendget_by_ref

### ISSUE THREAD

**Issue by vehre** [sourceryinstitute/OpenCoarrays#289]
Use MPI-Datatypes to and sophisticated communication functions to efficiently transfer data between two remote images.

**Comment by rouson** [comment]
Shall we mark this as wont-fix and close it?

**Comment by zbeekman** [comment]
This is still an issue, IMO, but I think there are bigger issues with sendget_by_ref captured elsewhere. Therefore, I'll leave as closed unless someone thinks I should re-open.

**Comment by zbeekman** [comment]
This is still an issue, IMO, but I think there are bigger issues with sendget_by_ref captured elsewhere. Therefore, I'll leave as closed unless someone thinks I should re-open.
