### ISSUE TITLE
libfft_sse.a fails to link on `mpich-docker-image`

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#297]
Attn: @rouson 

When trying to build the naiver-stokes integration test, the linker fails with the following output:

```
/usr/bin/gfortran   -Wl,-rpath  -Wl,/opt/mpich/3.1.4/gnu/6.2.1/lib  -Wl,--enable-new-dtags  -g CMakeFiles/coarray_navier_stokes.dir/coarray-shear_coll.F90.o  -o coarray_navier_stokes -Wl,-rpath,/opt/mpich/3.1.4/gnu/6.2.1/lib  ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a ../../../../mpi/libcaf_mpi.a /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpi.so /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpifort.so /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpi.so /opt/mpich/3.1.4/gnu/6.2.1/lib/libmpifort.so
/usr/bin/ld: ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a(trig.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../../../../../../src/tests/integration/pde_solvers/navier-stokes/libfft_sse.a(plan.o): relocation R_X86_64_32 against `.rodata.str1.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

I'm a bit perplexed as to why this happens... the linker is saying that `-fPIC` should be added, but, I thought that the FFT libraries were hand written in assembly... Perhaps this is just a "won't fix" and we should move on...

**Comment by vehre** [comment]
When looking into the archive, one sees that GCC 4.8.2 is referenced. That may indicate those libraries have at least been assembled by gcc. Would it be feasible to use system supplied fft-libraries? Getting updates...

**Comment by zbeekman** [comment]
According to email with @rouson, just remove the test NS test due to the headaches it causes here and elsewhere... I may keep the target but just exclude it from "all" and don't add a CTest test for it.
