### ISSUE TITLE
muliti dimension array, co_sum bug?

### ISSUE THREAD

**Issue by WeiLiPenguin** [sourceryinstitute/opencoarrays#3]
Hi, 
Is co_sum(A) should sum each element of A from images to itself ?
I use a array shape like a(1,1,2,2,1) seems co_sum only sum to a(1,1,2
maybe it is gfortran or mpich bug
if I set a=1, code can run 
but if I set like:
a(1,1,1,1,1)=1
a(1,1,2,1,1)=1
a(1,1,1,2,1)=1
a(1,1,2,2,1)=1
code crash Segmentation fault - invalid memory reference.

test.f90

```fortran
      ! CAF CO_SUM(A[, RESULT_IMAGE, STAT, ERRMSG])
      integer a(1,1,2,2,1)![*]
      integer b(1,1,2,2,1)![*]
      integer me

      me=this_image()
      !a(1,1,1,1,1)=1
      !a(1,1,2,1,1)=1
      !a(1,1,1,2,1)=1
      !a(1,1,2,2,1)=1
      a=1
      critical
      print*,"I am",me,"before co_sum a=",a
      end critical
      call co_sum(a)
      critical
      print*,"I am",me," after co_sum a=",a
      end critical
      return
      end
```
so, gfortran, mpich or coarray's bug ?

Thanks!

**Comment by afanfa** [comment]
Hi,

I do not follow your description. Could you please provide your code?

On Tue, Jun 2, 2015 at 1:10 PM, WeiLi <notifications@github.com> wrote:

> Hi,
> Is co_sum(A) should sum each element of A from images to itself ?
> I use a array shape like a(1,1,2,2,1) seems co_sum only work to a(1,1,2
> maybe it is gfortran or mpich bug
> if I set a=1, code can run
> but if I set like:
> a(1,1,1,1,1)=1
> a(1,1,1,1,1)=1
> a(1,1,1,1,1)=1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/3>.
>



-- 

Alessandro Fanfarillo

**Comment by WeiLiPenguin** [comment]
```fortran
      ! CAF CO_SUM(A[, RESULT_IMAGE, STAT, ERRMSG])
      integer a(1,1,2,2,1)
      integer me

      me=this_image()
      !a(1,1,1,1,1)=1
      !a(1,1,2,1,1)=1
      !a(1,1,1,2,1)=1
      !a(1,1,2,2,1)=1
      a=1
      print*,"I am",me,"before co_sum a=",a
      call co_sum(a)
      print*,"I am",me," after co_sum a=",a
      return
      end
```

**Comment by WeiLiPenguin** [comment]
Hi, @afanfa
I update the report
could you reproduce my result?

**Comment by afanfa** [comment]
Yes, I do. I got:

 I am           1 before co_sum a=           1           1
1           1
 I am           4 before co_sum a=           1           1
1           1
 I am           2 before co_sum a=           1           1
1           1
 I am           3 before co_sum a=           1           1
1           1
 I am           1  after co_sum a=           4           4
1           1
 I am           2  after co_sum a=           4           4
1           1
 I am           3  after co_sum a=           4           4
1           1
 I am           4  after co_sum a=           4           4
1           1

it should be 4 4 4 4 on each process.

On Tue, Jun 2, 2015 at 1:46 PM, WeiLi <notifications@github.com> wrote:

> Hi, @afanfa <https://github.com/afanfa>
> I update the report
> could you reproduce my result?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/3#issuecomment-107926075>
> .
>



-- 

Alessandro Fanfarillo

**Comment by WeiLiPenguin** [comment]
update the bug trigger example, this time seems `co_broadcast` also have same problem. Is this bug related to the gfc_descriptor_t ?
```fortran
      integer, allocatable :: a(:,:,:)
      integer me
      allocate(a(2,1,2))

      me=this_image()
      !a(1,1,1,1)=1
      !a(1,2,1,1)=1
      !a(1,1,2,1)=1
      !a(1,2,2,1)=1
      a=me
      print*,"I am",me,"before co_broadcast a=",a
      call co_broadcast(a,1)
      print*,"I am",me," after co_broadcast a=",a
      sync all()

      a=me
      print*,"I am",me,"before co_sum a=",a
      call co_sum(a)
      print*,"I am",me," after co_sum a=",a
      return
      end
``` 
results:
```bash
 I am           1 before co_broadcast a=           1           1           1           1
 I am           2 before co_broadcast a=           2           2           2           2
 I am           1  after co_broadcast a=           1           1           1           1
 I am           2  after co_broadcast a=           1           2           2           1
 I am           1 before co_sum a=           1           1           1           1
 I am           2 before co_sum a=           2           2           2           2
 I am           2  after co_sum a=           3           2           2           3
 I am           1  after co_sum a=           3           1           1           3
```

**Comment by afanfa** [comment]
All the collectives are based on a single function called co_reduce_1. Such
function analyzes the gfc_descriptor_t in order to decide how to implement
the collective. The problem could be: 1) in the library, if we read in the
wrong way the descriptor; 2) in the compiler, if the descriptor has been
filled with wrong data; 3) both.

On Wed, Jun 3, 2015 at 7:12 PM, WeiLi <notifications@github.com> wrote:

> update the bug trigger example, this time seems co_broadcast also have
> same problem. Is this bug related to the gfc_descriptor_t ?
>
>       integer, allocatable :: a(:,:,:)
>       integer me
>       allocate(a(2,1,2))
>
>       me=this_image()
>       !a(1,1,1,1)=1
>       !a(1,2,1,1)=1
>       !a(1,1,2,1)=1
>       !a(1,2,2,1)=1
>       a=me
>       print*,"I am",me,"before co_broadcast a=",a
>       call co_broadcast(a,1)
>       print*,"I am",me," after co_broadcast a=",a
>       sync all()
>
>       a=me
>       print*,"I am",me,"before co_sum a=",a
>       call co_sum(a)
>       print*,"I am",me," after co_sum a=",a
>       return
>       end
>
> results:
>
>  I am           1 before co_broadcast a=           1           1           1           1
>  I am           2 before co_broadcast a=           2           2           2           2
>  I am           1  after co_broadcast a=           1           1           1           1
>  I am           2  after co_broadcast a=           1           2           2           1
>  I am           1 before co_sum a=           1           1           1           1
>  I am           2 before co_sum a=           2           2           2           2
>  I am           2  after co_sum a=           3           2           2           3
>  I am           1  after co_sum a=           3           1           1           3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/3#issuecomment-108527580>
> .
>



-- 

Alessandro Fanfarillo

**Comment by WeiLiPenguin** [comment]
Hi, 
How to print out the the size of the each rank of the source in co_reduce_1? 
I print the rank, it is 3, seems right for my allocate(a(2,1,2)), but  I don't know about c and  what '->' means.
is `source->dim[j]._ubound` the start address ? what is `ptrdiff_t`?  I have no idea about the pointer.  

could you help me? Thanks 

```c
 co_reduce_1 (MPI_Op op, gfc_descriptor_t *source, int result_image, int *stat,              
              char *errmsg, int src_len __attribute__ ((unused)), int errmsg_len)            
 {                                                                                           
   size_t i, size;                                                                           
   int j, ierr;                                                                              
   int rank = GFC_DESCRIPTOR_RANK (source);                                                  
                                                                                             
   fprintf (stderr, "souce have rank %d: from %d \n", rank, caf_this_image);                 
   MPI_Datatype datatype = get_MPI_datatype (source);                                        
                                                                                             
   size = 1;                                                                                 
   for (j = 0; j < rank; j++)                                                                
     {                                                                                       
       ptrdiff_t dimextent = source->dim[j]._ubound                                          
                             - source->dim[j].lower_bound + 1;                               
       if (dimextent < 0)                                                                    
         dimextent = 0;                                                                      
       size *= dimextent;                                                                    
     }                                                                                       
                                                                                             

```

**Comment by WeiLiPenguin** [comment]
update issue trigger example:
```fortran
      integer, allocatable :: a(:,:,:)
      integer me, address
      allocate(a(2,1,2))

      me=this_image()
      !a(1,1,1,1)=1
      !a(1,2,1,1)=1
      !a(1,1,2,1)=1
      !a(1,2,2,1)=1
      a=me
      address = loc(a(1,1,1))
      print*,"I am",me,"address of a(1,1,1): ",address
      address = loc(a(2,1,1))
      print*,"I am",me,"address of a(2,1,1): ",address
      address = loc(a(1,1,2))
      print*,"I am",me,"address of a(1,1,2): ",address
      address = loc(a(2,1,2))
      print*,"I am",me,"address of a(2,1,2): ",address
      sync all()
      call co_broadcast(a,1)
      print*,"I am",me," after co_broadcast a=",a
      sync all()

      a=me
      print*,"I am",me,"before co_sum a=",a
      call co_sum(a)
      print*,"I am",me," after co_sum a=",a
      return
      end
```
to prove if the `a` is continuously allocated, and also   
add some printout in `mpi_caf.c`:
```c
static void
co_reduce_1 (MPI_Op op, gfc_descriptor_t *source, int result_image, int *stat,
             char *errmsg, int src_len __attribute__ ((unused)), int errmsg_len)
{                                                                                                                                                                      
  size_t i, size;
  int j, ierr;
  int rank = GFC_DESCRIPTOR_RANK (source);

  fprintf (stderr, "souce have rank %d: from %d \n", rank, caf_this_image);
  MPI_Datatype datatype = get_MPI_datatype (source);

  size = 1;
  for (j = 0; j < rank; j++)
    {
      ptrdiff_t dimextent = source->dim[j]._ubound
                            - source->dim[j].lower_bound + 1;
      if (dimextent < 0)
        dimextent = 0;
      size *= dimextent;
      fprintf (stderr, "souce extent %td  dim %d: upb= %td  lowb=%td from %d \n", dimextent, j,  source->dim[j]._ubound,  source->dim[j].lower_bound, caf_this_image);
    }

  bool contiguous = PREFIX (is_contiguous) (source) ;


  fprintf (stderr, "souce have size %td: from %d \n", size, caf_this_image);

  fprintf (stderr, "souce is contiguous: %d  from %d \n", contiguous, caf_this_image);

  if (rank == 0 || PREFIX (is_contiguous) (source))
     {
       if (result_image == 0)
         ierr = MPI_Allreduce (MPI_IN_PLACE, source->base_addr, size, datatype,
                               op, CAF_COMM_WORLD);
       else if (result_image == caf_this_image)
         ierr = MPI_Reduce (MPI_IN_PLACE, source->base_addr, size, datatype, op,
                            result_image-1, CAF_COMM_WORLD);
       else
         ierr = MPI_Reduce (source->base_addr, NULL, size, datatype, op,
                            result_image-1, CAF_COMM_WORLD);
       if (ierr)
         goto error;
       return;
     }
 
   fprintf (stderr, "souce is not ( contiguous || rank == 0): from %d \n", caf_this_image);
 
   for (i = 0; i < size; i++)                                                                              
....
```

also check the `common/caf_auxiliary.c` and add printout:

```c
bool                                                                                       
PREFIX (is_contiguous) (gfc_descriptor_t *array)                                           
{                                                                                          
    int i;                                                                                 
    ptrdiff_t dim_extent;                                                                  
    ptrdiff_t extent = 1;                                                                  
    bool element = false;                                                                  
                                                                                           
    for (i = 0; i < GFC_DESCRIPTOR_RANK(array); i++)                                       
    {                                                                                      
        if (!element && array->dim[i]._stride != extent)                                   
        {                                                                                  
                                                                                           
            fprintf (stderr, "souce is not contiguous for dim %d: stride !=1 \n", i);      
            return false;                                                                  
        }                                                                                  
        dim_extent = array->dim[i]._ubound - array->dim[i].lower_bound + 1;                
        if (dim_extent <= 0)                                                               
            return true;  /* Zero-sized array.  */                                         
        else if (dim_extent == 1)                                                          
            element = true;                                                                
        else if (element)                                                                  
        {                                                                                  
            fprintf (stderr, "souce is not contiguous for dim %d: element is true \n", i); 
            return false;                                                                  
        }                                                                                  
            extent *= dim_extent;                                                          
    }                                                                                      
    return true;                                                                           
}                                                                                          
```

the output like:
```bash
 I am           1 address of a(1,1,1):     20218704
 I am           1 address of a(2,1,1):     20218708
 I am           1 address of a(1,1,2):     20218712
 I am           1 address of a(2,1,2):     20218716
 I am           2 address of a(1,1,1):     11739888
 I am           2 address of a(2,1,1):     11739892
 I am           2 address of a(1,1,2):     11739896
 I am           2 address of a(2,1,2):     11739900
 I am           1  after co_broadcast a=           1           1           1           1
 I am           1 before co_sum a=           1           1           1           1
 I am           2  after co_broadcast a=           1           2           2           1
 I am           2 before co_sum a=           2           2           2           2
souce have rank 3: from 1 
souce extent 2  dim 0: upb= 2  lowb=1 from 1 
souce extent 1  dim 1: upb= 1  lowb=1 from 1 
souce have rank 3: from 2 
souce extent 2  dim 0: upb= 2  lowb=1 from 2 
souce extent 1  dim 1: upb= 1  lowb=1 from 2 
souce extent 2  dim 2: upb= 2  lowb=1 from 2 
souce is not contiguous for dim 2: element is true 
souce extent 2  dim 2: upb= 2  lowb=1 from 1 
souce is not contiguous for dim 2: element is true 
souce have size 4: from 2 
souce is contiguous: 0  from 2 
souce is not contiguous for dim 2: element is true 
souce is not ( contiguous || rank == 0): from 2 
souce have size 4: from 1 
souce is contiguous: 0  from 1 
souce is not contiguous for dim 2: element is true 
souce is not ( contiguous || rank == 0): from 1 
 I am           1  after co_sum a=           3           1           1           3
 I am           2  after co_sum a=           3           2           2           3
```
It is shown the integer array `a` is allocated continuously in memory,  seems the `gfc_descriptor_t` of source is right, but the `_gfortran_is_contiguous` not return True for `a`.   `_gfortran_is_contiguous` is used to make sure the source is allocated continuously in memory ? 

comment found in `common/caf_auxiliary.c` 
```c
 /* Check whether the array section is contiguous.  There are two possibilities 
    either the stride matches always the extent of that dimension - or if the   
    "noncontiguous" dimensions have all extent one (= element access for that   
    dimension); a mixture is possible if the left dimensions are contiguous     
    and the right ones are elements.  */                                        
```
is the last situation looks like when allocate(a(2,2,2)) but use the array `a` as  a(1:2,2:2,1:2) ?
so
```fortran
allocate(a(2,2,2))
a=this_image()
call co_sum(a(1:2,2:2,1:2))
```
what will happen? 

what value the dim[n]._ubound and dim[n]._lower_bound should be? 
does the compiler make a copy of array `a` to contiguous one with the same shape and pass it to a subroutine and map it back?

**Comment by afanfa** [comment]
Hi,

I just pushed a patch that should solve the problem. Please let us know how
it goes.

Thanks.

On Wed, Jun 3, 2015 at 7:43 PM, WeiLi <notifications@github.com> wrote:

> Hi,
> How to print out the the size of the each rank of the source in
> co_reduce_1?
> I print the rank, it is 3, seems right for my allocate(a(2,1,2)), but I
> don't know about c and what '->' means.
> is source->dim[j]._ubound the start address ? what is ptrdiff_t? I have
> no idea about the pointer.
>
> could you help me? Thanks
>
>  co_reduce_1 (MPI_Op op, gfc_descriptor_t *source, int result_image, int *stat,
>               char *errmsg, int src_len __attribute__ ((unused)), int errmsg_len)
>  {
>    size_t i, size;
>    int j, ierr;
>    int rank = GFC_DESCRIPTOR_RANK (source);
>
>    fprintf (stderr, "souce have rank %d: from %d \n", rank, caf_this_image);
>    MPI_Datatype datatype = get_MPI_datatype (source);
>
>    size = 1;
>    for (j = 0; j < rank; j++)
>      {
>        ptrdiff_t dimextent = source->dim[j]._ubound
>                              - source->dim[j].lower_bound + 1;
>        if (dimextent < 0)
>          dimextent = 0;
>        size *= dimextent;
>      }
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/3#issuecomment-108542599>
> .
>



-- 

Alessandro Fanfarillo

**Comment by WeiLiPenguin** [comment]
Well done~  works
thanks again!
close issue
