### ISSUE TITLE
Adjust CMakeLists.txt compiler flags to work even for 'Release' build types

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#30]
See also #28 for a more detailed discussion.

**Comment by zbeekman** [comment]
This seems to be a major concern for the folks @homebrew See a length discussion at homebrew/homebrew#46547 I'll try to get to this sometime soon.

**Comment by zbeekman** [comment]
@afanfa and @rouson 

Do either of you know if -O1 will cause bugs, and also if I need to disable -O2 and -O3 globally or just for certain files and/or just for gfortran (as opposed to gfortran AND gcc)

**Comment by afanfa** [comment]
Yes, -O1 and above will cause bugs. I've posted a draft patch on the gfortran mailing list long time ago. I'm going to produce a definitive patch pretty soon.

**Comment by zbeekman** [comment]
Does it cause bugs when compiling the C source code too, or just the
Fortran OCA source code?

Also, after OCA is built is it safe to use these optimization flags or is
it never safe to use them until GCC is patched?

**Comment by afanfa** [comment]
The bugs are related with the Fortran front-end. Any Fortran code that uses OpenCoarrays with an optimization level higher than -O0 is not safe (yet).

**Comment by zbeekman** [comment]
OK, that's actually great news from the build system perspective. I think we can just add a -O0 on the end of all the Fortran compiler flags (maybe via and advance CMake cache variable) which will override any previously inserted -O[1-3].

**Comment by afanfa** [comment]
I just posted the patch on the gfortran and opencoarrays mailing lists. The patch is pretty easy to review, it shouldn't take too long.

**Comment by rouson** [comment]
@zbeekman and @afanfa thanks for investigating and fixing this.  Of course, optimization will be very important to users -- especially for parallel code.

**Comment by zbeekman** [comment]
yes, ideally the cmake file can do some introspection on the compiler or in lieu of that just read the compiler version to determine which flags are safe.

**Comment by sourceryinstitute** [comment]
CMake introspection of compiler identity should be pretty robust.  Introspection of compiler version is very recent for Fortran compilers.  I think CMake 3.4.0 is the first version to correctly identify Fortran compiler versions and CMake 3.4.1 is required for identifying Fortran compiler version on Cray platforms. In lieu of that, I sometimes use the C compiler version as a proxy. This of course works only if the C and Fortran compiler are from the same vendor and use the same version numbering, e.g., it works with GNU, but fails with the NAG Fortran compiler (which has gcc as its companion C compiler) and I believe that using C as a proxy would fail with the Cray compilers (if I recall correctly, their C/C++ compilers don't have the same version numbering as their Fortran compiler).  See the top-level CMakeLists.txt file for my current strategy.   Probably the best thing is just to bump the minimum CMake version requirement to 3.4.1 soon, which of course also means install.sh will have to build CMake for most people for the the near future.

**Comment by zbeekman** [comment]
The folks from Kitware seem to be proponents of the type of introspect where you test functionalities and features rather than keeping track of compiler versions. In a this particular case, the complications of non-gnu compilers should not come into play for this issue because it's coding around a bug in Gfortran itself.

**Comment by rouson** [comment]
> On Dec 6, 2015, at 4:36 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> The folks from Kitware seem to be proponents of the type of introspect where you test functionalities and features rather than keeping track of compiler versions.
> 
Good to know.  That sounds smart. You’ll see some of that type of introspection in the top-level CMakeLists.txt file too. That file references CheckFortranSourceCompiles.cmake, which is also in the top-level source directory.  The latter file does some introspection via testing of functionality.
> In a this particular case, the complications of non-gnu compilers should not come into play for this issue because it's coding around a bug in Gfortran itself.
> 

Sounds good.

D

**Comment by zbeekman** [comment]
This appears to be fixed by #71
