### ISSUE TITLE
sync image race condition with gcc trunk

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#301]
See discussion in #299

**Comment by zbeekman** [comment]
I think this could be the cause of the test failure in `async_comp_alloc` related to an email from @jerryd:

> Hi Zaak,
> 
> Se below. One failure. Have not see this before.  I am going to update gcc trunk
> and rebuild and try this again.
> 
>       Start  8: register_alloc_comp_2
>  8/34 Test  #8: register_alloc_comp_2 ............   Passed    0.03 sec
>       Start  9: register_alloc_comp_3
>  9/34 Test  #9: register_alloc_comp_3 ............   Passed    0.03 sec
>       Start 10: async_comp_alloc
> 10/34 Test #10: async_comp_alloc .................***Timeout   3.39 sec
>       Start 11: get_array
> 11/34 Test #11: get_array ........................   Passed    0.28 sec
> 
> Let me know what you think.

**Comment by vehre** [comment]
This issue has nothing to do with sync images. It is the cause of #260 (the allocation part) not being addressed yet. I therefore advise to close this issue and use #260 for tracking.

**Comment by zbeekman** [comment]
Ah, yes, my mistake.... I knew about this too.... sorry for the noise.
