### ISSUE TITLE
Build of mpich fails on freeBSD

### ISSUE THREAD

**Issue by jerryd** [sourceryinstitute/opencoarrays#320]
With master, executing in top directory, gcc 7.0.0 specified in paths as shown. No installed mpich on this system. Script correctly attempts to build mpich and proceeds to download and compile the source.

If it matters:
$ cmake --version
cmake version 3.7.1
$ flex --version
flex 2.5.37

$ ./install.sh -c /home/jerryd/gcc/usr/bin/gcc -C /home/jerryd/gcc/usr/bin/g++ -f /home/jerryd/gcc/usr/bin/gfortran

... after a while compiling ...

/usr/bin/install -c -m 644 index.html /home/jerryd/dev/opencoarrays/prerequisites/installations/mpich/3.1.4/share/doc/mpich/index.html
install: /home/jerryd/dev/opencoarrays/prerequisites/installations/mpich/3.1.4/share/doc/mpich/index.html: No such file or directory
*** Error code 71

Stop.
make[3]: stopped in /usr/home/jerryd/dev/opencoarrays/prerequisites/builds/mpich-3.1.4
*** Error code 1

Stop.
make[2]: stopped in /usr/home/jerryd/dev/opencoarrays/prerequisites/builds/mpich-3.1.4
*** Error code 1

Stop.
make[1]: stopped in /usr/home/jerryd/dev/opencoarrays/prerequisites/builds/mpich-3.1.4
*** Error code 1

Stop.
make: stopped in /usr/home/jerryd/dev/opencoarrays/prerequisites/builds/mpich-3.1.4
2017-01-28 00:18:30 UTC [     info] Cleaning up. Done
2017-01-28 00:18:30 UTC [     info] Cleaning up. Done

**Comment by zbeekman** [comment]
can you add the the configure line? Also, were there any other errors or warnings? If you could upload the entire log that would be great.

**Comment by jerryd** [comment]
install log


[install-opencoarrays.log.txt](https://github.com/sourceryinstitute/opencoarrays/files/737049/install-opencoarrays.log.txt)

**Comment by zbeekman** [comment]
Well i meant what configure was passed to mpich... I should be able to pull it out of the logs... this looks like a task for @rouson probably, not sure I'll have much time for this anytime soon.

**Comment by rouson** [comment]
From the installation log, it appears the configure line was something like
```
/home/jerryd/dev/opencoarrays/prerequisites/downloads/mpich-3.1.4/src/mpl/configure --disable-option-checking '--prefix=/home/jerryd/dev/opencoarrays/prerequisites/installations/mpich/3.1.4' --disable-versioning 'CC=/home/jerryd/gcc/usr/bin/gcc' 'CXX=/home/jerryd/gcc/usr/bin/g++' 'FC=/home/jerryd/gcc/usr/bin/gfortran' --cache-file=/dev/null --srcdir=/home/jerryd/dev/opencoarrays/prerequisites/downloads/mpich-3.1.4/src/mpl
```
@jerryd Because this happens a ways into the MPICH build, this is probably something to post to an MPICH forum.   I'm unlikely to be able to sort out the issue.  If you have time, please contact the MPICH mailing list.  For now, I'm going to mark this as "won't fix" only because I'm not at all certain we can sort this out ourselves and you have access to package management so hopefully you can still progress.
