### ISSUE TITLE
Incorrect setting for caf_lib_dir in Installed caf script

### ISSUE THREAD

**Issue by nncarlson** [sourceryinstitute/opencoarrays#321]
Using a cmake installation prefix in `/opt/...`, I found that the installed `caf` script sets `caf_lib_dir=lib64` which is incorrect.  It should have been prefixed by the value of `CMAKE_INSTALL_PREFIX`. You're getting the value from `CMAKE_INSTALL_LIBDIR`  which is set by the `GNUInstallDirs` module, and it isn't always an absolute path.  I think maybe you want `CMAKE_INSTALL_FULL_LIBDIR` here.

Same issue for `caf_mod_dir`, but that was irrelevant in my case.

I think this is likely related to some of the issues from #268.

**Comment by zbeekman** [comment]
Many thanks! Yes you're right. I think in most places I need to carefully examine the usage and ensure we have full paths where needed. I'll get to this ASAP

**Comment by zbeekman** [comment]
@nncarlson just curious did you set the prefix at CMake/configure time or build/make time? I'm wondering if I might need to do something clever to treat the case where the user changes the installation location after they have configured with CMake, on the command line to make...

**Comment by nncarlson** [comment]
@zbeekman on the cmake command line.  Often wondered if the cmake-generated makefiles are designed to allow it to be changed on the the make command line as they are with autoconf.

**Comment by zbeekman** [comment]
I think it may depend on the implementation and whether or not they
accounted for it... the short answer, is: theoretically, yes, and
theoretically it *should* be taken care of accurately... it should be
possible, and a correct implementation *should* account for it. But the
problem is it's complicated... IMO CMake is like git, it's the worst
possible option, except for all the alternatives.

**Comment by jerryd** [comment]
Not sure if this is related but on my multi-lib system (both lib and lib64) we seem to be installing in lib and not lib64 even though default compilation is 64-bit. (linux fedora 25). In this case we should consider building for both cases, but the libcas-mpi.a should be placed in lib64

**Comment by jerryd** [comment]
Example, I have LD_LIBRARY_PATH pointing to lib and lib64:

[jerry@amda8 coarrayHelloWorld]$ caf hello_multiverse.F90 
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgfortran.so when searching for -lgfortran
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgfortran.a when searching for -lgfortran
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libquadmath.so when searching for -lquadmath
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libquadmath.a when searching for -lquadmath
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1

[jerry@amda8 coarrayHelloWorld]$ cafrun  ./a.out 

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 13107 RUNNING AT amda8.localdomain
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by zbeekman** [comment]
I'll look into the CMake way of building both 32 and 64bit libs. Should we build shared/dynamic libs and static? Do we need 32 and 64 there as well?

**Comment by zbeekman** [comment]
@jerryd just saw your comment

> Example, I have LD_LIBRARY_PATH pointing to lib and lib64

So are the errors you're seeing because it's in /lib and not lib64?

**Comment by nncarlson** [comment]
@jerryd,  that's odd I'm also on Fedora 25 64-bit, but mine was installed in lib64.  However, GNUInstallDirs does some special things for specific cases of cmake_install_prefix

**Comment by jerryd** [comment]
Tells me I have something broken, so will start clean and report back.

**Comment by jerryd** [comment]
OK now things execute OK after I deleted a a few rogue files. At link time still getting the warning about skipping becasue it is looking for 64bit libs in 32 bit lib directory. It then finds these in lib64. So I think the OpenCoarrays installer, using my custom script and cmake need to build and install in lib64. The same with the building of mpi as well. It is being put in lib and not lib64.

$ ~/dev/usr/bin/caf -m32 hello_multiverse.F90 
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libcaf_mpi.a when searching for -lcaf_mpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libcaf_mpi.a when searching for -lcaf_mpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../../lib/libcaf_mpi.a when searching for -lcaf_mpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../libcaf_mpi.a when searching for -lcaf_mpi
/usr/bin/ld: cannot find -lcaf_mpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpifort.so when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpifort.a when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpifort.so when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpifort.a when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../../lib/libmpifort.so when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../../lib/libmpifort.a when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../libmpifort.so when searching for -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../libmpifort.a when searching for -lmpifort
/usr/bin/ld: cannot find -lmpifort
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpi.so when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpi.a when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpi.so when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libmpi.a when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../../lib/libmpi.so when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../../lib/libmpi.a when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../libmpi.so when searching for -lmpi
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/gcc/x86_64-pc-linux-gnu/7.0.1/../../../libmpi.a when searching for -lmpi
/usr/bin/ld: cannot find -lmpi
collect2: error: ld returned 1 exit status

Compiling with -m64 works except for the skipping incompatible search

$ echo $LD_LIBRARY_PATH/home/jerry/dev/usr/lib:/home/jerry/dev/usr/lib64
[jerry@amda8 caftests]$ ~/dev/usr/bin/caf -m64 hello_multiverse.F90 /usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgfortran.so when searching for -lgfortran
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgfortran.a when searching for -lgfortran
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgfortran.so when searching for -lgfortran
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgfortran.a when searching for -lgfortran
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libquadmath.so when searching for -lquadmath
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libquadmath.a when searching for -lquadmath
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libquadmath.so when searching for -lquadmath
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libquadmath.a when searching for -lquadmath
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: skipping incompatible /home/jerry/dev/usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1
[jerry@amda8 caftests]$ ~/dev/usr/bin/cafrun -n 4 ./a.out  Greetings from image  1 of  4                                                                       
 Greetings from image  2 of  4                                                                       
 Greetings from image  3 of  4                                                                       
 Greetings from image  4 of  4                                                                       
 Test passed.

**Comment by zbeekman** [comment]
@jerryd any chance you can distill this into actionable items? Here's what I'm thinking, but please adjust. 

 - Build 32 and 64 bit libraries (if appropriate)
 - Install into lib and lib64 as appropriate

Should we build static and shared/dynamic by default?

**Comment by zbeekman** [comment]
@nncarlson if you have a chance to test out `master` and confirm for certain that the issue is resolved, we would appreciate it very much. If not, no worries.

**Comment by nncarlson** [comment]
@zbeekman that resolved the issue for me.  Thanks!
