### ISSUE TITLE
install script seeming does nothing

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/OpenCoarrays#329]
```bash
newblue4> ./install.sh 
2017-02-08 11:10:50 UTC [     info] __file: /panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4/install.sh
2017-02-08 11:10:50 UTC [     info] __dir: /panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4
2017-02-08 11:10:50 UTC [     info] __base: install
2017-02-08 11:10:50 UTC [     info] __os: Linux
2017-02-08 11:10:50 UTC [     info] __usage: /panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4/install.sh-usage
2017-02-08 11:10:50 UTC [     info] LOG_LEVEL: 6
2017-02-08 11:10:50 UTC [     info] -b (--install-branch):   
2017-02-08 11:10:50 UTC [     info] -B (--list-branches):    
2017-02-08 11:10:50 UTC [     info] -c (--with-c):           
2017-02-08 11:10:50 UTC [     info] -C (--with-cxx):         
2017-02-08 11:10:50 UTC [     info] -d (--debug):            0
2017-02-08 11:10:50 UTC [     info] -D (--print-downloader): 
2017-02-08 11:10:50 UTC [     info] -e (--verbose):          0
2017-02-08 11:10:50 UTC [     info] -f (--with-fortran):     
2017-02-08 11:10:50 UTC [     info] -h (--help):             0
2017-02-08 11:10:50 UTC [     info] -i (--install-prefix):   /panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4/prerequisites/installations//
2017-02-08 11:10:50 UTC [     info] -I (--install-version):  
2017-02-08 11:10:50 UTC [     info] -j (--num-threads):      1
2017-02-08 11:10:50 UTC [     info] -l (--list-packages):    0
2017-02-08 11:10:50 UTC [     info] -m (--with-cmake):       cmake
2017-02-08 11:10:50 UTC [     info] -M (--with-mpi):         
2017-02-08 11:10:50 UTC [     info] -n (--no-color):         0
2017-02-08 11:10:50 UTC [     info] -p (--package):          opencoarrays
2017-02-08 11:10:50 UTC [     info] -P (--print-path):       
2017-02-08 11:10:50 UTC [     info] -U (--print-url):        
2017-02-08 11:10:50 UTC [     info] -v (--version):          0
2017-02-08 11:10:50 UTC [     info] -V (--print-version):    
2017-02-08 11:10:50 UTC [     info] -y (--yes-to-all):       0
2017-02-08 11:10:50 UTC [     info] install_path="/panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4/prerequisites/installations/"
2017-02-08 11:10:50 UTC [     info] num_threads="1"
2017-02-08 11:10:50 UTC [     info] opencoarrays_src_dir=/panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4
2017-02-08 11:10:50 UTC [     info] build_path="/panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4"/prerequisites/builds
2017-02-08 11:10:50 UTC [     info] build_script="/panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4"/prerequisites/build.sh
newblue4> 
```

What am I missing?

Thanks

Anton

**Comment by zbeekman** [comment]
Hi Anton,

In the future can you please paste code in fenced code blocks? (i.e., between triple back ticks ` ``` ` on their own line above and below the code? Also please add the language if relevant, i.e., ` ```fortran ` in the opening/first triple back tick code fence)

Very odd indeed! Can you please report, include and try the following:

 1. Was OpenCoarrays previously installed on that machine?
 2. Which OS distro, version, kernel etc. ?
 3. Please past the output of `uname -a`
 4. Please rerun the `install.sh` script with the extra `-e` and `-d` flags and report on the value of `$?` immediately after the script exits
 5. Please post the output of 4. and also attach the `install-opencoarrays.log` file (you will have to change the extension to `.txt` to upload it here.)


It looks like the script may be hitting an error condition and silently aborting when checking for `/panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4/prerequisites/installations/` or before...

@rouson any ideas?

**Comment by mexas** [comment]
Q1. Was OpenCoarrays previously installed on that machine?
A1. yes:
```ls -1 OpenCoarrays-1.*gz
OpenCoarrays-1.3.2.tar.gz
OpenCoarrays-1.4.0.tar.gz
OpenCoarrays-1.6.0.tar.gz
OpenCoarrays-1.8.4.tar.gz
```

Q2. Which OS distro, version, kernel etc. ?
A2. No idea. This is a University cluster.

Q3. Please past the output of uname -a
A3.
```
uname -a
Linux newblue4 2.6.32-220.23.1.el6.x86_64 #1 SMP Mon Jun 18 09:58:09 CDT 2012 x86_64 x86_64 x86_64 GNU/Linux
```

Q4. Please rerun the install.sh script with the extra -e and -d flags and report on the value of $? immediately after the script exits
A4.
```
newblue4> ./install.sh -e >& install-e.txt
newblue4> echo $?
2
newblue4> ./install.sh -d >& install-d.txt
newblue4> echo $?
2
```
[install-d.txt](https://github.com/sourceryinstitute/opencoarrays/files/761777/install-d.txt)
[install-e.txt](https://github.com/sourceryinstitute/opencoarrays/files/761779/install-e.txt)

Q5. Please post the output of 4. and also attach the install-opencoarrays.log file (you will have to change the extension to .txt to upload it here.)
A5. I can't find
```
install-opencoarrays.log
```
```
newblue4> pwd
/panfs/panasas01/mech/mexas/OpenCoarrays-1.8.4
newblue4> ls -trl
total 1792
-rw-r--r-- 1 mexas mech  1021 Feb  7 05:19 windows-install.sh-usage
-rwxr-xr-x 1 mexas mech 11775 Feb  7 05:19 windows-install.sh
-rw-r--r-- 1 mexas mech 10637 Feb  7 05:19 STATUS.md
drwxr-xr-x 8 mexas mech  4096 Feb  7 05:19 src
-rw-r--r-- 1 mexas mech 10468 Feb  7 05:19 README.md
drwxr-xr-x 6 mexas mech  4096 Feb  7 05:19 prerequisites
-rw-r--r-- 1 mexas mech  1518 Feb  7 05:19 LICENSE
-rw-r--r-- 1 mexas mech  1671 Feb  7 05:19 install.sh-usage
-rwxr-xr-x 1 mexas mech 13986 Feb  7 05:19 install.sh
-rw-r--r-- 1 mexas mech 12351 Feb  7 05:19 INSTALL.md
-rw-r--r-- 1 mexas mech  5694 Feb  7 05:19 GETTING_STARTED.md
drwxr-xr-x 3 mexas mech  4096 Feb  7 05:19 doc
-rw-r--r-- 1 mexas mech  8427 Feb  7 05:19 CONTRIBUTING.md
-rw-r--r-- 1 mexas mech 21001 Feb  7 05:19 CMakeLists.txt
drwxr-xr-x 3 mexas mech  4096 Feb  7 05:19 cmake
-rw-r--r-- 1 mexas mech 23735 Feb  7 05:19 CAF_ABI.md
-rw-r--r-- 1 mexas mech   921 Feb  7 05:19 Brewfile
-rw-r--r-- 1 mexas mech   769 Feb  7 05:19 AUTHORS.md
-rw-r--r-- 1 mexas mech 25652 Feb  8 19:43 install-e.txt
-rw-r--r-- 1 mexas mech 28190 Feb  8 19:43 install-d.txt
newblue4> find . -name "install-opencoarrays.log"
newblue4> 
```

Thanks

Anton

**Comment by zbeekman** [comment]
Thanks so much! I guess the install.log file is missing because it never started compiling etc. I'll look through this and try to figure out what's going on

**Comment by rouson** [comment]
Based on the final lines in [install-e.txt](https://github.com/sourceryinstitute/opencoarrays/files/761779/install-e.txt), it appears the problem is related to the [stack_peep](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/prerequisites/stack.sh#L250) function that I added to a stack utility imported from [another project](http://brizzled.clapper.org/blog/2011/10/28/a-bash-stack/).  If necessary, stack_peep can be eliminated eliminated because it mostly consists of calls to two other stack functions.  First, it would be good to see the results of running the unit tests for our installation scripts.  @mexas please post the output of the following:

```bash
cd OpenCoarrays-1.8.4/src/tests/installation
./installation-scripts.sh 
```
which should produce output similar to the following:
```bash
~/opencoarrays/src/tests/installation ~/opencoarrays/src/tests/installation
2017-02-14 19:37:29 UTC [     info] test-stack.sh: All tests passed.
~/opencoarrays/src/tests/installation
2017-02-14 19:37:29 UTC [     info] Cleaning up. Done
```

**Comment by mexas** [comment]
```
$ cd OpenCoarrays-1.8.4/src/tests/installation/
$ ./installation-scripts.sh 
~/OpenCoarrays-1.8.4/src/tests/installation ~/OpenCoarrays-1.8.4/src/tests/installation
$ 
```

**Comment by zbeekman** [comment]
It's weird that you are getting this result but the installation proceeded correctly in the past. This section of code hasn't changed in quite some time, so it would appear that your environment is different. Also, it is worth noting that you are running a relatively ancient Linux kernel judging from the output of `uname -a`.

Can you please see which bashes are available:

```
$ which -a bash
$ type -a bash
```

And then see which bash is in your environment and its version:

```
$ which bash
$ ps
$ echo "${BASH_VERSION}" # assuming your shell is in fact bash or ...
$ $(which bash) -c "echo \${BASH_VERSION}" # this will pick up the bash on your path...
```

And then lastly lets see which bashes are on your system:
```bash
for bash in $(which -a bash); do
  ${bash} -c "echo \${BASH_VERSION}"
done
```

**Comment by mexas** [comment]
I use tcsh. Is that a problem?

**Comment by rouson** [comment]
@mexas That confirms that the failure is in stack.sh as suspected.  

Because the Linux kernel version on your system is approximately 5 years old, I'm not certain that we'll be able to support it, but if the problem is in stack_peek as indicated by your previous output, I could create a branch with a version of OpenCoarrays that eliminates the need for that function.  If you'd like to try that, let me know.

@zbeekman I just ran `./installation-scripts.sh -d` and observed some interesting behaviors: the result included output from two emergency statements, which would seem to be impossible with `set -o errexit`.  The two emergency statements were in a function that is not invoked anywhere (`stack_destroy`) so it's of no consequence, but it's interesting behavior nonetheless.

**Comment by zbeekman** [comment]
> I use tcsh. Is that a problem?

It worked in the past and it should not be a problem. Can you please let me know the output of the commands I listed above? Also the output of `/usr/bin/env bash -c "echo \$BASH_VERSION"`

@rouson set -x outputs all sorts trace info, so it's not necessarily calling abort... I haven't looked at your bash tests in detail yet, so I'm not 100% up to date on what's going on.

**Comment by mexas** [comment]
Well, your commands are already specific to bash.
Would be great if your build system didn't depend on the exact shell.

Anyway, as you asked:

```bash
newblue2> which -a bash
-a: Command not found.
/bin/bash
newblue2> type -a bash
type: Command not found.
newblue2> bash
[mexas@newblue2 OpenCoarrays-1.8.4]$ which -a bash
/bin/bash
[mexas@newblue2 OpenCoarrays-1.8.4]$ type -a bash
bash is /bin/bash
[mexas@newblue2 OpenCoarrays-1.8.4]$ which bash
/bin/bash
[mexas@newblue2 OpenCoarrays-1.8.4]$ ps 
  PID TTY          TIME CMD
 9594 pts/4    00:00:00 tcsh
11495 pts/4    00:00:00 bash
11945 pts/4    00:00:00 ps
[mexas@newblue2 OpenCoarrays-1.8.4]$ echo "${BASH_VERSION}"
4.1.2(1)-release
[mexas@newblue2 OpenCoarrays-1.8.4]$ for bash in $(which -a bash); do
>   ${bash} -c "echo \${BASH_VERSION}"
> done
4.1.2(1)-release
[mexas@newblue2 OpenCoarrays-1.8.4]$ 
```

Anton

**Comment by zbeekman** [comment]
@mexas if you want installation that doesn't depend on bash, try the "advanced" installation. You must ensure that dependencies (gfortran, CMake, MPI) are met yourself, then adapt the following for c shell:

```
export FC=gfortran # assuming its on your PATH and is GFortran >= 6
export CC=gcc # again assumes on PATH, otherwise specify full path
cd OpenCoarrays/dir
mkdir build
cd build
# ensure MPI is available and any environment modules are loaded, consider exporting MPI_HOME=/path/to/MPI/installation if CMake has trouble finding it
cmake .. # you may want to set install prefix etc.
make -j
make test
make install
```

See the corresponding section in INSTALL.md for further details.

**Comment by mexas** [comment]
yes, using cmake directly works fine.
Feel free to close this PR.
