### ISSUE TITLE
Limit root/sudo aspect of installation

### ISSUE THREAD

**Issue by tclune** [sourceryinstitute/opencoarrays#34]
It is understandable, albeit, unfortunate that the ./install.sh script requires sudo access.

However, the opencoarray-installation directory should definitely not be owned by root.

**Comment by rouson** [comment]
@tclune, fyi, sudo is not needed for a default installation with no arguments:

./install.sh

Such an installation results in an opencoarrays-installation directory that is not owned by root. Up until the commit that I just made and that I will merge into the master branch tomorrow (Tuesday), sudo was required if the user passed an installation path that requires root privileges:

sudo ./install.sh /installation/path/requiring/root/permissions

As soon as I merge this commit into our master branch (which will be included in our next release), ./install.sh will check whether the user has write permission for the chosen installation path.  If not, then install.sh uses sudo only for the final "make install" step of the OpenCoarrays installation.  That sudo invocation will prompt the user for his or her password if necessary. 

On a related note, the default installation location for all prerequisites is in a directory of the form

opencoarrays/install_prerequisites/name-version-installation

where "name" is replaced with the package name and "version" is replaced with the version number.  At the present time, if one desires to install any prerequisites elsewhere, they must be installed individually in the following manner:

cd install_prerequisites
./build cmake <version-number> /desired/installation/path

where <version-number> can be replaced with "--default" for the default choice.  If a prerequisite is installed in the above manner, then "build" performs analogously to "install.sh" in that it only invokes "sudo" for the final "make install" step if necessary.  I'll close this issue when I merge the commit.

**Comment by zbeekman** [comment]
@tclune I believe this issue has been addressed in PR #84 which has been merged. I'm going to close this issue for now, unless you object. You can try the latest script by cloning the `master` branch, or if you're more patient than I am, you can wait until the next release which should be in a week or two. If you find that it has not been adequately addressed, feel free to reopen the issue.

**Comment by tclune** [comment]
Thanks - I’ll wait for the update (and probably still need to be prodded gently by Damian).

Cheers,

- Tom

> On Dec 23, 2015, at 11:02 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> @tclune <https://github.com/tclune> I believe this issue has been addressed in PR #84 <https://github.com/sourceryinstitute/opencoarrays/pull/84> which has been merged. I'm going to close this issue for now, unless you object. You can try the latest script by cloning the master branch, or if you're more patient than I am, you can wait until the next release which should be in a week or two. If you find that it has not been adequately addressed, feel free to reopen the issue.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/sourceryinstitute/opencoarrays/issues/34#issuecomment-167038351>.
> 

Thomas Clune, Ph. D. 	<Thomas.L.Clune@nasa.gov>
Software Infrastructure Team Lead
Global Modeling and Assimilation Office, Code 610.1
NASA GSFC		
MS 610.1 B33-C128
Greenbelt, MD 20771
301-286-4635
