### ISSUE TITLE
consider changing caf and cafrun permissions to 555

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/OpenCoarrays#340]
ATM caf and cafrun are installed as 777, which is unsafe.
E.g. FreeBSD refuses to install under /usr/local/bin with such perms.
Consider changing to 555 by default:

```
-    PERMISSIONS WORLD_EXECUTE WORLD_READ WORLD_WRITE OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EX
ECUTE GROUP_READ GROUP_WRITE
+    PERMISSIONS WORLD_EXECUTE WORLD_READ OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ
     DESTINATION "${CMAKE_INSTALL_BINDIR}"
```
in
```
src/mpi/CMakeLists.txt
```

Thanks

Anton

**Comment by zbeekman** [comment]
hmmmm, I thought I had adjusted these... I'll make sure they are 555 in the next release.

**Comment by rouson** [comment]
Thanks for reporting this @mexas
