### ISSUE TITLE
Implement Gnu Build System (Autotools) and then provide an RPM package suitable for Fedora and possibly other Linux distributions.

### ISSUE THREAD

**Issue by jerryd** [sourceryinstitute/OpenCoarrays#343]
Using existing RPM tools provided by Fedora Distribution and following requirements and guidelines for official distributions. Target x86_64 architecture first, folowed by i686

**Comment by jerryd** [comment]
I thought I would capture what I am really doing here. I have made some progress in that autoconf is generating a ./configure script and the ./configure is generating Makefiles. The make is attempting to compile libcaf.c. Now working on the definition of PREFIX based on compiler environment. Starting to get the 'hang' of it so to speak.

**Comment by jerryd** [comment]
Status: autoconf is building the ./configure script. The subsequent make is building libcaf_mpi.a. The make install is installing the library to the user provided --prefix= directory given to ./configure.  The build process can be done from a directory separate from the source tree.

Starting on better location of the mpich library and executables using available m4 scripts.
Starting on generation of the caf and cafrun scripts and will coordinate with Zaak's work on consolidating the head and foot files into one file.

**Comment by jerryd** [comment]
Note to self. Currently I am setting some flags to some defaults values in configure.ac. I have the use of pkg-config commented out. I plan to re-enable pkg-config and set those variables to the defaults if pkg-config is not found.  This will provide additional flexibility as we decide what the defaults should be.  Also not that the "philosophy" of configure is to set variables manually in the configure invocation when non-standard locations are used. It is quite evident that the various installations of mpich use a lot of non-standard locations. Using pkg-config will help with a lot of these

**Comment by rouson** [comment]
@jerryd , my sense is that this is ready modulo the macOS issues that @zbeekman and I have reported, but I don't see resolving those issues as being critical to closing this issue. If this is working on Linux, then I suggest we consider this sufficiently complete to move forward with putting the OpenCoarrays tar ball on the GCC server and submitting the configure changes to the relevant GCC list(s) for review. As a compromise position, I might even be ok with merging this into the OpenCoarrays master branch if we can limit the new files in the top-level source directly to one file.  One idea would be to write an extremely short bash script named `configure`, or something like `configure.sh` or `configure-sh`, and let that script simply move all the required files from whatever is their permanent location into the top-level source directory and then the final line would simply invoke the actual `configure` file.  I very much hope we can find a way to bring this effort to a rapid conclusion (i.e., this week or next week at the absolute latest) that at least provides some basic level of functionality that is considered ready for release.  If this drags into August, I fear the original requestors will begin to conclude that it's a never-ending project.

**Comment by jerryd** [comment]
Current status. The build works without issue on Fedora system. On Lubuntu ./configure generates the Makefiles without error. Executing make compiles the library fine.  However when attempting to link the first test case, hello_universe, it complains about needing to use -fPIC

**Comment by zbeekman** [comment]
Currently the library must always be compiled with -fPIC in the CMake build
(and it is). The CMake build creates shared and static libraries, and
defaults to linking the tests to the shared library, IIRC. It should be
easy to add -fPIC to the tests, or link them against the static library in
the GNU AutoTools build, no?

**Comment by iGeorgeX** [comment]
Does it work to create RPM packages? Or is there still a problem with -fPIC?

**Comment by rouson** [comment]
Notes from 16 March Google Hangouts discussion about Daniel's collaborator:

* Integration of OpenCoarrays into GCC autotools build system:
   - Previous work by @jerryd is on branch issue-343-gnu-build.
   - Talk with @zbeekman about his past investigations on building on macOS.
   - Read [GNU Autotools manual], [Autotools book] by Calcote on O’Reilly, and documentation on the GNU build system

2. Convert OpenCoarrays C header to Fortran module.
    - Jerry says the dependences can include Fortran programs (see configure & src/Makefile.am files in issue-343-gnu-build

3. Incremental conversion of OpenCoarrasy MPI layer from C to Fortran.

[GNU Autotools manual]: https://www.gnu.org/software/automake/
[Autotools book]: http://shop.oreilly.com/product/9781593272067.do

**Comment by rouson** [comment]
Note from 2018-03-23 OpenCoarrays Hangout:

@dcelisgarza Jerry mentions that the libtool dependency in the issue-343-gnu-build branch can be removed if we "libtoolize" the branch.  @zbeekman mentioned that it creates a macro that emulates libtool.  Check the GCC ChangeLog to see who has made a recent change on the GCC build scripts to find a candidate for someone who might be able to assist with your work.

**Comment by susilehtola** [comment]
I've succesfully packaged OpenCoarrays for Fedora using CMake.

**Comment by uihsnv** [comment]
@susilehtola I ask because I'm unaware of the intricacies involved, but why not use the `cmake` way of configuring? Why is `autotools` better?

**Comment by rouson** [comment]
Unless @jerryd disagrees, I think it makes sense to mark this issue as "Won't Fix" and close the issue.  My understanding is that the Autotools scripts on the issue-343-gnu-build branch works for building OpenCoarrays.  The difficulty is in modifying the GCC build system so to automatically build OpenCoarrays whenever gfortran is built.  We've had two developers attempt this over the past ~2 years so I think it's time to assume it's not likely to happen unless and until someone new comes along and is sufficiently motivated and knowledgeable about the GCC build system.

**Comment by jerryd** [comment]
On 08/21/2018 07:56 PM, Damian Rouson wrote:
> Unless @jerryd <https://github.com/jerryd> disagrees, I think it makes 
> sense to mark this issue as "Won't Fix" and close the issue. My 
> understanding is that the Autotools scripts on the issue-343-gnu-build 
> branch works for building OpenCoarrays. The difficulty is in modifying 
> the GCC build system so to automatically build OpenCoarrays whenever 
> gfortran is built. We've had two developers attempt this over the past 
> ~2 years so I think it's time to assume it's not likely to happen unless 
> and until someone new comes along and is sufficiently motivated and 
> knowledgeable about the GCC build system.
> 

I agree. Frustrating, but I think focusing on distribution packages is 
effort better spent. (such as Fedora)

Jerry
