### ISSUE TITLE
Defect: Fork OpenCoarrays & then delete devel

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#346]
# Defect: delete stale  branch #

The devel branch contains features that we have decided will not be merged into master.  @zbeekman will verify that there is nothing obvious to save.  @afanfa will fork if it is desired to retain any of the code.  Then one of us can delete devel.

**Comment by rouson** [comment]
@afanfa has forked to preserve anything he wants from devel.  @zbeekman, shall we delete devel?

**Comment by zbeekman** [comment]
`git log --oneline --no-merges --left-only origin/devel...origin/master` will show which commits are on devel but not master... going through this now, and double checking this matches what github says. Will delete in a moment.

**Comment by zbeekman** [comment]
Without `--no-merges` then merge commits are shown too... the number of commits (26) shown by `git log --oneline --left-only origin/devel...origin/master | wc -l` matches what Github says here: https://github.com/sourceryinstitute/OpenCoarrays/branches/stale

However there are only 12 actual substantive commits:

`$ git log --oneline --no-merges --left-only origin/devel...origin/master`

 1. 8d800bd Add draft of OFP build script and ofp wrapper
 1. 7648496 Add source transformation test targets and outputs
 1. 19024e9 Require SOURCE & OFP_HOME passed to Makefile CLI
 1. ba94c70 Add `caf_init` and `caf_finalize` calls to `Scope`
 1. 0ddccf4 Support `sync images` with image set & stat list
 1. 0833778 Add initial usage of OFP for s2s translation
 1. c4ba404 Revert "Add OFP as git submodule connected to #119"
 1. 913f4c0 Add OFP as git submodule connected to #119
 1. 81c0bb3 Update markdown files in `devel` to match `master`
 1. 987c879 Add CMake build types including coverage build
 1. b2d931d Fix ABI link & add badges to README
 1. 3e8296f Create devel branch via merge --squash old changes

**Comment by zbeekman** [comment]
I can confirm that there is nothing here that needs to be ported to master. Closing and deleting.
