### ISSUE TITLE
Defect: --wrapping option is not accepted

### ISSUE THREAD

**Issue by LaHaine** [sourceryinstitute/OpenCoarrays#352]
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

Please replace `[ ]` with `[X]` to indicate you have taken the requested action

# Defect/bug report #
This is with opencoarrays 1.8.5. The wrapper script caf lists the options if called without any arguments:
````
caf - Fortran compiler wrapper for OpenCoarrays

 Usage: caf <fortran-source-file> [options] ...

 Options:
   --help, -h               Show this help message
   --version, -v, -V        Report version and copyright information
   --wrapping, -w, --wraps  Report the name of the wrapped compiler
[…]
````
The option --wrapping does not work, but -w does:
````
# caf --wrapping
gfortran: error: unrecognized command line option ‘--wrapping’; did you mean ‘--graphite’?
# caf -w
caf wraps CAFC=/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/bin/mpif90
````
I propose to either remove the --wrapping option or make it work like -w.

 - [x] I have searched the [issues page] and [mailing list] and did
       not find any issue matching the one I would like to report
 - [x] I have included a succinct description of the problem,
       including the steps necessary to reproduce it
 - [x] I have included which version of OpenCoarrays I am working
       with, or the output of `git describe` if working with a cloned
       repository rather than an [official release]
  1.8.5
 - [x] I have included the MPI library name and version I am using
       with OpenCoarrays
   - [x] name: [Open-MPI] version:1.10.6
 - [x] I have included the Fortran compiler name and version that I am
       using with OpenCoarrays: gfortran 6.2.1
 - [x] I have included the output of `uname -a` 
Linux pax11.zeuthen.desy.de 3.10.0-514.6.1.el7.x86_64 #1 SMP Tue Jan 17 11:12:41 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
 - [x] I have included the Operating system name and version,
       including linux distro: Scientific Linux 7.3
 - [x] I have included the machine name if I am allowed to do so and
       wish to seek help debugging on that particular system (Titan,
       Pleiades, Excalibur, Lightening, Mira, etc.)

**Comment by zbeekman** [comment]
Oh I see now... the help doesn't match the implementation
