### ISSUE TITLE
Improve defaults for install.sh script

### ISSUE THREAD

**Issue by tclune** [sourceryinstitute/opencoarrays#36]
When the script prompts with [y/n], it would be more conventional to use "[Y/n]" .  Note the capitalization.  A <return> will then do the default (capitalized) option.   

One could make the argument that this is less safe.   I only point out that previous scripts have led my intuition to blindly hit return and cross my fingers rather than think, or worse, read the instructions.  :-)

**Comment by zbeekman** [comment]
I may try to tackle this in the coming days or weeks. It will make sense to have something a little bit more sane setup as we expand our Travis-CI test matrix to include coverage of the install.sh script.
