### ISSUE TITLE
Update INSTALL.md for new installation options

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#368]
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

# RFE: #

[INSTALL.md](INSTALL.md) needs to be updated to reflect the newest installation options:
- [X] Freshports on FreeBSD (see [Issue 338] for links)
- [x] APT on Debian-based distributions such as Ubuntu
- [x] linuxbrew on all Linux distributions (probably the most most up-to-date because it pulls from homebrew, which updates automatically)

[links]:#

[issue stat img]:https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square
[Issue 338]: https://github.com/sourceryinstitute/OpenCoarrays/issues/338

**Comment by zbeekman** [comment]
Linuxbrew is most up to date, after homebrew, since it pulls formula updates from Homebrew, which updates automagically when we mint a new release.

**Comment by zbeekman** [comment]
Also, the [OpenCoarrays website](opencoarrays.org) should be updated too.

**Comment by rouson** [comment]
The new installation options are now mentioned in INSTALL.md and the OpenCoarrays web site has been updated to include the new options so I'll close this.

As an aside, sometime soon I'll explore setting up a GitHub Pages site for OpenCoarrays and redirecting OpenCoarrays.org to it.
