### ISSUE TITLE
Question: shall we update mpif90/mpirun to mpifort/mpiexec?

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#378]
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

Please replace `[ ]` with `[X]` to indicate you have taken the requested action

 - [X] I have surrounded any code, or log output in codeblock fences
       (` ``` `) if it occupies more than one line, or in single
       backticks if it is short `short code`

# Question: #

1. The [MPI 3.1](http://mpi-forum.org/docs/mpi-3.1/mpi31-report.pdf) standard mentions that many implementations provide `mpirun` but recommends providing `mpiexec`.  
2. MPI 3.1 mentions `mpif90` in a similar manner but is silent on `mpifort`.  However, comments online indicate a preference for the latter to liberate the name of the command from a specific revision of the Fortran standard.

I don't know of any implementations that don't provide `mpirun` or `mpif90`, but it seems reasonable to switch to `mpifort` and `mpiexec` for standard-conformance and clarity where the former two are employed.  On the master branch, I find the following locations:
- [x] [windows-install.sh](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/windows-install.sh#L243),
- [x] at several places in [find_or_install.sh](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/prerequisites/install-functions/find_or_install.sh), and
- [x] at two places in [report_results.sh](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/prerequisites/install-functions/report_results.sh).

Motivation: I'm introducing `caf` and `cafrun` early the new book so this is a good time to update these commands to versions that are more standard or modern.

**Comment by zbeekman** [comment]
doing this with #268

**Comment by rouson** [comment]
@zbeekman given the simplicity of this issue, shall we simply implement a quick fix rather than tie it to #268, of which this is presumably a tiny component?

**Comment by zbeekman** [comment]
sure, but it's not quite as trivial as it seems, because it pops up a few
places... what I should do is just cherry pick the commit off my work and
merge that.. I'll do that now
