### ISSUE TITLE
Build error: MacPorts port install fails on Sierra

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#379]
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

## Installation/build problem ##

MacPorts fails to install OpenCoarrays 1.8.10 on macOS Sierra:
```bash
$ sudo port install opencoarrays
--->  Computing dependencies for OpenCoarrays
--->  Staging OpenCoarrays into destroot
Error: Failed to destroot OpenCoarrays: error renaming "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/work/destroot/opt/local/mod/opencoarrays.mod": no such file or directory
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_science_OpenCoarrays/OpenCoarrays/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port opencoarrays failed
$ uname -a
Darwin localhost 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```
This occurs with and without previous versions of OpenCoarrays installed and with both the gcc6 and gcc7 MacPorts ports and the corresponding mpich ports.

 - [X] I have surrounded any code, or log output in codeblock fences
       (` ``` `) if it occupies more than one line, or in single
       backticks if it is short `short code`
 - [X] I have searched the [issues page] and [mailing list] and did
       not find any issue matching the one I would like to report
 - [X] I have included a succinct description of the problem,
       including the steps necessary to reproduce it
 - [X] I have included which version of OpenCoarrays I am working
       with, or the output of `git describe` if working with a cloned
       repository rather than an [official release]
 - [X] I have included the MPI library name and version I am using
 - [X] I have included the Fortran compiler name and version that I am
       using with OpenCoarrays
 - [X] I have included the output of `uname -a`
 - [X] I have included the Operating system name and version,
       including linux distro
 - [X] I have indicated if previous versions of OpenCoarrays are or
       were installed on the machine in question
 - [X] Build/install was attempted with  [MacPorts]

**Comment by zbeekman** [comment]
It looks like the port file may need to know a-priori where things get installed to... Does that sound right? I did some minor tweaking to the mod file installation location, and some more may come in the not so distant future... because mod files should be specific to compiler and compiler version, so I was name spacing opencoarrays.mod with the compiler ID and version and then also created a symbolic link. I'll try to look at the port file definition and see if I have any ideas for a quick fix.

**Comment by rouson** [comment]
@afanfa Any thoughts on this?  On a related note, it's probably a good idea to update your macOS laptop to the latest OS (Sierra), which should be free.

**Comment by zbeekman** [comment]
I tried to look at this, but IMO macports is a mess... I have a lot of trouble following the DSL for defining ports and their dependencies... @afanfa any time to investigate?

**Comment by afanfa** [comment]
@zbeekman I'll take a look at this later today. I don't have my Mac with me at the moment.

**Comment by rouson** [comment]
MacPorts now installs OpenCoarrays 1.8.6 correctly on macOS Sierra so I believe this can be closed.  I'll create a second issue to request that the MacPorts port be updated to install the latest release.
