### ISSUE TITLE
Bug: report_results.sh sometimes sets incorrect cmake path

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#385]
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

# Defect/bug report #
In the current version of the Sourcery Institute VM, the `cmake` executable in the `PATH` lives in a path that includes a directory named `cmake`
```
which cmake
/opt/cmake/3.7.0/bin/cmake
```
I suspect this is the reason that [line 18] in report_results.sh yields the incorrect value:
```
  cmake_install_path="${fully_qualified_CMAKE%%/cmake*}"
```
which assigns the value `/opt`.  I will submit a pull request shortly that fixes this. @zbeekman is there some reason that cmake was treated differently in the the path variables set near the top of report_results.sh?

[line 18]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/prerequisites/install-functions/report_results.sh#L18

**Comment by zbeekman** [comment]
I don't recall at the moment. I'm definitely confused as to why this is the
greedy version. (Two %s instead of just one.) One % should fix this...) Git
blame (or better yet open in github and click "blame") should show the
commit that introduced this which hopefully will have some context.

**Comment by zbeekman** [comment]
(I'll look when I'm back at my computer)
