### ISSUE TITLE
RFE: Add EasyBuild option in INSTALL.md

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#387]
| Avg response time              |
| ------------------------------ |
| ![Issue Stats][issue stat img] |

# Request for Enhancement: #

Cranfield University Ph.D. student Anuj Sharma (@anujsharmax) has created a configuration file that facilitates building OpenCoarrays  with the [EasyBuild] build and installation framework for HPC systems.  EasyBuild's documentation states that "EasyBuild has mostly been used and tested on x86_64-based Linux systems... Limited provisions for other Unix-based operating systems (e.g., Mac OS X) are also available."  Let's add this to the list of Linux installation options in the [Linux section] of INSTALL.md and consider whether to mention it in the macOS section as well.  Anuj will fork OpenCoarrays, add the appropriate text to our INSTALL.md on a branch, and submit a pull request.

[links]:#
[EasyBuild]: https://github.com/hpcugent/easybuild
[Linux section]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#linux

**Comment by rouson** [comment]
Anuj will also mention the existing support for build OpenCoarrays so there are two new ones to mention in INSTALL.md

- [ ] [Easybuild](https://github.com/hpcugent/easybuild)
- [ ] [Spack](https://github.com/LLNL/spack)

**Comment by zbeekman** [comment]
Are these build systems where we'll host the files defining the build, or is there a central repository we submit them to? It would be nice to take a look at the build setups.

**Comment by zbeekman** [comment]
@rouson: Will you see @anujsharmax during your travels? It would be great to post the package definitions and build instructions here soon, and close this issue.

**Comment by rouson** [comment]
We were supposed to meet today, but he was unable to make it to the
meeting.

Best Regards,
_______________________
Damian Rouson, Ph.D., P.E.
President, Sourcery Institute
www.sourceryinstitute.org
+1-510-600-2992 (mobile)

**Comment by zbeekman** [comment]
Should we close this issue, or should I email someone to get it unstuck?

**Comment by anujsharmax** [comment]
hi @zbeekman,
Sorry for the delays - The [Easyconfig](https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/o/OpenCoarrays) for OpenCoarrays became part of Easybuild in yesterday's release. I'll update the INSTALL.md file today.

**Comment by zbeekman** [comment]
Amazing @anujsharmax! Thanks so much!



> I'll update the INSTALL.md file today.

Yes, if you could submit a pull request with instructions on how to use EasyBuild/EasyConfig that would be great! I've never used it before, so try to be concise, but thorough so that new users can figure it out. Also, if we have a better understanding, then we can help maintain the [Easyconfig file](https://github.com/easybuilders/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/o/OpenCoarrays).

Also, do you know the status of Spack? Is there an OpenCoarrays recipe there too? If so, how does one use it?

**Comment by anujsharmax** [comment]
Sure @zbeekman.

Spack already supports OpenCoarrays using a similar [package.py](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/opencoarrays/package.py) file in their repository.

I'll include the instructions for installing OpenCoarrays, both for Spack and Easybuild, in my pull request.

**Comment by zbeekman** [comment]
Fabulous! I'm reading up about Spack now, it seems the package.py needs
some updating

**Comment by anujsharmax** [comment]
With Spack, I was able to download the latest version of OpenCoarrays with an extra argument to the installation command. But you are right - I'll add another line for the latest version in the [package.py](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/opencoarrays/package.py) file.

**Comment by zbeekman** [comment]
Also, Spack is still passing mpicc and mpifort as the compilers to CMake
which is deprecated... And it might be wise to put a dependency on a recent
GCC... alghtough perhaps some people want to play with the minimal s2s
transformations and collectives using other compilers? But at least some
sort of warning should be issued for non Fortran >= 5

**Comment by anujsharmax** [comment]
I've added the instructions for Linux only, but they might be applicable to macOS as well. While Spack supports both Linux and macOS, EasyBuild supports macOS only partially (based on their respective manuals). 

I don't have access to macOS, so I couldn't check the instructions on it.  If someone else can check it, I can update the PR.

**Comment by zbeekman** [comment]
I'll try to remember to add a link to the instructions from the MacOS section to the #spack section. If EB doesn't fully support MacOS let's not add it, our build systems and package managers are already multiplying more quickly than we can keep up with.

Thanks for your contribution, @anujsharmax! 🎉
