### ISSUE TITLE
`image_fail_and_sync_test_2` hangs when run in rapid succession

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/OpenCoarrays#390]
`image_fail_and_sync_test_2` seems to reliably hang if you run the test multiple times in succession: https://travis-ci.org/sourceryinstitute/OpenCoarrays/jobs/235412457#L1160

If you run with, e.g.,  `ctest --output-on-failure --repeat-until-fail 10` you might be able to trigger this on your own machine... another idea may be to try running it more oversubscribed.

This test is similar to the tests bearing the same name, but with the 1 and 2 suffixes. The biggest difference is that this test calls `sync images(*, STAT=...)` whereas the other two test `sync all (STAT=...)` and `image_status()`.

**Comment by vehre** [comment]
That flag as developer_test still does not work. I do have the environment variable
`declare -x OPENCOARRAYS_DEVELOPER="ON"`
set, but the test is not run.

**Comment by zbeekman** [comment]
> That flag as developer_test still does not work. I do have the environment variable
> declare -x OPENCOARRAYS_DEVELOPER="ON"
> set, but the test is not run.

1. It looks like you merged in upstream changes after making some commits, so it's possible this change wasn't incorporated until then
2. You need to re-run CMake after setting the environment variable
3. If the problem still persists, try deleting the CMake cache (you can just wipe out the entire build directory and re-create it)
4. If none of these suggestions fixes it, then I'm quite puzzled... We could set up a screen share or a [warp](https://github.com/spolu/warp) sometime so that I can take a look for myself

**Comment by zbeekman** [comment]
OK, I've hammered away testing this on my local system which closely mimics the VM running on Travis-CI. Despite trying many times, I'm not able to reproduce the "bug" that we see on Travis-CI wherein the test hangs when re-run. Because of this, I'm going to mark this as "invalid" and only run that one test in the "developer tests" on the "allowed failures" Travis-CI job.
