### ISSUE TITLE
FreeBSD install can now use packages

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/OpenCoarrays#395]
FreeBSD users can now simply do (as root):
```
pkg install opencoarrays
```
The suggested link on FreeBSD ports/packages installation:

https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/ports.html

I suggest you update the text on
https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#freebsd

BTW, the opencoarrays.org home page FreeBSD link is wrong -
it points to windows text.

**Comment by rouson** [comment]
@mexas, I just corrected the link on opencoarrays.org.  Thanks for reporting this.

**Comment by rouson** [comment]
@mexas I just submitted [pull request 416](https://github.com/sourceryinstitute/OpenCoarrays/pull/416 in response to your suggestions in this issue. Please feel free to suggest better text if I've missed the mark.

**Comment by zbeekman** [comment]
@mexas, PR #416 merged, but please to take a look at https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#freebsd and suggest any changes...
