### ISSUE TITLE
missing mpif90

### ISSUE THREAD

**Issue by finneyb** [sourceryinstitute/opencoarrays#41]
Was able to successfully complete the  install using the "automatic" installation script.  Went to try the test problems in the tests directory, but the Makefiles refer to mpif90, which does not appear to be something that is installed.  

BTW, you mention that opencoarrays is working on some of the worlds biggest machines, well I may have it working on one of the smallest machines, a $38 quadcore ARM7 machine the size of the deck of cards.  However, I would like to verify it is working, so I need some test problems.  I am not familiar with coarrays (yet), hence my effort to use the examples in the test directory.

**Comment by zbeekman** [comment]
Can you run `ctest` from the build directory? Will this complain about missing mpif90?

**Comment by finneyb** [comment]
On 12/6/2015 6:24 AM, Izaak Beekman wrote:
> Can you run |ctest| from the build directory? Will this complain about
> missing mpif90?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sourceryinstitute/opencoarrays/issues/41#issuecomment-162320816>.
>

That worked fine, with the exception of one test (see below).  ctest 
must not be using mpif90 which is what is listed in the Makefiles in the 
Testing directories.

Test project /usr/local/bin/opencoarrays/opencoarrays-build
       Start  1: initialize_mpi
  1/22 Test  #1: initialize_mpi ...................   Passed    0.04 sec
       Start  2: register
  2/22 Test  #2: register .........................   Passed    0.04 sec
       Start  3: register_rename_me
  3/22 Test  #3: register_rename_me ...............   Passed    0.04 sec
       Start  4: register_rename_me_too
  4/22 Test  #4: register_rename_me_too ...........   Passed    0.04 sec
       Start  5: allocate_as_barrier
  5/22 Test  #5: allocate_as_barrier ..............   Passed    1.07 sec
       Start  6: allocate_as_barrier_proc
  6/22 Test  #6: allocate_as_barrier_proc .........   Passed    1.04 sec
       Start  7: get_array
  7/22 Test  #7: get_array ........................   Passed    0.57 sec
       Start  8: send_array
  8/22 Test  #8: send_array .......................   Passed    0.89 sec
       Start  9: get_with_offset_1d
  9/22 Test  #9: get_with_offset_1d ...............   Passed    0.04 sec
       Start 10: whole_get_array
10/22 Test #10: whole_get_array ..................   Passed    0.04 sec
       Start 11: strided_get
11/22 Test #11: strided_get ......................   Passed    0.04 sec
       Start 12: co_sum
12/22 Test #12: co_sum ...........................   Passed    0.12 sec
       Start 13: co_broadcast
13/22 Test #13: co_broadcast .....................   Passed    0.08 sec
       Start 14: co_min
14/22 Test #14: co_min ...........................   Passed    0.07 sec
       Start 15: co_max
15/22 Test #15: co_max ...........................   Passed    0.06 sec
       Start 16: syncall
16/22 Test #16: syncall ..........................   Passed    7.30 sec
       Start 17: syncimages
17/22 Test #17: syncimages .......................   Passed    8.02 sec
       Start 18: co_reduce
18/22 Test #18: co_reduce ........................   Passed    0.12 sec
       Start 19: hello_multiverse
19/22 Test #19: hello_multiverse .................   Passed    0.04 sec
       Start 20: coarray_burgers_pde
20/22 Test #20: coarray_burgers_pde ..............   Passed    0.11 sec
       Start 21: co_heat
21/22 Test #21: co_heat ..........................   Passed   33.13 sec
       Start 22: coarray_navier_stokes
22/22 Test #22: coarray_navier_stokes ............***Failed  Required 
regular expression not found.Regex=[Test passed.
]  0.03 sec

95% tests passed, 1 tests failed out of 22

Total Test time (real) =  52.95 sec

The following tests FAILED:
          22 - coarray_navier_stokes (Failed)
Errors while running CTest

**Comment by afanfa** [comment]
The problem with the navier_stokes solver is most likely related with the FFTs and WALLTIME functions written for x86. You may want to try with LEGACY_ARCHITECTURE=ON and HIGH_RESOLUTION_TIMER=OFF ("Advanced options" in INSTALL.md).

**Comment by finneyb** [comment]
Regarding the original issue, that was my error.  The build script did not install mpich because it was already on the machine and I had not noticed that.  Issue closed.  
I am still having trouble with the last test, but will open a different issue for that.
