### ISSUE TITLE
1.9.1 all tests pass on FreeBSD 

### ISSUE THREAD

**Issue by mexas** [sourceryinstitute/OpenCoarrays#433]
Well done guys.
FreeBSD 11.1-RELEASE, Clang 4.0.0, GCC from 5.4 to 8.0, MPICH 3.2.
```
100% tests passed, 0 tests failed out of 41
```
I updated the FreeBSD port.

**Comment by zbeekman** [comment]
🎉 🎆 🎊 🌈 :unicorn: 👏 

Glad to hear things are working well!!!!

FYI I think I have upstreamed all of your FreeBSD related build system patches. Please let me know what, if any, additional patching you're doing.

There are a bunch of patches from, and tweak for Debian that still haven't quite made it in yet.

Also, thanks so much 🙇 for the prompt release of the new port! 💯

**Comment by zbeekman** [comment]
@mexas please do let me know if you're doing any patching of the build system. If not, let's please close this issue. Thanks!

**Comment by mexas** [comment]
no patches!
