### ISSUE TITLE
Defect: Failed images support not enabled during tests

### ISSUE THREAD

**Issue by afanfa** [sourceryinstitute/OpenCoarrays#437]
Sorry for not using the template but I believe this issue should be mostly used for discussion.
Is the --disable-auto-cleanup string passed at runtime for the failed images tests?
Is the --enable-error-checking=all string passed at configure time for mpich?

**Comment by zbeekman** [comment]
Interesting...

- yes `-disable-auto-cleanup` is passed to `mpiexec` when running failed images tests. Do you have evidence to the contrary?
- As for `--enable-error-checking=all` being passed at configure time for MPICH, I'm not 100% sure. The only circumstance under which we install MPICH as part of the installation process is when using `install.sh`. I'm guessing, as of right now, that we don't pass `--enable-error-checking=all` at configure time for MPICH.

Is MPICH being built with `--enable-error-checking=all` a required condition for failed images to work properly? Do you know how to detect if MPICH was built this way?

Right now, the logic for enabling failed images is:

 1. GCC/GFortran >= 1? Yes: try to enable failed images & proceed to 2. No: disable failed images
 2. Are the required proposed/experimental MPI functions available? Yes: Enable failed images, No: do not enable failed image support

In addition, failed images tests are only run if `OPENCOARRAYS_DEVELOPER=TRUE` (or `1` or `YES` or `ON`)

**Comment by zbeekman** [comment]
According to the MPICH wiki `--enable-error-checking=all` is on by default: https://wiki.mpich.org/mpich/index.php/Fault_Tolerance#Usage .. double checking the output of `./configure` for MPICH now, to confirm

**Comment by zbeekman** [comment]
```
  --enable-error-checking=level
      Control the amount of error checking.
        no        - no error checking
        runtime   - error checking controllable at runtime through environment
                    variables
        all       - error checking always enabled (default)
```
