### ISSUE TITLE
Suggested GFortran coarray cleanup patch

### ISSUE THREAD

**Issue by jabl** [sourceryinstitute/OpenCoarrays#497]
For GFortran 8 (expected to be released spring 2018) character lengths have been changed to be size_t rather than int. This patch does the same changes to the coarray API, and also to use plain int rather than int32_t for process exit values.

See https://gcc.gnu.org/ml/fortran/2018-02/msg00039.html

**Comment by zbeekman** [comment]
Thanks so much for reminding us to address this, Janne!
