### ISSUE TITLE
real `getopts` based script argument parsing

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#50]
`getopts` argument parsing for [`install.sh`](../blob/master/install.sh) and [`build`](../blob/master/install_prerequisites/build)

**Comment by rouson** [comment]
Thanks for adding this.  I'm curious about what the "help wanted" label does. Will it notify other developers that we could use some assistance?  I assume they'll only see it if their visiting our site, which is fine -- no reason to spam folks.  I've been thinking about hiring someone via TaskRabbit to do this. I bet there's a developer out there who knows this stuff cold and is interested in contract work.  Alternatively, if we can find a good example to work from, that would be great.

**Comment by zbeekman** [comment]
@rouson You can add tags by clicking the sprocket icon to the right of the "Labels" text which is to the right, and upwards from this text. Below that, you can also pick milestones, and assign the issue to a particular person in the @sourceryinstitute organization, like, me, you or @afanfa.

Feel free to edit/create/delete labels. This can be done here (it happens on a per-repository basis): https://github.com/sourceryinstitute/opencoarrays/labels

GitHub starts all repositories with a number of default labels, but then you can add/remove more as you see fit. I just added some that I thought could be helpful to have. In this case, I don't remember if `help wanted` is a default label or if I added it, but it can help encourage community contributions and let people know which issues we're soliciting help for. It has no effect (it doesn't email any pool of developers or anything) other than tagging the issue for organizational purposes, and helping communicate to people who find themselves browsing our issues that it is an area we would welcome outside help on. (You can also link to views of issues by tags, etc. so on the README.md or CONTRIBUTING.md you can point people to ways that they can help out.)

You can also [create milestones](https://github.com/sourceryinstitute/opencoarrays/milestones) and attach issues to those, to track progress towards that goal... perhaps not necessary but it's an additional organizational tool.

**Comment by rouson** [comment]
Great idea.  Thanks!

**Comment by zbeekman** [comment]
I have made some contributions to https://github.com/kvz/bash3boilerplate which now has a phenomenal setup for minimal duplication of documenting and implementing option flags for shell scripts. It allows one to write a flag/option usage statement to a bash variable (which can then later be printed in the usage statement message) and parses this documentation to generate option parsing with `getopts`. Flag/option documentation strings look something like this:

```bash
# Commandline options. This defines the usage page, and is used to parse cli
# opts & defaults from. The parsing is unforgiving so be precise in your syntax
# - A short option must be preset for every long option; but every short option
#   need not have a long option
# - `--` is respected as the separator between options and arguments
read -r -d '' usage <<-'EOF' || true # exits non-zero when EOF encountered
  -f --file  [arg] Filename to process. Required.
  -t --temp  [arg] Location of tempfile. Default="/tmp/bar"
  -v               Enable verbose mode, print script as it is executed
  -d --debug       Enables debug mode
  -h --help        This page
EOF
```

This `$usage` variable is then parsed and a getopts command line option parsing loop is create which handles these options and their arguments, including default values.

**Comment by rouson** [comment]
Let's talk about this in our next call. Anything that helps with parsing command-line arguments is very welcome, but I'm not immediately understand how to incorporate and I'm wary about adding a node.js dependency.  We're already swimming in dependencies.  I could be convinced and I would probably choose a JavaScript dependency such as node.js over a Java dependency. I look forward to hearing more.

**Comment by zbeekman** [comment]
There's no node.js dependency. We can chat on our call.

**Comment by zbeekman** [comment]
To elaborate some more, this is a strictly copy paste solution in pure bash3. It doesn't add a dependency of any kind, just helps us get a sane/easy/usable option parsing scheme up and running.
