### ISSUE TITLE
Defect: cmake does not (always) correctly detect MPI features

### ISSUE THREAD

**Issue by aetx** [sourceryinstitute/OpenCoarrays#509]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

- OpenCoarrays Version: 1.9.2 and 2.0.0-rc1-5-gd88bfd0
- Fortran Compiler: GCC 7.2.0
- C compiler used for building lib: GCC 7.2.0
- Installation method: tarball/git clone + cmake
- Output of `uname -a`: `Linux jrl10 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- MPI library being used: ParaStationMPI 5.2.0 (wrapped with slurm 17.02.9 when run)
- Machine architecture and number of physical cores: x64_64 & 2 * 12 cores per node
- Version of CMake: 3.10.2

OpenCoarrays compiled using 
~~~
CC=gcc FC=gfortran cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.modules/libopencoarrays/1.9.2_gcc7.2.0
~~~

## Observed Behavior ##
When running `cmake` it seems to find `MPIX_Comm_failure_get_acked`
~~~
-- Looking for MPIX_ERR_PROC_FAILED
-- Looking for MPIX_ERR_PROC_FAILED - found
-- Looking for MPIX_ERR_REVOKED
-- Looking for MPIX_ERR_REVOKED - found
-- Looking for MPIX_Comm_failure_ack
-- Looking for MPIX_Comm_failure_ack - found
-- Looking for MPIX_Comm_failure_get_acked
-- Looking for MPIX_Comm_failure_get_acked - found
-- Looking for MPIX_Comm_shrink
-- Looking for MPIX_Comm_shrink - found
-- Looking for MPIX_Comm_agree
-- Looking for MPIX_Comm_agree - found
-- Looking for include file mpi.h
-- Looking for include file mpi.h - found
-- Looking for I_MPI_VERSION
-- Looking for I_MPI_VERSION - not found
~~~
However, when running the code it is not implemented in ParaStationMPI 5.2.0 and the following error appears
~~~
Warning: MPID_Comm_failure_get_acked() not implemented
Warning: MPID_Comm_failure_get_acked() not implemented
Warning: MPID_Comm_failure_get_acked() not implemented
Warning: MPID_Comm_failure_get_acked() not implemented
Fatal error in PMPIX_Comm_agree: Unsupported file operation , error stack:
PMPIX_Comm_agree(183): MPIX_Comm_agree(MPI_COMM_WORLD) failed
PMPIX_Comm_agree(169): 
MPIR_Comm_agree(49)..: 
(unknown)(): Unsupported file operation Fatal error in PMPIX_Comm_agree: Unsupported file operation , error stack:
PMPIX_Comm_agree(183): MPIX_Comm_agree(MPI_COMM_WORLD) failed
PMPIX_Comm_agree(169): 
MPIR_Comm_agree(49)..: 
(unknown)(): Unsupported file operation Fatal error in PMPIX_Comm_agree: Unsupported file operation , error stack:
PMPIX_Comm_agree(183): MPIX_Comm_agree(MPI_COMM_WORLD) failed
PMPIX_Comm_agree(169): 
MPIR_Comm_agree(49)..: 
(unknown)(): Unsupported file operation Fatal error in PMPIX_Comm_agree: Unsupported file operation , error stack:
PMPIX_Comm_agree(183): MPIX_Comm_agree(MPI_COMM_WORLD) failed
PMPIX_Comm_agree(169): 
MPIR_Comm_agree(49)..: 
(unknown)(): Unsupported file operation srun: error: jrc0538: tasks 0-3: Exited with exit code 44
~~~

When compiling with `-DCAF_ENABLE_FAILED_IMAGES=FALSE` the functions are still found, but the code runs without aborting.

## Expected Behavior ##
CMake should correctly identify whether the functions may be used or not.

Although this may be a bigger problem for this case, as CMake just checks if their symbols appear in the MPI library and they seem to be there.

## Steps to Reproduce ##
Compile OpenCoarrays with failed image support, then run a program using coarrays.

**Comment by zbeekman** [comment]
Hmmm, interesting. It does seem that we need to be a little more rigorous in determining whether the detected features actually work.

For the time being, a work around is to pass `-DCAF_ENABLE_FAILED_IMAGES=FALSE` when configuring with CMake.

**Comment by zbeekman** [comment]
The solution to this will be to use introspection to compile and run a test program using the MPIX features. Fun times. This is not a high priority but should be easy to do.

**Comment by zbeekman** [comment]
The experimental/proposed ULFM features did not make it into MPI 4, furthermore, it was determined that a big re-work is required. As such we have turned off enabling ULFM support by default even when the build system detects it. While this does, in principle, still need fixing, I'm going to close this as "won't fix" until the ULFM implementation stabilizes a bit and we have something reliable to test against.
