### ISSUE TITLE
Rectify differences between `master` and `branch-1.0.0`

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#52]
Ensure the only differences between the 1.x release branch, `branch-1.0.0` and `master` are intentional and resolve any unintended conflicts.

Some differences are clearly intentional, like the mpi_cuda work on master, and the install script modifications on the release branch (which likely may be safely absorbed into master, but I don't know if @rouson wants me to attempt this or if he would prefer doing it himself).

```diff
 CAF_API.txt => CAF_ABI.txt                          |  159 ++--
 CMakeLists.txt                                      |   73 +-
 COPYRIGHT-BSD3                                      |   18 +-
 GETTING_STARTED.md                                  |    2 +-

branch-1.0.0 wins for all these:
 doc/dependency_tree/opencoarrays-tree.txt           |    9 +
 install.sh                                          |  807 +++++++++++++++----
 install_prerequisites/build                         |  130 +++-
 install_prerequisites/stack.sh                      |  209 +++++

This was updated in mid-November in preparation for SC15.  Go with whichever branch has a commit just before the November 15 tutorial (presumably master branch):
 src/cuda_mpi/Makefile                               |   21 -
 src/cuda_mpi/mpi_caf.c                              | 2517 ------------------------------------------------------------
 src/extensions/caf-foot                             |    1 +
 src/extensions/opencoarrays.F90                     |  221 +-----
 src/make.inc                                        |    2 +-
 src/mpi/mpi_caf.c                                   |   69 +-
 src/tests/integration/gpu/Makefile                  |   27 -
 src/tests/integration/gpu/co_dot.f90                |  152 ----
 src/tests/integration/gpu/kernelCaller.cu           |  176 -----
 src/tests/unit/extensions/CMakeLists.txt            |    6 +-
 src/tests/unit/extensions/this_image_num_images.f90 |   62 --
 src/tests/unit/simple/CMakeLists.txt                |    4 +-
 20 files changed, 1113 insertions(+), 3552 deletions(-)
```

**Comment by rouson** [comment]
If you feel comfortable doing so, please go ahead and move install.h to the master branch and move the entire install_prerequisites/ directory to master as well, replacing the version of that directory on master. Nothing in master's version of install.sh needs to be saved and nothing in master's install_prerequisites/ directory needs to be saved. Of course,  all of this needs to be tested, but it seems that should be automatic now that we have Travis-CI. :)

**Comment by zbeekman** [comment]
Hi Alessandro (@afanfa),
Damian (@rouson) and I wanted you input on the differences to `src/mpi/mpi_caf.c` [between master and branch-1.0.0](https://github.com/sourceryinstitute/opencoarrays/compare/master...branch-1.0.0#diff-775a104746a19927fb80aad9b039981f)

Here is the diff, where `-` indicates something on `master` but not `branch-1.0.0` and `+` indicates something on `branch-1.0.0` but not on `master`

```diff
diff --git a/src/mpi/mpi_caf.c b/src/mpi/mpi_caf.c
index 414289e..5cf36a4 100644
--- a/src/mpi/mpi_caf.c
+++ b/src/mpi/mpi_caf.c
@@ -104,13 +104,6 @@ char err_buffer[MPI_MAX_ERROR_STRING];
    MPI_COMM_WORLD for interoperability purposes. */
 MPI_Comm CAF_COMM_WORLD;
 
-/* Shared memory variables */
-#ifdef SHARED
-MPI_Comm SHARED_COMM;
-int *local_ranks, *global_ranks, local_size;
-MPI_Group local_group, global_group;
-static int shared_win = MPI_KEYVAL_INVALID;
-#endif
 /* For MPI interoperability, allow external initialization
    (and thus finalization) of MPI. */
 bool caf_owns_mpi = false;
@@ -366,29 +359,7 @@ PREFIX (init) (int *argc, char ***argv)
 
       MPI_Comm_size(CAF_COMM_WORLD, &caf_num_images);
       MPI_Comm_rank(CAF_COMM_WORLD, &caf_this_image);
-#ifdef SHARED
-      MPI_Comm_split_type(CAF_COMM_WORLD,MPI_COMM_TYPE_SHARED,0,MPI_INFO_NULL, &SHARED_COMM);
-      MPI_Comm_group(SHARED_COMM, &local_group);
-      MPI_Comm_group(MPI_COMM_WORLD, &global_group);
-      MPI_Group_size(local_group, &local_size);
-
-      local_ranks = (int *) malloc(local_size * sizeof(int));
-      global_ranks = (int *) malloc(caf_num_images * sizeof(int));
-
-      for (i = 0; i < local_size; i++)
-	local_ranks[i] = i;
-      
-      MPI_Group_translate_ranks(local_group, local_size, local_ranks, global_group, global_ranks);
-
-      for(i = 1; i < caf_num_images; i++)
-      	if(global_ranks[i] == 0)
-      	  global_ranks[i] = -1;
 
-      if(shared_win == MPI_KEYVAL_INVALID)
-	MPI_Win_create_keyval(MPI_WIN_NULL_COPY_FN,
-			      MPI_WIN_NULL_DELETE_FN,
-			      &shared_win, (void *)0);
-#endif
       caf_this_image++;
       caf_is_finalized = 0;
 
@@ -521,11 +492,8 @@ void *
   /* Token contains only a list of pointers.  */
 
   *token = malloc (sizeof(MPI_Win));
-  MPI_Win *p = token[0];
 
-#ifdef SHARED
-  MPI_Win *p_local = malloc(sizeof(MPI_Win));
-#endif
+  MPI_Win *p = *token;
 
   if(type == CAF_REGTYPE_LOCK_STATIC || type == CAF_REGTYPE_LOCK_ALLOC ||
      type == CAF_REGTYPE_CRITICAL || type == CAF_REGTYPE_EVENT_STATIC ||
@@ -538,13 +506,7 @@ void *
     actual_size = size;
 
 #if MPI_VERSION >= 3
-#ifdef SHARED
-  MPI_Win_allocate_shared(actual_size, 1, MPI_INFO_NULL, SHARED_COMM, &mem, p_local);
-  MPI_Win_create(mem, actual_size, 1, mpi_info_same_size, CAF_COMM_WORLD, token[0]);
-  MPI_Win_lock_all(MPI_MODE_NOCHECK, *p_local);
-#else
   MPI_Win_allocate(actual_size, 1, mpi_info_same_size, CAF_COMM_WORLD, &mem, *token);
-#endif
 # ifndef CAF_MPI_LOCK_UNLOCK
   MPI_Win_lock_all(MPI_MODE_NOCHECK, *p);
 # endif // CAF_MPI_LOCK_UNLOCK
@@ -553,11 +515,7 @@ void *
   MPI_Win_create(mem, actual_size, 1, MPI_INFO_NULL, CAF_COMM_WORLD, *token);
 #endif // MPI_VERSION
 
-  p = token[0];
-#ifdef SHARED
-  /* shared window attached to remote window as attribute */
-  MPI_Win_set_attr(*p, shared_win, (void*)p_local);
-#endif
+  p = *token;
 
   if(l_var)
     {
@@ -996,16 +954,6 @@ PREFIX (send) (caf_token_t token, size_t offset, int image_index,
         for (i = 0; i < (dst_size-src_size)/4; i++)
               ((int32_t*) pad_str)[i] = (int32_t) ' ';
     }
-#ifdef SHARED
-  if(global_ranks[image_index-1] != -1)
-    {
-      /* Images on same node. Let's use the shared memory window */
-      int flag = 0;
-      MPI_Win_get_attr(*p,shared_win,&p,&flag);
-      image_index = global_ranks[image_index-1];
-      image_index++;
-    }
-#endif
   if (rank == 0
       || (GFC_DESCRIPTOR_TYPE (dest) == GFC_DESCRIPTOR_TYPE (src)
           && dst_kind == src_kind && GFC_DESCRIPTOR_RANK (src) != 0
@@ -1389,16 +1337,7 @@ PREFIX (get) (caf_token_t token, size_t offset,
         for (i = 0; i < (dst_size-src_size)/4; i++)
               ((int32_t*) pad_str)[i] = (int32_t) ' ';
     }
-#ifdef SHARED
-  if(global_ranks[image_index-1] != -1)
-    {
-      /* Images on same node. Let's use the shared memory window */
-      int flag = 0;
-      MPI_Win_get_attr(*p,shared_win,&p,&flag);
-      image_index = global_ranks[image_index-1];
-      image_index++;
-    }
-#endif
+
   if (rank == 0
       || (GFC_DESCRIPTOR_TYPE (dest) == GFC_DESCRIPTOR_TYPE (src)
           && dst_kind == src_kind
@@ -1727,7 +1666,7 @@ PREFIX (sync_images) (int count, int images[], int *stat, char *errmsg,
 	       goto sync_images_err_chk;
 	     }
 	 }
-
+       
        for(i=0; i < count; i++)
          ierr = MPI_Send(&caf_this_image, 1, MPI_INT, images[i]-1, 0, CAF_COMM_WORLD);
 
```

I can't seem to determine, just from the commit history and commit dates of this file on [master (here)](https://github.com/sourceryinstitute/opencoarrays/commits/master/src/mpi/mpi_caf.c) and [branch-1.0.0 (here)](https://github.com/sourceryinstitute/opencoarrays/commits/branch-1.0.0/src/mpi/mpi_caf.c) how to determine what changes should remain unique to one branch or the other, or which changes should be merged in one or both branches.

**Comment by afanfa** [comment]
All the changes from master to branch in mpi_caf.c are related to a new feature i"m testing (shared memory windows). Such feature is disabled by default and It should remain only on the master branch.

**Comment by zbeekman** [comment]
Great, thanks for the input @afanfa

**Comment by zbeekman** [comment]
@afanfa and @rouson I'd love to borrow your eyeballs to look at this discrepancy: In [opencoarrays.F90](../blob/master/src/extensions/opencoarrays.F90) it looks like the 1.x branch has a bug. Here is the diff:

```diff
diff --git a/src/extensions/opencoarrays.F90 b/src/extensions/opencoarrays.F90
index 8dd0786..91ddaed 100644
--- a/src/extensions/opencoarrays.F90
+++ b/src/extensions/opencoarrays.F90
@@ -220,7 +269,7 @@ subroutine opencoarrays_co_reduce(a, opr, opr_flags, result_image, stat, errmsg,
 #ifdef COMPILER_SUPPORTS_CAF_INTRINSICS
       bind(C,name="_caf_extensions_co_reduce")
 #else
-      bind(C,name="_gfortran_extensions_co_reduce")
+      bind(C,name="_gfortran_caf_co_reduce")
 #endif
       use iso_c_binding, only : c_ptr,c_funptr,c_int,c_char
       type(c_ptr), intent(in), value :: a
```

I suspect that `_gfortran_caf_co_reduce` is the correct binding. [A search seems to verify that](https://github.com/search?q=_gfortran_caf_co_reduce&type=Code&utf8=✓)

[Here is the line in question on master](https://github.com/sourceryinstitute/opencoarrays/blame/master/src/extensions/opencoarrays.F90#L272) which was committed Nov 5 and appears to be a bug fix. [Here is the line on 1.x](https://github.com/sourceryinstitute/opencoarrays/blame/branch-1.0.0/src/extensions/opencoarrays.F90#L223)

**Comment by rouson** [comment]
@zbeekman, yes, the version on master is the correct one.

**Comment by zbeekman** [comment]
OK, PRs #57 and #58 are almost ready to go, as far as I can tell... Tomorrow we should discuss workflow, and whether and how to reintegrate a common history between these two branches... Also some line ending and white-space cleanup is in order, and if we do this, it might be a good opportunity to take care of all of it at once.

**Comment by rouson** [comment]
@zbeekman, the COMPILER_SUPPORTS_CAF_INTRINSICS gets defined in src/mpi/CMakeLists.txt when the compiler is gfortran and the version is less than 5.  Not setting the aforementioned variable should produce a linking error some I'm a little perplexed as to why this wasn't discovered sooner.

My first thought is that  it relates some somehow to the fact gfortran had a co_reduce bug before version 5.3. Because that compiler bug generated test failures, we would  have ignored any test failures for gfortran 5.1.0 or 5.2.0, but that doesn't explain why no linking error showed up when building with versions 5.2.0 or 6.0.0, which are both versions that I test prior to release.  

An enigma wrapped in a conundrum...

**Comment by zbeekman** [comment]
Sorry, @rouson... are you saying that this is a bug existing in both master and branch-1.0.0? If so, it might warrant a new issue being created... I'll have a look and see if I can I understand the behavior you're seeing, and get to the bottom of what's going on.

**Comment by zbeekman** [comment]
If you are online now, and want to discuss, here is the private SourceryInstitute chatroom: https://gitter.im/sourceryinstitute

**Comment by zbeekman** [comment]
Once #57 and #58 are merged the difference between master and branch 1.x will look like this:

```
$ git diff issue-52-synchronize-master-to-branch issue-52-synchronize-branches-to-master --stat
 CMakeLists.txt                                      |  44 +++++++++++++++--
 src/cuda_mpi/Makefile                               |  21 ++++++++
 src/{mpi => cuda_mpi}/mpi_caf.c                     |  66 ++++++++++++++++---------
 src/extensions/opencoarrays.F90                     | 193 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 src/make.inc                                        |   2 +-
 src/mpi/mpi_caf.c                                   |  69 ++++++++++++++++++++++++--
 src/tests/integration/gpu/Makefile                  |  27 +++++++++++
 src/tests/integration/gpu/co_dot.f90                | 152 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/tests/integration/gpu/kernelCaller.cu           | 176 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/tests/unit/extensions/CMakeLists.txt            |   2 +-
 src/tests/unit/extensions/this_image_num_images.f90 |  62 ++++++++++++++++++++++++
 11 files changed, 778 insertions(+), 36 deletions(-)
```

After this, only 4 files would have potential merge conflicts now, down from 14, and each one should be straightforward to determine how to fix.

**Comment by rouson** [comment]
I figured it out. It is a bug in branch-1.0.0, but it is inconsequential in then most likely scenarios. The bug is in the API. If the compiler version is >5, then the compiler calls the ABI directly and what is in the API doesn't matter.  If the compiler version is < 5.3, then the erroneous code doesn't get built because of the preporiceeor variable definition.  

The one scenario when the bug would matter is if the compiler version is >=5 and the user's code contains a "use opencoarrays" statement. Such a statemement is a direct reference to to the API.  Such a reference would cause s linking error due to the erroneous code. Correcting the binding name will eliminate the problem. 

Wow. I'm amazed that you caught this.  Great job. I guess it exposes a gap in the test coverage.

**Comment by rouson** [comment]
I wrote the last response and the current one on my phone and can't edit it. 

"<5.3" should have been "<5"

I was mixing up the version number in the preprocessor conditional with the version number in with a gfortran co_reduce bug was fixed.

**Comment by zbeekman** [comment]
I fixed it for you...

Yeah, getting the test-coverage analysis up will help us find some more places where tests might be lacking... However, there are a lot of scenarios and it's tough to test all of them.

We should probably also start adding regression tests: each time we fix a defect we add a test that will fail before the defect is fix is applied and will pass afterwards.

BTW, if you get a chance to look at PR #57 and #58 tonight, and give me a :+1: `:+1:` to merge, it will help me continue to make progress... but if you can't look tonight that's fine

I guess we should change the `COMPILER_SUPPORTS_CAF_INTRINSICS` on both branches too?

**Comment by rouson** [comment]
> On Dec 14, 2015, at 7:14 PM, Izaak Beekman <notifications@github.com> wrote:
> 
> I fixed it for you...
> 

Thanks!

> Yeah, getting the test-coverage analysis up will help us find some more places where tests might be lacking... However, there are a lot of scenarios and it's tough to test all of them.
> 
> We should probably also start adding regression tests: each time we fix a defect we add a test that will fail before the defect is fix is applied and will pass afterwards.
> 
> 

Sounds good.
> BTW, if you get a chance to look at PR #57 <https://github.com/sourceryinstitute/opencoarrays/pull/57> and #58 <https://github.com/sourceryinstitute/opencoarrays/issues/58> tonight, and give me a  :+1: to merge, it will help me continue to make progress... but if you can't look tonight that's fine
> 
Done.
> I guess we should change the COMPILER_SUPPORTS_CAF_INTRINSICS on both branches too?
> 
> 

Sounds good.

Damian

**Comment by zbeekman** [comment]
Here is the diff --stat between 1.x and master, as it currently stands:

```
$ git diff branch-1.0.0 master --stat
 CMakeLists.txt                                      |  42 ++++++++++++++++-
 src/{mpi => cuda_mpi}/Makefile                      |   6 +--
 src/{mpi => cuda_mpi}/mpi_caf.c                     |  66 +++++++++++++++++---------
 src/extensions/opencoarrays.F90                     | 189 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
 src/make.inc                                        |   2 +-
 src/mpi/Makefile                                    |   7 +--
 src/mpi/helper.c                                    | 180 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/mpi/mpi_caf.c                                   | 176 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------
 src/tests/integration/gpu/Makefile                  |  27 +++++++++++
 src/tests/integration/gpu/co_dot.f90                | 152 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/tests/integration/gpu/kernelCaller.cu           | 176 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/tests/unit/extensions/this_image_num_images.f90 |  62 ++++++++++++++++++++++++
 12 files changed, 1036 insertions(+), 49 deletions(-)
```

Also, here is the comparison of some critical directories with @afanfa's fork (on master) just to ensure everything looks right:

```diff
$ git diff afanfa/master master -b -w -- src/mpi/ src/extensions/ src/cuda_mpi/diff --git a/src/extensions/caf-foot b/src/extensions/caf-foot
index 9afc0dc..59155e4 100755
--- a/src/extensions/caf-foot
+++ b/src/extensions/caf-foot
@@ -67,6 +67,7 @@ fi

 # TODO -- improve the syntax of the "set" command below to accepted an unlimited number of arguments
 max_arguments=100
+link_args="-fcoarray=lib -lcaf_mpi"

 if [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
     echo ""
diff --git a/src/extensions/opencoarrays.F90 b/src/extensions/opencoarrays.F90
index 2dea2e5..3a4ae14 100644
--- a/src/extensions/opencoarrays.F90
+++ b/src/extensions/opencoarrays.F90
@@ -36,7 +36,7 @@ module opencoarrays
 #elif defined(COMPILER_LACKS_C_SIZEOF_ASSUMED_RANK)
   use iso_c_binding, only : c_int,c_char,c_ptr,c_loc,c_double,c_int32_t,c_bool,c_funloc,c_ptrdiff_t
 #else
-  use iso_c_binding, only : c_int,c_char,c_ptr,c_loc,c_float,c_double,c_int32_t,c_bool,c_funloc,c_ptrdiff_t,c_sizeof
+  use iso_c_binding, only : c_int,c_char,c_ptr,c_loc,c_double,c_int32_t,c_ptrdiff_t,c_sizeof,c_bool,c_funloc,c_float
 #endif
   implicit none

```

Note here in `opencoarrays.F90` there has only been a re-ordering in the `only` clause. Also, the flags are for ignoring whitespace issues.

**Comment by rouson** [comment]
I can never remember the ordering of arguments to diff and, in this case, it might not help because I don't know what "a" designates versus "b".   When posting diffs pleased preface them with a description of the form "+ designates something in file x or branch x that is missing in file y or branch y..."

**Comment by rouson** [comment]
In this case, by doing a fresh clone, I surmise that the predominance of + signs indicates that many things were added on master that did not migrate to branch-1.0.0, which is the expected result.  I'm not aware of any issues that would prevent your moving forward as planned.  Work your magic. :)

**Comment by zbeekman** [comment]
Yup, I'll try to remember to do this in the future. I am posting the difference between @afanfa's latest commits to his fork on master which are the (-) and how the development branch looks now (+) (i.e. this is "master," but only `master` for the next 5 minutes or so, due to renaming of the branches master ==> level and 1.x ==> master

**Comment by zbeekman** [comment]
CC: @rouson @afanfa 

`master` and `branch-1.0.0` are now identical. `branch-1.0.0` *could* be safely deleted, but it could also make sense to rename it to something more meaningful and leave it for archival purposes. However, these two have exactly the same commits as can be seen by the lack of output [here](https://github.com/sourceryinstitute/opencoarrays/compare/branch-1.0.0...master?expand=1). I think my preference would actually be to remove the `branch-1.0.0` since all the history still exists, in master in the exact same form. (Same SHAs, same commit messages, same commit history and change sets)

What was formerly `master` has moved to `old-devel-FKA-master` (i.e. the old development branch, formerly known as master) The content (save for some whitespace fixes) is exactly the same as `old-devel-FKA-master` however the commit history is **not** the same; via `merge --squash` the changes required to transform the stable, `master` branch to `devel` were applied in a single merge commit, cab96acb2e54d053e2499b9111bebd1ad4dfb9a8. This was done to re-establish a more recent common history. I **DO** recommend we keep `old-devel-FKA-master` around for archival purposes, and to allow for inspection of commits which were unique to it, after this branch diverged from the old `branch-1.0.0`.

The [branches page](https://github.com/sourceryinstitute/opencoarrays/branches) gives a little bit of insight into how branches are related (commits ahead/behind master).

I'll try to make the call Tuesday, so that I can answer questions or explain the transformation that has taken place.

**Comment by zbeekman** [comment]
TO: @gustavj1976 @jeffhammond @milancurcic @mishatomsk @naveen-rn @ppenzin @raullaasner

I [noticed that you have you have cloned the sourceryinstitute opencoarrays repository](https://github.com/sourceryinstitute/opencoarrays/network/members) and just wanted to make you aware of some changes we've made on our end. We've moved to a [Github Flow](https://guides.github.com/introduction/flow/) workflow, which required some restructuring. See the conversation above for some more details. I recommend that you take the following actions if you have any active work on your personal fork:

 1. Locally backup a copy of your local repository (somewhere other than by pushing to github.com)
 2. Delete your fork on github.com, and then create a new one by visiting https://github.com/sourceryinstitute/opencoarrays and clicking on the [fork](https://github.com/sourceryinstitute/opencoarrays/issues/52#fork-destination-box) button.
 3. clone a fresh copy of your fork to a *new* location on your local computer (i.e. NOT where you backed up your local work)
 4. reapply any patches from your old local changes to the appropriate fork on the freshly cloned repository
 5. (optional) contribute bug fixes, and improvements back upstream [by submitting pull requests](https://github.com/sourceryinstitute/opencoarrays/pulls) or filing any issues if you find defects.

Thanks

**Comment by rouson** [comment]
Bravo!  Bravissimo!

**Comment by zbeekman** [comment]
> What was formerly master has moved to old-devel-FKA-master (i.e. the old development branch, formerly known as master) The content (save for some whitespace fixes) is exactly the same as old-devel-FKA-master however the commit history is not the same; via merge --squash the changes required to transform the stable, master branch to devel were applied in a single merge commit, cab96ac. This was done to re-establish a more recent common history. I DO recommend we keep old-devel-FKA-master around for archival purposes, and to allow for inspection of commits which were unique to it, after this branch diverged from the old branch-1.0.0.

I'm a little bit worried that I should have used `merge --squash --no-ff` not just `merge --squash` to help document the history/lineage of the "new" `devel` branch, and ensure a merge commit was entered. However, I don't think this will be an issue. I don't anticipate that we'll be needing to do too much  digging around in the past to determine which commit (between where old master and branch-1.0.0 diverged) *à la* `git blame`. If I could go back in time I would probably do it that way, but I don't think this is a large enough issue to warrant redoing the branch merge, update and rename.

**Comment by zbeekman** [comment]
Unless anyone objects, I am now closing this issue.
