### ISSUE TITLE
Defect: opencoarrays 2.0.0 fails to build with GCC 8 on macOS 10.13

### ISSUE THREAD

**Issue by fxcoudert** [sourceryinstitute/OpenCoarrays#527]
# Defect/Bug Report #

- OpenCoarrays Version: 2.0.0
- Fortran Compiler: GCC 8.0.1 (RC2)
- C compiler used for building lib: AppleClang 9.1.0.9020039
- Installation method: Homebrew, which is using cmake
- Output of `uname -a`: `Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64`
- MPI library being used: OpenMPI 3.0.1
- Machine architecture and number of physical cores: virtual box
- Version of CMake: 3.11.1

## Observed Behavior ##

Builds fail with gfortran internal compiler error:

```
08:14:51 /tmp/opencoarrays-20180501-23507-1ij1841/OpenCoarrays-2.0.0/src/tests/integration/dist_transpose/coarray_distributed_transpose.F90:57:0:
08:14:51 
08:14:51              do i = 2, num_nodes;    variable[i] = variable;      end do
08:14:51  
08:14:51 internal compiler error: in gfc_dep_resolver, at fortran/dependency.c:2258
```

Full output is there: https://gist.github.com/fxcoudert/dd8422987e4a71cbefb470c411a4e19d

## Expected Behavior ##

Build succeeds.

## Steps to Reproduce ##

`brew install -s opencoarrays`, which runs `cmake` then `make`, after GCC 8 is installed: https://github.com/Homebrew/homebrew-core/pull/27276

**Comment by vehre** [comment]
This issue is addressed by: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85507

**Comment by fxcoudert** [comment]
Any chance the patch makes it into GCC 8 before release? (I'm not sure how the regression sneaked in so late in the release process, but it seems kind of a blocker for gfortran)

**Comment by vehre** [comment]
Gfortran is not important enough to GCC to block a release. Gfortran rather is a side project and GCC will release even with a non-functional gfortran.

Anyway the patch needs to be reviewed before we can think about in which versions it will be present. The merge window for gcc-8 has been closed BTW.

**Comment by fxcoudert** [comment]
I only asked because I know Fortran fixes can be sneaked in late in the process, as did the patch that caused the bug (which was applied while GCC was in regression-fix only, although was not a regression fix).

Is there a workaround that opencoarrays can implement? As it is, we will be shipping with GCC 8 shortly in Homebrew, and opencoarrays will be broken. I do not wish that, but will not delay shipping GCC 8 for opencoarrays.

**Comment by rouson** [comment]
@vehre I'd like to approach Paul Thomas to ask if he would review it.  Is the following link the one that I should forward to Paul?  https://gcc.gnu.org/ml/fortran/2018-04/msg00120.html

**Comment by fxcoudert** [comment]
FYI: GCC 8.1 is now the default version in Homebrew, breaking opencoarrays.

**Comment by rouson** [comment]
@fxcoudert I'm going to investigate whether I can have the OpenCoarrays installer (`install.sh`) apply the patch.  I've done something similar in the past so hopefully it will work as a short-term measure for those who use the installer.

**Comment by zbeekman** [comment]
@fxcoudert ah, yes, because ABI incompatibilities between libgfortran etc. from 7 to 8 etc. I guess the only option is to come up with some sort of work around in OpenCoarrays... CC: @vehre

**Comment by zbeekman** [comment]
@fxcoudert: I've done some testing and it's not too hard to get OpenCoarrays to build using gcc@7 with OpenMPI built using GCC 8.1: The main library that interfaces with GFortran is written in C, and the C ABI should be the same between OpenMPI compiled by GCC 7.3 and 8.1. The downside is that mixed Coarray Fortran + MPI won't be supported, and the extensions module will have to be skipped. This means that we could potentially configure OpenCoarrays to build with gcc@7 and OpenMPI built with 8.1. However, I don't know if the homebrew build environment will allow a dependency on a package that depends on gcc (openmpi, which depends on gcc 8.1) and a dependency on gcc@7. Will look into other work arounds on the library side too...

**Comment by jbmaggard** [comment]
Continued success with native Win64 build of OpenCoarrays-2.0.0 using Win7-64/Intel-MPI/MSYS2/GCC 7.3.0  (using install.sh, with one change to FindMPI.cmake (3.11.1), and one change to OpenCoarrays-2.0.0/prerequisites/install-functions/build_opencoarrays.sh).

The mingw-w64 project [(mingw-w64.org)](mingw-w64.org) released their first [build](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/) of GCC 8.1.0 for Win64 on 2018/5/24.
```
$ gcc --version
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
```
I see the same internal compiler error discussed in the current issue.

```
[ 10%] Generating coarray_distributed_transpose
C:/msys2/home/maggard.admin/OpenCoarrays-2.0.0/src/tests/integration/dist_transpose/coarray_distributed_transpose.F90:57:0:

             do i = 2, num_nodes;    variable[i] = variable;      end do

internal compiler error: in gfc_dep_resolver, at fortran/dependency.c:2258
```
In the reference (just above) to this issue as posted to the msys2 project, I am hoping that the msys2 build of GCC8 that @Alexpux is currently developing will have working coarrays in gfortran.

I found the discussion of GCC versions, MPI versions, and patches that @zbeekman provided in [#735](https://github.com/sourceryinstitute/OpenCoarrays/issues/435#issuecomment-328354074) to be quite useful, and would appreciate an update on the discussion of implementation of events, failed images, and teams, now that MPICH 3.2.1/3.3b2, GCC 8.1, and OpenCoarrays-2.0.0 have all been released.
