### ISSUE TITLE
Question: Configuring install.sh to see prereqs

### ISSUE THREAD

**Issue by jordana309** [sourceryinstitute/OpenCoarrays#530]
# Question #
Question: Configuring install.sh to see prereqs

- OpenCoarrays Version: 2.0.0
- Fortran Compiler: GNU Fortran Ubuntu 5.5.0-12ubuntu1\~16.04 comes up with gfortran --version, but I do have GNU Fortran (Ubuntu 7.3.0-16ubuntu3\~16.04.1) installed.
- C compiler used for building lib: same deal. gcc (Ubuntu 5.5.0-12ubuntu1\~16.04) comes up when I type gcc -version, but I have gcc-7 (Ubuntu 7.3.0-16ubuntu3\~16.04.1) installed.
- Installation method: "bash install.sh"
- Output of `uname -a`: "Linux NukeBox 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
- MPI library being used: I don't think I got to using the MPI library. The install script isn't seeing what I have installed--I have MPICH 3.2.
- Machine architecture and number of physical cores: 64-bit, 4 cores, but it's a VM.
- Version of CMake: 3.5.1

## Observed Behavior ##
After downloading prerequisites that I have installed on my system, install.sh crashed out trying to compile gcc-7.3.0, it appears. The output is attached. I should note that I am new to playing with compilers, so my mistake is probably silly and easily corrected, but I need some help understanding what that is. How would I configure the install.sh script to see my installed prerequisites?

## Expected Behavior ##
Completing the install, and recognizing the preinstalled prerequisites. I do expect, however, to have to point the install script to my install of MPICH 3.2, but I'm not sure how.

## Steps to Reproduce ##
Type the following into your terminal:
```
sudo apt-get install aptitude
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo aptitude install gcc-7 g++-7 gfortran-7
cd ~/Codes/src
git clone https://github.com/sourceryinstitute/OpenCoarrays.git
cd OpenCoarrays
bash install.sh
```
After it gets to installing gcc-7, it will crash out like this.

OUTPUT after error is attaches (it was longer than expected).
[Compile Error.txt](https://github.com/sourceryinstitute/OpenCoarrays/files/1965915/Compile.Error.txt)

**Comment by rouson** [comment]
See example 3 in the [Example script invocations] in the [INSTALL.md] file.  In addition, I recommend adding the `--disable-bootstrap` or equivalently the `-z` argument to speed up the build process considerably (but try again without these arguments if the build fails.  Also, I recommend speeding things up further with a parallel build.  For example, on a system with 4 cores, use `--num-threads 4` or equivalently `-j 4`.  So please try something like the following:
```bash
./install.sh 
   --with-fortran <path-to-gcc-bin>/gfortran \
   --with-cxx <path-to-gcc-bin>/g++ \
   --with-c <path-to-gcc-bin>/gcc \
   --disable-bootstrap \
   --num-threads 4 \
   --install-prefix <path-to-desired-opencoarrays-location> 
```
where `<path-go-gcc-bin>\` may be ommitted if the desired gcc/g++/gfortran are at the front of your `$PATH`. 

[Example script invocations]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#installation-script
[INSTALL.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md

**Comment by zbeekman** [comment]
@jordana309 If you already have gcc-7, g++-7 and gfortran-7 installed at the front of your path then just specify them to `install.sh`

Confirm that GCC-7 compilers are on your path:

```
which gcc-7
which g++-7
which gfortran-7
```

Each command should print the location of the compiler.

Next, try:

```bash
./install.sh \
   --with-fortran "`which gfortran-7`"
   --with-cxx "`which g++-7`"
   --with-c "`which gcc-7`"
   -j 4
   --install-prefix "/path/to/install/OpenCoarrays/into"
```

If you have CMake and MPI installed too, you might just want to install directly with CMake.

**Comment by jordana309** [comment]
I got Fortran to install by running the following line (I had to manually put in all my paths, and specifically install mpich for some reason:
` bash install.sh --with-fortran "/usr/bin/gfortran-7" --with-cxx "/usr/bin/g++-7" --with-c "/usr/bin/gcc-7" --disable-bootstrap --num-threads 4 --package mpich --install-prefix "home/jordan/Codes/" `

Thank you for your help. Then, I installed the [Jupyter CAF kernel](https://github.com/sourceryinstitute/jupyter-CAF-kernel), and when I ran the kernel in jupyter, it connected fine. However, when trying to run a simple hello world program to make sure it works, I got the following error:

```
  File "/home/jordan/Codes/Anaconda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'caf': 'caf'
```

Is that likely a kernel problem, or a Coarrays Fortran problem? I'm not sure how to overcome it, because the actual kernelspec file looks fine from what I can tell.

Thank you!

**Comment by zbeekman** [comment]
hmmmm I'm not sure. Jupyter CAF kernel has been neglected for a few months. If you type `which caf` does it show you where you installed OpenCoarrays? If you set the `--install-prefix` to something that is not on your `PATH` by default you will have to make sure it gets added, probably somewhere in your "dot files". I'm not 100% sure how python & Jupyter handle the user's PATH in the context of Jupyter kernels.

**Comment by jordana309** [comment]
`which caf` returns nothing, and when I tried to add the <specific path> from my `--install-prefix`, it still can't find it. I tried doing the bin folder in that directory, but no dice. I tried to point to the caf kernel and several folders in there, but it didn't like any of them (and I did remember to close all my terminals and reopen them between tests). What is 'caf' supposed to be pointing to? MPICH? the CAF kernel?

**Comment by zbeekman** [comment]
Yes, there is a default of two coarray images. You can use some magic to control compilation and number of images. Let's close this issue and open one on Jupyter-CAF-kernel to continue discussion there.

**Comment by zbeekman** [comment]
See, e.g., https://github.com/sourceryinstitute/jupyter-CAF-kernel/blob/master/index.ipynb. This should load as a non-interactive example notebook. You can see in the first input cell two "magics" one to say how many images to use `%num_images: 1` and one to allow longer input lines: `%fc_flags: -ffree-line-length-none`. It looks like GH is having trouble rendering the entire document for me, so you can also look at it here: https://nbviewer.jupyter.org/github/sourceryinstitute/jupyter-CAF-kernel/blob/master/index.ipynb

**Comment by rouson** [comment]
Shall we close the issue?
