### ISSUE TITLE
Bug: allocating coarrays at the team level

### ISSUE THREAD

**Issue by MichaelSiehl** [sourceryinstitute/OpenCoarrays#533]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

- OpenCoarrays Version: `2.0.0`
- Fortran Compiler: `GNU Fortran (GCC) 9.0.0 20180506 (experimental)`
- C compiler used for building lib: `gcc (GCC) 9.0.0 20180506 (experimental)`
- Installation method: `install.sh`
- Output of `uname -a`: `Linux 3.13.0-147-generic #196-Ubuntu SMP Wed May 2 15:51:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- MPI library being used: `MPICH 3.2.1`
- Machine architecture and number of physical cores: `laptop computer, 4 cores`
- Version of CMake: `3.4.0`

## Observed Behavior ##
When trying to allocate an allocatable coarray on the images of a specific team only, that `allocate` statement does not only synchronize with the (same) `allocate` statement on the images of that team, but instead does (try to) synchronize with (any) `allocate` statement(s) on the images of any other team as well. This may prevent from independent code execution on the images of a specific team in the presence of an allocatable coarray. 
See the following code example: There are two `allocate` statements (the second one being out commented) in the code execution parts of the subteams. Each `allocate` statement does allocate another coarray in other teams each. With only the first `allocate` statement active in the code, program execution does hang (assuming that the `allocate` statement does try to synchronize with `allocate` statements outside that team, which do not exist). On the other side, with both `allocate` statements being active, runtime execution does complete successfully, even if the both `allocate` statements do allocate two distinct coarrays on the teams.
```fortran
program Main
! please compile and run with 15 coarray images
  !
  use,intrinsic :: ISO_FORTRAN_ENV, only: team_type
  implicit none
  !
  integer, codimension[:], save, allocatable :: intAllocatableCoarray1
  integer, codimension[:], save, allocatable :: intAllocatableCoarray2
  !
  integer :: intTeamNumber
  type (team_type) :: MainTeam
  type (team_type) :: SubTeam
  !
!
!************************************************
! MainTeam **************************************
!************************************************
!
! split the 15 images of the initial team into 3 child teams consisting of 5 images each:
  if (this_image() <= 5) then
    intTeamNumber = 1
  else if (this_image() >= 6 .and. this_image() <= 10) then
    intTeamNumber = 2
  else if (this_image() >= 11) then
    intTeamNumber = 3
  end if
  !
form team (intTeamNumber, MainTeam) ! this creates the 3 child teams in MainTeam
!
change team (MainTeam)
!
!************************************************
! SubTeam ***************************************
!************************************************
!
! split the 5 images of the MainTeam's child teams into two distinct teams resp.:
  if (this_image() < 3) then
    intTeamNumber = 1
  else
    intTeamNumber = 2
  end if
!
form team (intTeamNumber, SubTeam) ! this generates 6 teams (2 new sub teams in the 3 main teams resp.)
                                   ! within the change team (MainTeam) construct
change team (SubTeam)
!
SubTeam_select: select case (team_number())
!
case (1) SubTeam_select
  ! codes for child team 1 of SubTeam:
  allocate (intAllocatableCoarray1[*])
  !
  write(*,*) 'image number: ', this_image(), ' of team number: ', team_number(), &
             ' in SubTeam, of MainTeam''s child team number:'
  !
!*******************
case (2) SubTeam_select
  ! codes for child team 2 of SubTeam:
!  allocate (intAllocatableCoarray2[*]) ! without this allocate statement runtime execution will hang
  !
  write(*,*) 'image number: ', this_image(), ' of team number: ', team_number(), &
             ' in SubTeam, of MainTeam''s child team number:'
!
end select SubTeam_select
!
end team !(SubTeam)
!
!*************
!*************
!*************
!
end team !(MainTeam)
!
end program Main
```

## Expected Behavior ##
Program execution should not hang when allocating a coarray on a specific team only.

**Comment by MichaelSiehl** [comment]
Let me further comment on this to give some idea about the importance of correct working of the ALLOCATE statement at the team level:

The desired runtime behavior of the ALLOCATE statement with a coarray object at the team level is described in the standards text, chapter 9.7.1.2, paragraph 4: “...execution...is delayed until all other images in the current team have executed the same statement the same number of times in this team.”

And here is what the standard can't possibly say explicitly about the already very desirable real-world runtime behavior of the ALLOCATE statement in conjunction with remote atomics (through atomic subroutines) using the current implementations (ifort and gfortran):

Remote data transfer through atomic subroutines can be very irritable: Especially after a failure we can observe severe side effects that do corrupt the remote data transfer channels through atomic subroutines among the involved coarray images, so that no further remote data transfer will succeed. Nevertheless, we can use atomic subroutines (and SYNC MEMORY) to develop (with low effort) quite sophisticated (customized or user-defined) synchronization procedures that are able to detect such faulty remote data transfer channels between coarray images (using a timer). 

Recovering from such is the goal and is exactly where the ALLOCATE statement comes into play: I did (more or less) extensive testing the ALLOCATE statement with corrupted remote data transfer channels using the current implementations (ifort 18/19beta, and recent gfortran/OpenCoarrays/MPICH -they have virtually the same runtime behavior on my computer-). 

From my current testing I would say that the ALLOCATE statement is the one synchronization method that does allow to recover safely from corrupted data transfer channels through atomic subroutines. In this context, the ALLOCATE statement is not just for memory management but rather for restoring of (corrupted) remote data transfer channels by reallocating them after a failure.

I could imagine that correct implementation of ALLOCATE at the team level means a major effort for the implementer but hopefully did give an idea about it's importance as well.

Cheers

PS: I will soon upload a working example program that demonstrates such recovery through ALLOCATE to a new GitHub repository as well.

**Comment by zbeekman** [comment]
Hi Michael, I just wanted to let you know that I have seen this issue, but cannot attend to it for a few days. Please remind me later next week if you haven't heard from anyone by then.

Thanks!

**Comment by MichaelSiehl** [comment]
Hi Zaak,
thanks for the note, and I will do so. That issue is on top of my list. (To
me, any other issue is currently secondary). I will even continue trying to
convince others about it's importance.
cheers

2018-05-17 3:14 GMT+02:00 zbeekman <notifications@github.com>:

**Comment by MichaelSiehl** [comment]
Hi Zaak,
sorry for being somewhat delayed with my reminder to that issue.
As I've already told, it's an important issue for me and surely for others as well. I could imagine that the implementation of ALLOCATE / DEALLOCATE at the team level will be a major effort for the developer(s). Is there anything I could possibly do to help with this? Please let me know if any help is needed. (I can't make promises yet but would surely try to help if I only can).
Best Regards
Michael

**Comment by scrasmussen** [comment]
Hi @MichaelSiehl,
I was one of the people that originally helped with teams and will be able to look into this issue next week. I'll be able to report on the amount of time/effort that I expect it will take to fix this issue. I can see its an important issue for you, thanks for your patience and reporting the issue.
Cheers, Soren

**Comment by MichaelSiehl** [comment]
Hi Soren,
great! Thanks for that info.

Just some further background information:

I've got the plan to develop a coarray-based framework (as Open Source) for
general purpose parallel programming myself. I started with F08 but have
reached (and exceeded) the limits of Fortran 2008 coarrays (using it for
MPMD-style programming).

With current OpenCoarrays (I'm still using 2.0.0), and it's impressive
support for Fortran 2018 coarray teams, opportunities have already improved
greatly.

My current status: Due to a customized synchronization procedure, I can
easily detect (and avoid) many kinds of parallel runtime failures, ranging
from data races to hardware failures (by using a timer as well as an
'enumerated synchronization technique' within the customized
synchronization procedures; it requires also a certain programming
technique for the development of parallel algorithms). I can also produce
corrupted atomic data transfer channels between coarray images, to use
these for testing purposes.

(Just from my testing, the atomic data transfer channels themselves do not
seem to be corrupted but the timing between them. As a result, no further
data transfer between coarray images through the corrupted atomic (derived
type) coarray (component) may occur).

From my current testing, using ifort 18 and 19 beta (these do not support
F18 teams), as well as gfortran/OpenCoarrays, the ALLOCATE statement is the
one synchronization method that allows to safely recover from such
corrupted atomic data transfer channels (coarrays). That is what could make
ALLOCATE at the team level a really powerful feature.

(Another working option, that we can use meanwhile, is to switch to another
(derived type) atomic coarray (component) after such runtime failures with
corrupted atomic data transfer channels. On the other hand, a CHANGE TEAM
or END TEAM is not a cure for it. But also, and fortunately, there were no
side effects between coarray images in distinct teams at the same team
level, even not if they did execute on the same processor core -as far as I
can assume yet-.)

Cheers, Michael

https://github.com/MichaelSiehl?tab=repositories


2018-06-29 0:00 GMT+02:00 Soren Rasmussen <notifications@github.com>:

**Comment by nathanweeks** [comment]
The deadlock occurs only when failed image support is enabled. Failed images have been disabled by default since OpenCoarrays 2.4.0.

The reason is that the gfortran front end emits a call to _gfortran_caf_sync_all() as part of the coarray allocation process. In OpenCoarrays, this routine includes the following barrier:

```
#ifdef WITH_FAILED_IMAGES
    ierr = MPI_Barrier(alive_comm); chk_err(ierr);
#else
    ierr = MPI_Barrier(CAF_COMM_WORLD); chk_err(ierr);
#endif
```

"alive_comm" is effectively MPI_COMM_WORLD, whereas CAF_COMM_WORLD is the communicator for the current team of images... so if failed images support is enabled, and a coarray allocation occurs in only a subset of sibling teams, then those teams will deadlock.

I'm working on enhancing failed images in OpenCoarrays to support a larger subset of the Fortran 2018 standard; that work will include a fix for this issue as well.

**Comment by MichaelSiehl** [comment]
@nathanweeks Thanks very much for this information. I will check this soon using OC 2.4.0. (My current installation does still use OC 2.3.1.)

**Comment by MichaelSiehl** [comment]
@nathanweeks It really works, great! I can confirm that OpenCoarrays 2.4.0 (with default usage) does allocate coarrays at the team level independently from any allocation on another team (no deadlock occurs). I think we can close this issue now. 
Thanks very much. Great job!

**Comment by rouson** [comment]
@nathanweeks and @MichaelSiehl Thanks for resolving this!
