### ISSUE TITLE
Defect: new armflang exploratory code generates MPI "invalid communicator" error

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#567]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

The armflang branch now contains a very short demonstration program to emulate the invocation of `co_sum` in the file `src/extensions/co_sum-transformed.F90` along with a stripped-down version of the `opencoarrays` module supporting our new collaboration with Arm engineer and WG5 member Nathan Sircombe.  This represents a first attempt to use OpenCoarrays with the `armflang` compiler installed at the University of Oregon.  A detailed transcript of the results are below.  The relevant files are
* `src/extensions/Makefile`, which successfully compiles and links the file below,
* `src/extensions/co_sum-transformed.F90`,
* `src/extensions/opencoarrays.F90`, which is a stripped-down version of our like-named file,
* `src/mpi/caf_mpi.c,
all of which get compiled via `mpifort` and `mpicc` wrapping `arfmlang` to produce an executable program named `co_sum-transformed`.

Guidance from @afanfa or @scrasmussen about recommended next steps would be greatly appreciated.

## Steps to Reproduce ##
```bash
$ ssh nic.uoregon.edu
$ ssh cerberus
$ srun -p jetson --pty /bin/bash
$ export ARM_HPC_COMPILER_LICENSE_SEARCH_PATH=/packages/arm
$ module use /packages/arm/opt/arm/modulefiles
$ module load Generic-AArch64/Ubuntu/16.04/suites/arm-compiler-for-hpc_eval/18.2
$ module load openmpi/3.0.2_arm-18.2
$ git clone -b armflang https://github.com/sourceryinstitute/opencoarrays
$ cd opencoarrays/src/extensions
$ cat co_sum-transformed.F90
```
```fortran
program main
  use iso_fortran_env, only : error_unit
  use iso_c_binding, only : c_int,c_double,c_loc,c_char
  use opencoarrays
  implicit none

  integer(c_int) :: i,me(1),argc=0
  character(kind=c_char) :: argv(1)
 
  call caf_init(c_loc(argc),c_loc(argv))

  ! Verify collective sum of integer data by tallying image numbers
  me=this_image()
  call co_sum(me)
  if ( any(me/=sum([(i,i=1,num_images())])) ) call error_stop
   
  ! Wait for every image to pass
  call sync_all
  if (this_image()==1) print *, "Test passed."

  call caf_finalize()
end program
```
```
$ make
$ mpirun -n 1 ./co_sum-transformed
[jetson01:4279] *** An error occurred in MPI_Comm_rank
[jetson01:4279] *** reported by process [74252289,545460846592]
[jetson01:4279] *** on communicator MPI_COMM_WORLD
[jetson01:4279] *** MPI_ERR_COMM: invalid communicator
[jetson01:4279] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[jetson01:4279] ***    and potentially your MPI job)
[warn] Epoll MOD(1) on fd 25 failed.  Old events were 6; read change was 0 (none); write change was 2 (del): Bad file descriptor
[warn] Epoll MOD(4) on fd 25 failed.  Old events were 6; read change was 2 (del); write change was 0 (none): Bad file descriptor
```

**Comment by rouson** [comment]
This has been fixed on the armflang branch.

**Comment by zbeekman** [comment]
@rouson should we disable CI for this branch? Or try to install flang/f18 instead of GFortran?

**Comment by rouson** [comment]
@zbeekman Yes, please feel free to disable CI for the armflang branch.  Installing flang is a bear of a process that I have yet to install.  AFAIK, the only option for installing flang via package management is the package manager [spack](https://github.com/spack/spack), but that appears to be broken and NVIDIA confirmed that space support for building flang is problematic.  Building it from source is probably not an option given the Travis-CI 1-hr limit and doing so is also not trivial.  

Also, the only thing that currently works with armflang is a "Hello, world!" example that uses only `this_image()`, `num_images()`, `error stop`, and `sync all`.  Nothing that involves communication works yet -- not even collective subroutines.
