### ISSUE TITLE
Question: Does a gfortran ABI change necessitate an SO_VERSION update?

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#572]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Question #

If yes, this can issue can be kept open to remind us to watch for a possible upcoming gfortran ABI change depending on the outcome of today's gfortran mailing list [discussion thread](https://gcc.gnu.org/ml/fortran/2018-07/msg00137.html).

If no, then this issue can be closed.

**Comment by zbeekman** [comment]
Yes, we should bump the SO_VERSION every time GFortran does. I don't think a persistent open issue does much to remind us of anything, my gut says close this so it doesn't look like we have a huge backlog... well at least not any larger than it actually is....
