### ISSUE TITLE
Defect: caf script does not use shared object (dynamic) library files

### ISSUE THREAD

**Issue by uihsnv** [sourceryinstitute/OpenCoarrays#579]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

- OpenCoarrays Version: 2.2.0
- Fortran Compiler: gfortran version 8.2.0
- C compiler used for building lib: gcc version 8.2.0
- Installation method: cmake, make & make install
- Output of `uname -a`: Linux 4.17.14
- MPI library being used: MPICH 3.2.1
- Machine architecture and number of physical cores: x86_64, 4-cores & 8-threads
- Version of CMake: 3.11.4

## Observed Behavior ##

```
$ caf program.f90
gfortran: error: /usr/lib/libcaf_mpi.a: No such file or directory
    Error: comand:
       `/usr/bin/gfortran -I/usr/include/OpenCoarrays-2.2.0_GNU-8.2.0 -fcoarray=lib -Wl,-rpath -Wl,/opt/mpich/lib -Wl,--enable-new-dtags program.f90 /usr/lib/libcaf_mpi.a /opt/mpich/lib/libmpifort.so /opt/mpich/lib/libmpi.so`
    failed to compile.
```

## Expected Behavior ##

Since the cmake method of install generates `/usr/lib/libcaf_mpi.so`, the `caf` script should be modifed (if possible) during install to point to it instead of the static library file.

## Steps to Reproduce ##

Install using, or as described in the AUR build script:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opencoarrays

Also, the discussion on the mailing-list:
https://groups.google.com/d/msg/opencoarrays/uRlWSby8dY8/7xde_Cl8CgAJ

**Comment by uihsnv** [comment]
Oh shoot! @zbeekman  Looks like you already had one opened: https://github.com/sourceryinstitute/OpenCoarrays/issues/575

**Comment by zbeekman** [comment]
Ah, cool. Well this added context is good (the error message) and it will be linked from #575 now that we've mentioned it. Thanks!
