### ISSUE TITLE
setup.csh has errors

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#584]
- OpenCoarrays Version: <2.2.0>
- Fortran Compiler: <gcc 7.3.0>
- C compiler used for building lib: <gcc 7.3.0>
- Installation method: <install.sh>
- Output of `uname -a`: Linux hze.larc.nasa.gov 2.6.32-431.11.2.el6.x86_64 #1 SMP Tue Mar 25 19:59:55 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
- MPI library being used: <MPICH 3.2>
- Machine architecture and number of physical cores: Not relevant
- Version of CMake: <3.4.0>

Please create the setup.csh file in prerequisites/installations to

set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/cmake/3.4.0/bin" $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/gcc/7.3.0"/bin $path)
set LD_LIBRARY_PATH = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/gcc/7.3.0/lib64/:/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/gcc/7.3.0/lib/:" ${LD_LIBRARY_PATH}) 
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/mpich/3.2"/bin $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/flex/2.6.0"/bin $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/bison/3.0.4"/bin $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations/m4/1.4.17"/bin $path)
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.2.0/prerequisites/installations"/bin $path)

**Comment by rouson** [comment]
@singleterry It appears the the suggested edit removes the double quotes around the second argument on each `set` command.  Is that correct?  Am I missing another change?  I'm a little concerned that this could cause problems if $path contains any white space.  What was the problem you observed with the previous version of `setup.csh`?

**Comment by singleterry** [comment]
Hello,

The double quotes is supposed to include spaces in the apth/name….  My understanding anyway.

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by zbeekman** [comment]
> The double quotes is supposed to include spaces in the apth/name…. My understanding anyway.

I think @rouson meant that `$path` should probably be quoted since it may have spaces, however, I am not that familiar with csh.

**Comment by singleterry** [comment]
Hello,

Yes, it should!!

Thanks!!

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by singleterry** [comment]
Hello,

Absolutely DO NOT put double quotes around the $path.  It breaks everything.  It must already be taken care of!

Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************
