### ISSUE TITLE
Defect: Deprecated MPI_Type_extent function used

### ISSUE THREAD

**Issue by jabl** [sourceryinstitute/OpenCoarrays#586]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

# Defect/Bug Report #

- OpenCoarrays Version: 2.2.0-1-g6203ab9
- Fortran Compiler: GCC 9.0.0 20180924
- C compiler used for building lib: Same as above
- Installation method: cmake from git checkout
- Output of `uname -a`: Linux dt 4.15.0-32-generic #35-Ubuntu SMP Fri Aug 10 17:58:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux                                                                                                              

- MPI library being used: OpenMPI 2.1.1-8 (from Ubuntu package)
- Machine architecture and number of physical cores: x86_64, 4 cores
- Version of CMake: 3.10.2-1ubuntu2

## Observed Behavior ##

<pre><code>
[  2%] Building C object src/mpi/CMakeFiles/caf_mpi.dir/mpi_caf.c.o                                                                                                                                                
/home/janne/src/gfortran/OpenCoarrays/src/mpi/mpi_caf.c: In function ‘redux_char_by_reference_adapter’:                                                                                                            
/home/janne/src/gfortran/OpenCoarrays/src/mpi/mpi_caf.c:6993:3: warning: ‘MPI_Type_extent’ is deprecated: MPI_Type_extent is superseded by MPI_Type_get_extent in MPI-2.0 [-Wdeprecated-declarations]              
   MPI_Type_extent(*datatype, &string_len);                                                                                                                                                                        
   ^~~~~~~~~~~~~~~                                                                                                                                                                                                 
In file included from /home/janne/src/gfortran/OpenCoarrays/src/mpi/mpi_caf.c:46:0:                                                                                                                                
/usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h:1776:20: note: declared here                                                                                                                                       
 OMPI_DECLSPEC  int MPI_Type_extent(MPI_Datatype type, MPI_Aint *extent)                                                                                                                                           
                    ^~~~~~~~~~~~~~~                                                                                                                                                                                
[  3%] Building C object src/mpi/CMakeFiles/caf_mpi.dir/__/common/caf_auxiliary.c.o                                                                                                                                
[  4%] Linking Fortran shared library ../../lib/libcaf_mpi.so                                                                                                                                                      
Creating symlink include/opencoarrays.mod --> include/OpenCoarrays-2.2.0-1-g6203ab9_GNU-9.0.0/opencoarrays.mod                                                                                                     
[  4%] Built target caf_mpi                                                                                                                                                                                        
[  5%] Building C object src/mpi/CMakeFiles/caf_mpi_static.dir/mpi_caf.c.o                                                                                                                                         
/home/janne/src/gfortran/OpenCoarrays/src/mpi/mpi_caf.c: In function ‘redux_char_by_reference_adapter’:                                                                                                            
/home/janne/src/gfortran/OpenCoarrays/src/mpi/mpi_caf.c:6993:3: warning: ‘MPI_Type_extent’ is deprecated: MPI_Type_extent is superseded by MPI_Type_get_extent in MPI-2.0 [-Wdeprecated-declarations]              
   MPI_Type_extent(*datatype, &string_len);                                                                                                                                                                        
   ^~~~~~~~~~~~~~~                                                                                                                                                                                                 
In file included from /home/janne/src/gfortran/OpenCoarrays/src/mpi/mpi_caf.c:46:0:                                                                                                                                
/usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h:1776:20: note: declared here                                                                                                                                       
 OMPI_DECLSPEC  int MPI_Type_extent(MPI_Datatype type, MPI_Aint *extent)                                                                                                                                           
                    ^~~~~~~~~~~~~~~                                                                                                                                                                                
</code></pre>

## Expected Behavior ##

Compiles without warnings

## Steps to Reproduce ##

Should happen when trying to build against a recent-ish openmpi.

**Comment by opoplawski** [comment]
With the release of openmpi 4.0, support for MPI1 has been dropped, so this now results in a build failure:
```
cd /builddir/build/BUILD/OpenCoarrays-2.3.1/openmpi/src/tests/integration/dist_transpose && ../../../../bin/caf -I /usr/include/openmpi-x86_64 -I /usr/lib64/openmpi/lib -DPREFIX_NAME=_gfortran_caf_ -DGCC_GE_7 -DGCC_GE_8 -DHAVE_MPI -DMPI_WORKING_MODULE -DNDEBUG -o /builddir/build/BUILD/OpenCoarrays-2.3.1/openmpi/bin/OpenCoarrays-2.3.1-tests/coarray_distributed_transpose /builddir/build/BUILD/OpenCoarrays-2.3.1/src/tests/integration/dist_transpose/coarray_distributed_transpose.F90
BUILDSTDERR: /usr/bin/ld: /builddir/build/BUILD/OpenCoarrays-2.3.1/openmpi/lib64/libcaf_mpi.a(mpi_caf.c.o): in function `redux_char_by_reference_adapter':
BUILDSTDERR: /builddir/build/BUILD/OpenCoarrays-2.3.1/src/mpi/mpi_caf.c:6993: undefined reference to `MPI_Type_extent'
BUILDSTDERR: collect2: error: ld returned 1 exit status
```
