### ISSUE TITLE
VirtualBox version has a suspected compiler issue (or we are Fortran idiots which is of equal probability)

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#596]
[CAF_test.zip](https://github.com/sourceryinstitute/OpenCoarrays/files/2480749/CAF_test.zip)

Version: C:\Users\<users>\VirtualBox VMs\Sourcery Institute Virtual Machine (20180503)

We are trying to read data from files and place it into a user defined type (then will use co_broadcast to send it to all images although the error seems to occur long before we get to the co_broadcast part of the code).  We are either doing it wrong or there is a bug.  In the example, we are successful with regular real/character/integer so we appear to know what we are doing (even with the co_broadcast).  When it comes the the user defined type data, it seems to fail using the unlimited polymorphic data type with select type and not in a good way!

We have included two codes: hzetrn_trn and hzetrn_trn_NW

The only difference is in the Read_Write_Target_Material_Mod.f90 module (there is an '_NW' version to go with hzetrn_trn_NW) where data print statements are either commented in or out.  If commented in, the code seems to work fine.  With them commented out, the code fails.  To demonstrate this, in the included code/scripts/data, get a tcsh and % source go.csh.  It will compile and execute the working and non-working versions.  The differences are clear.

The Read_Write_*.f90 files handle the interface to the main code to mimic the Fortran 95 way of doing things so that regular Fortran programmers can understand the code and we can minimize the trauma to the Fortran 77 code in the physics routines (especially helpful when we get to the full CAF version).  The Type_*.f90 code does the read/write for each data type needed by the process.

This code worked in the "past".  We used the Intel 2016 compiler to run this code minus the co_broadcast since it did not exist.  We have a NASA-TP on this (NASA-TP_2018-219811, Singleterry with detailed source code) where it seem to work fine.  We have tried it with Intel 2018.3.222 and it worked fine.  Now modifying to use co_broadcast and it seems basic issues in Fortran are creeping in!  Since the Intel compiler does not support co_broadcast yet, so we cannot directly compare to it.  We compare to the Intel compiler by taking out the co_broadcasts and it works as planned....

We hope this is enough information.  If not, please let us know and we will do our best to elaborate!!

Thanks
Robert Singleterry
Eric Reaves

**Comment by rouson** [comment]
@singleterry 

Please reduce the code to a short example that reproduces the problem.  Doing so often identifies a bug in the code if there is one or a workaround if there is no bug in the code.  Also, a short reproducer shines a laser pointer on the problem if the bug is in the compiler or in OpenCoarrays.

It's also helpful to frame the reproducer as a test with conditional output that makes it clear what is expected:
```fortran
if ( actual_result == expected_result ) error stop "Test failed."
print *,"Test passed."
```
My personal goal with bug reproducers is to reduce them 25 lines or fewer.

If you have access to the Cray compiler, that's another option for testing testing collective subroutines.  If you don't have access to a Cray, then I'll be glad to test the code with the Cray compiler once it has conditional output to make clear what constitutes failure.

**Comment by rouson** [comment]
In my previous comment, I corrected the above snippet so to change the equality to an inequality.

**Comment by rouson** [comment]
Also, a newer virtual machine was uploaded last week so you might try that.

**Comment by singleterry** [comment]
Hello,

Unfortunately, I hate to say this, this is a reduction of the code to show the problem.  I will make a second pass to take out the stuff that work; however, what I fear is that the reduction in code will actually then mask the problem.

As far as pass/no pass code, since it is extra and extraneous code that gets executed, it is hard to have a single code that shows the problem.  Why I have two codes.

I will work on it today and update the issue later today.

Thanks
Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by singleterry** [comment]
Hello,

We will try that first!!!

Thanks
Robert

*******************************************************************************
Robert C. Singleterry Jr., Ph.D.
Research Engineer and NASA Administrator’s Fellow (Cohort 6: 2002-2004)
Durability, Damage Tolerance, & Reliability Branch
Langley Research Center, National Aeronautics and Space Administration
Building 1205, Room 285, Mail Stop 188E
2 West Reid Street
Hampton, VA 23681-2199
Work Voice: (757) 864-1437  FAX: (757) 864-4385   Personal Cell: (757) 371-4848
*******************************************************************************

**Comment by singleterry** [comment]
Latest version of virtualbox machine fixed the issue!!!
