### ISSUE TITLE
Defect: version number not updated for 2.3.0 release

### ISSUE THREAD

**Issue by LaHaine** [sourceryinstitute/OpenCoarrays#598]
[issue stat img]: https://img.shields.io/issuestats/i/github/sourceryinstitute/OpenCoarrays.svg?style=flat-square

| Avg response time              |
|:------------------------------:|
| ![Issue Stats][issue stat img] |

Please make sure to put any logs, terminal output, or code in
[fenced code blocks]. Please also read the [contributing guidelines]
before submitting a new issue.

# Defect/Bug Report #

- OpenCoarrays Version: 2.3.0
- Fortran Compiler: gcc 7.3.0
- C compiler used for building lib: gcc 4.8.5
- Installation method: install.sh
- Output of `uname -a`: 
- MPI library being used: openmpi 3.1.0
- Machine architecture and number of physical cores:
- Version of CMake: 

## Observed Behavior ##
.VERSION contains 2.2.0 and caf reports version 2.2.0
## Expected Behavior ##
it should report version 2.3.0 in release 2.3.0
## Steps to Reproduce ##
build opencoarrays 2.3.0 and run caf --version

**Comment by zbeekman** [comment]
I'm guessing @rouson may not have tagged on the command line and pushed the tag up... I'll investigate

**Comment by zbeekman** [comment]
Yeah, looks like it was tagged through the GH interface, and the .VERSION file wasn't updated. I'll yank the release and release a 2.3.1 version

**Comment by jbmaggard** [comment]
@zbeekman 
The web page at https://github.com/sourceryinstitute/OpenCoarrays/releases/tag/2.3.1 says "2.2.1"

**Comment by zbeekman** [comment]
@jbmaggard Thanks, good catch. I fixed the title.

@LaHaine I'm closing this issue now; we have yanked the 2.3.0 release and issued a 2.3.1 release.
