### ISSUE TITLE
src/mpi/CMakeLists.txt bug RE COMPILER_SUPPORTS_CAF_INTRINSICS

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#60]
>@zbeekman, the COMPILER_SUPPORTS_CAF_INTRINSICS gets defined in src/mpi/CMakeLists.txt when the compiler is gfortran and the version is less than 5. Not setting the aforementioned variable should produce a linking error some I'm a little perplexed as to why this wasn't discovered sooner.

>My first thought is that it relates some somehow to the fact gfortran had a co_reduce bug before version 5.3. Because that compiler bug generated test failures, we would have ignored any test failures for gfortran 5.1.0 or 5.2.0, but that doesn't explain why no linking error showed up when building with versions 5.2.0 or 6.0.0, which are both versions that I test prior to release.

>An enigma wrapped in a conundrum...

Moved from #52 

I think the source of this is the `NOT` clause in the `if` statement...

**Comment by rouson** [comment]
The NOT is confusing, but it's correct.  I posted the answer to this on a separate thread. I'm responding by phone and won't be able to find the link to the other thread easily. Bottom line: master is correct and the incorrect version on branch-1.0.0 will cause a linking error in the somewhat unlikely scenario when a user is compiling worth gfortran version >= 5 but still as a "use opencorrays" statement in a scope that contains co_reduce and therefore calls co_reduce through the API even though the gfortran >=5 is able to call co_reduce directly through the ABI.

**Comment by zbeekman** [comment]
As per our phone discussion I'll double check the CMakeLists.txt, but I have already addressed the bug you were referring to.

**Comment by zbeekman** [comment]
OK, I think I have convinced myself that everything is kosher here. See https://gitter.im/sourceryinstitute?at=5675c3b2091b6f9e0439dc14 for my reasoning. Closing this issue.
