### ISSUE TITLE
Query:  Assertion Failure with Intel MPI 2019 (Linux) with -DUSE_FAILED_IMAGES

### ISSUE THREAD

**Issue by jbmaggard** [sourceryinstitute/OpenCoarrays#601]
# Info #

- OpenCoarrays Version: 2.2.0
- Fortran Compiler: gfortran 8.2.1
- C compiler used for building lib: gcc 8.2.1
- Installation method: install.sh
- Output of `uname -a`: Fedora 28 (updated)
- MPI library being used: Intel MPI 2019 (Initial Release)
- Machine architecture and number of physical cores: 4-cores
- Version of CMake: 3.11.2

# Question #

I know that Linux/mpich are the supported case, so feel free to ignore...

Anyhow, I'm still working toward improving the current native Win64 CAF implementation using MSYS2/Intel MPI/OpenCoarrays/GCC.

Summary:  install.sh finds requirements for -DUSE_FAILED_IMAGES, however, trying to cafrun a produced caf executable gives:
Linux:
Assertion failed in file ../../src/mpid/ch4/src/ch4_comm.h at line 89: 0
Win64:
Assertion failed in file c:\iusers\jenkins\workspace\ch4-build-windows\impi-ch4-build-windows-builder\\src\mpid\ch4\src\ch4_comm.h at line 89: 0

If I comment out the part of src/mpi/CMakeFiles.txt that defines USE_FAILED IMAGES and run install.sh again, then 44 of the first 51 ctest cases pass (Linux).

[mpich ch4_comm.h](https://github.com/pmodels/mpich/blob/v3.3b2/src/mpid/ch4/src/ch4_comm.h)
```
MPL_STATIC_INLINE_PREFIX int MPID_Comm_revoke(MPIR_Comm * comm_ptr, int is_remote)
{
    MPIR_FUNC_VERBOSE_STATE_DECL(MPID_STATE_MPID_COMM_REVOKE);
    MPIR_FUNC_VERBOSE_ENTER(MPID_STATE_MPID_COMM_REVOKE);

    MPIR_Assert(0);

    MPIR_FUNC_VERBOSE_EXIT(MPID_STATE_MPID_COMM_REVOKE);
    return 0;
}
```

Details are at:
[https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/798715](https://software.intel.com/en-us/forums/intel-clusters-and-hpc-technology/topic/798715)

I'd appreciate any comment explaining what the assertion does, how it works, etc. and also any comment about how the #ifdef's in mpi_caf.c might be interacting to produce this assertion failure with -DUSE_FAILED_IMAGES.

**Comment by zbeekman** [comment]
Another user encountered issues with failed images being detected but failing at runtime. In their case, the MPI implementation provided the functions/API, but simply writes out a not-implmented-yet message. We need to do better introspection for this feature. Ideally by compiling and running a small hello-world example.

I don't have time now to look through the details, but an assertion within MPI itself sounds like a possible MPI bug or partial/not implemented feature. If Intel works on their MPI implementation in the same way they work on their fortran compiler, I wouldn't be surprised to see officially supported new features having bugs for a while after being "supported".

**Comment by jbmaggard** [comment]
@zbeekman Thank you for your feedback.  Feel free to close in a day or two if no further discussion ensues.  Your comment sounds quite reasonable to me.

My query made it through the moderator on the Intel HPC forum, so perhaps I'll get receive additional feedback there.

**Comment by zbeekman** [comment]
@jbmaggard 	I've posted a comment on the Intel forum post that you linked. Since MPI-4 did not ratify any proposed ULFM API, and it is being re-written at a lower level, we are disabling Failed image support by default in the next release of OpenCoarrays. The user can still explicitly ask for it with `-DCAF_ENABLE_FAILED_IMAGES:BOOL=ON` but even when probing MPI determines that support exists, we will not be turning it on. Because of this, I'm going to close this issue. Please feel free to reopen if you believe that it has not been adequately addressed.
