### ISSUE TITLE
Relocatable Installation

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#605]
Feature Request for Installation:

After installation, OpenCoarrays 2.2.0 was not relocatable.  Direct links to build directory structures are in the system somewhere.  

Thanks!

**Comment by zbeekman** [comment]
Thanks for the feature request, @singleterry! We are aware of this deficiency and are working to resolve the problem. I'm hoping this will be in the next minor version number bumping release. :crossed_fingers:

**Comment by zbeekman** [comment]
@singleterry: The latest release of OpenCoarrays (2.6.1) should be relocatable, and reproducible (assuming you set your environment appropriately). Please let me know if that solves your issues.

**Comment by singleterry** [comment]
Hello,



Major issue in setup.csh:
set path ("/users0/rsinglet/CAF/OpenCoarrays-2.6.1/prerequisites/installations/gnu/8.3.0"/bin $path)
needs to be
set path = ("/users0/rsinglet/CAF/OpenCoarrays-2.6.1/prerequisites/installations/gnu/8.3.0"/bin $path)



I am still checking for relocatablity besides the setup files.



Thanks
Robert

****************************************************
Robert C. Singleterry Jr., PhD
NASA Administrator's Fellow (2002-2004, Cohort 6)
Durability, Damage Tolerance, & Reliability Branch
Research Directorate
NASA Langley Research Center
MS 188E
2 West Reid Street
Bldg. 1205  Rm. 285
Hampton, VA 23681
757 864 1437 (Office)
757 864 8094 (FAX)
robert.c.singleterry@nasa.gov
757 371 4848 (Personal Cell)
**************************************************

**Comment by zbeekman** [comment]
I have fixed the csh issue on the `gfortran-non-determinism-repeat` branch which includes a bug fix for a GFortran bug in which `repeat()` is broken, and if you are able to use it, it embeds a path to the source directory in the object file even when you request it not to.

**Comment by singleterry** [comment]
Hello,

I manually put the ‘=’ in the setup.csh file and it worked fine.

I installed 2.6.1 under my directory structure (edited the setup.csh file as noted above) and had my SA copy my installation directory to /usr/local and it appears to work with no issues!!!!

Thanks for the modifications.

I am not sure what the repeat() fix you did is fixing, but I’ll believe you.

To get the latest 2.6.(2?) with these fixes in it, what do I do!?!

Thanks
Robert

****************************************************
Robert C. Singleterry Jr., PhD
NASA Administrator's Fellow (2002-2004, Cohort 6)
Durability, Damage Tolerance, & Reliability Branch
Research Directorate
NASA Langley Research Center
MS 188E
2 West Reid Street
Bldg. 1205  Rm. 285
Hampton, VA 23681
757 864 1437 (Office)
757 864 8094 (FAX)
robert.c.singleterry@nasa.gov
757 371 4848 (Personal Cell)
**************************************************

**Comment by zbeekman** [comment]
Hi Robert,

You can install from the source tarball provided by github, now that I have merged the fix into master, or you can clone and install from source, or you can wait for the next release.

FYI, the relocatability focuses on the libraries, and less so on the environment setup and compiler wrapper scripts, so YMMV with those. I'm planning to overhaul the wrapper scripts when I get the chance, so there should be additional improvements to those that will better support relocatability and address any lingering issues in the future.

I'll close this issue once we mint a new release.
