### ISSUE TITLE
ICE with certain flags and distributed transpose test

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/opencoarrays#63]
src/tests/integration/dist_transpose/coarray_distributed_transpose.F90 with `-fprofile-arcs -ftest-coverage`

I'm adding this here, just so that we can track it. I'm working on implementing #51 and find that adding the flags necessary for generating coverage data causes gfortran to ICE when compiling coarray_distributed_transpose.F90 I have yet to report this to the GCC maintainers.

If you're curious to see the current state of test coverage (I know you guys probably do more than just running `ctest` which is all that the Travis-CI build does right now) you can check it out here: https://codecov.io/github/zbeekman/opencoarrays/src?ref=ff9dfaf50838eaaba9f9c3e8cba4bdc2a6b04935

I am excluding the test files, and only looking at things not in `src/tests` Right now the tests are only exercising two of the library back end C files. And even still the coverage is fairly low---341/884 statements---not even counting files that were not touched at all. Now obviously some of these are currently unsupported features, like the GASNet builds, but others, like the interface module for non CAF aware compilers should probably be tested some how. Perhaps through writing additional test programs that `use` the module.

**Comment by rouson** [comment]
That's fascinating (and a little depressing) data.  Clearly we have a long way to go in terms of test coverage.

I only run ctest.  @afanfa, do you run any other tests?

**Comment by afanfa** [comment]
The bug has been reported here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68933
I noticed that with -fcoarray=single the error doesn't appear.

**Comment by rouson** [comment]
Thanks. Please also email fortran@gnu.gcc.org unless you're certain that someone will notice it.  I usually send an email to the list after ever bug report I submit.

**Comment by zbeekman** [comment]
Also, the code coverage I posted is not including both the NavierStokes test (since it doesn't seem to like to run on the Travis-CI VMs) as well as the distributed transpose test, since it can not be instrumented for coverage analysis without causing and ICE and breaking the build. I have little idea as to whether or not both those test are expected to have significant impact on the coverage results.

**Comment by zbeekman** [comment]
(And I forgot to add much thanks, @afanfa for reporting the bug :bow: )

**Comment by zbeekman** [comment]
@jerryd @vehre any idea if anyone from GCC has looked at this at all? https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68933

**Comment by zbeekman** [comment]
@rouson I'm wondering if I I should ping the GFortran mailing list about this. What is the email address again?

**Comment by sourcery-student** [comment]
On the one hand, an ICE is always a compiler bug so it's always a reasonable idea to ping the compiler team when an ICE occurs. On the other hand, I find it so often to be the case that I work around an ICE that I probably move on more frequently than I report them.  In this, case I would be fine with disabling this test because it was extracted from the Navier-Stokes solver, which we are also disabling.  A runtime error would disturb me much more than an ICE in code that is decreasing in its relevance.  By definition, the an ICE is a compiler issue and we should keep the OpenCoarrays tests focused on runtime behavior given that OpenCoarrays plays no role in compile-time behavior.

**Comment by rouson** [comment]
FYI, the above comment is from me. I was temporarily logged into the account used to grant course attendees access to private repositories.

**Comment by zbeekman** [comment]
Can you email them and CC me. I'm not sure which email address to use or what to say. The PR seems like it hasn't been looked at other than by Alessandro and me, last time I checked. Obviously it's probably not a high priority but  
it would be nice to confirm that it's on someone's radar.

**Comment by rouson** [comment]
@vehre do you have any comments on this?  Given the limited time of the few gfortran developers in existence, I'm hesitant to email them about an ICE with code that has decreased in its relevance to us over time.  Sadly, I run into ICEs so often that I've adopted a strategy of not reporting them unless (1) I can't devise a good workaround and (2) the code is important to me and/or my collaborators or clients.  This case fails on (2).

@zbeekman in my experience, it's not at all uncommon for PRs to go untouched for years.  The ratio of PRs to developers is such that many PRs languish and get resolved only after several years. That is regrettable, but it's a fact of life for a compiler developed primarily by a handful volunteers.

**Comment by zbeekman** [comment]
OK, then we can just leave it be...

**Comment by zbeekman** [comment]
Closing this since it is an upstream issue...

**Comment by vehre** [comment]
i have merely scanned this issue. It seems to be fixed in gcc 7.0. Given that the bug is somewhere in the inner tidings of computing the coverage, where I have no knowledge of, I am not very intimidated to work on this.

**Comment by zbeekman** [comment]
Oh great! Glad it's fixed in 7. I'll verify this and if this is true can we
close the PR
