### ISSUE TITLE
Defect: Compilation in Cygwin does not work

### ISSUE THREAD

**Issue by maurosgroi** [sourceryinstitute/OpenCoarrays#638]
# Defect/Bug Report #
- OpenCoarrays Version: 2.3.1
- Fortran Compiler: gfortran 7.3
- C compiler used for building lib: gcc 7.3
- Installation method:  direct with cmake
- Output of `uname -a`: CYGWIN_NT-6.1-WOW LT0217969 2.10.0(0.325/5/3) 2018-05-18 20:52 i686 Cygwin
- MPI library being used: openmpi 3.1.0
- Machine architecture and number of physical cores: AMD Pro - 2 cores 2.3 GHz
- Version of CMake:  preinstalled 3.6.2

## Observed Behavior ##
The library configure and compiles but all tests fail with segmentation fault.  
Please have a look at the output of make test.
`Running tests...
Test project /usr/local/src/opencoarrays_build
      Start  1: initialize_mpi
 1/66 Test  #1: initialize_mpi .......................***Failed  Required regular expression not found.Regex=[Test passed.
] 12.42 sec
[LT0217969:19400] *** Process received signal ***
[LT0217969:19400] Signal: Segmentation fault (11)
[LT0217969:19400] Signal code:  (23)
[LT0217969:19400] Failing at address: 0x9
Unable to print stack trace!
[LT0217969:19400] *** End of error message ***
--------------------------------------------------------------------------
mpiexec has exited due to process rank 0 with PID 0 on
node LT0217969 exiting improperly. There are three reasons this could occur:

1. this process did not call "init" before exiting, but others in
the job did. This can cause a job to hang indefinitely while it waits
for all processes to call "init". By rule, if one process calls "init",
then ALL processes must call "init" prior to termination.

2. this process called "init", but exited without calling "finalize".
By rule, all processes that call "init" MUST call "finalize" prior to
exiting or it will be considered an "abnormal termination"

3. this process called "MPI_Abort" or "orte_abort" and the mca parameter
orte_create_session_dirs is set to false. In this case, the run-time cannot
detect that the abort call was an abnormal termination. Hence, the only
error message you will receive is this one.

This may have caused other processes in the application to be
terminated by signals sent by mpiexec (as reported here).

You can avoid this message by specifying -quiet on the mpiexec command line.
--------------------------------------------------------------------------
Error: Command:
   `/usr/bin/mpiexec -np 2 --hostfile /usr/local/src/opencoarrays_build/hostfile --allow-run-as-root /usr/local/src/opencoarrays_build/bin/OpenCoarrays-2.3.1-tests/initialize_mpi`
failed to run.
`
All tests fails in the same way as above.

## Steps to Reproduce ##
Compilation under Mobaxterm version 11.1/build 3860 with pre-installed compilers and libraries.

# Question #
How can I solve the problem?
Thanks a lot in advance and best regards,
Mauro Sgroi.

**Comment by maurosgroi** [comment]
Sorry. I made a mistake attaching the log. 
It is not fenced as required.

**Comment by rouson** [comment]
@maurosgroi We have found MPICH to be more robust than OpenMPI, but probably the mores significant issue here is Cygwin.  Unfortunately, I don't believe we have the resources to support Cygwin builds.   I recommend instead using the Windows Subsystem for Linux (WSL), which provides a full instance of Ubuntu running as a shell in a Windows terminal window and is provided by Microsoft at no additional cost.  If you can install WSL, please try running the OpenCoarrays installer (`./install.sh`).

I'm closing this and marking it as "won't fix."

**Comment by maurosgroi** [comment]
Dear Rouson,
WSL requires windows 10. Many users are still forced to used Windows 7.
Thanks for the reply,
Mauro.

**Comment by rouson** [comment]
Sorry we can't help.  Have you tried running other MPI jobs such as an MPI "Hello, world!"?  Also, just in case it's of interest, there's a gfortran developer working on a shared-memory coarray implementation that won't require OpenCoarrays or MPI.  You can follow development on it on [GCC Bugzilla issue 88076](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88076).
