### ISSUE TITLE
error when building with conda gcc/gfortran 7.3

### ISSUE THREAD

**Issue by ericpellegrini** [sourceryinstitute/OpenCoarrays#652]
Dear all,

When trying to build OpenCoarrays using conda and gcc-7 toolchain I get the following error at build time:

`x86_64-conda_cos6-linux-gnu-cc: error:  -DNDEBUG: No such file or directory`

Investigating further the problem by switching to verbose mode, I could narrow the error to the following build command:

```cd /home/pellegrini/tests/OpenCoarrays/build/src/mpi && /home/pellegrini/.conda/envs/jupyterhub/bin/x86_64-conda_cos6-linux-gnu-cc -DGCC_GE_7 -DHAVE_MPI -DMPI_WORKING_MODULE -DPREFIX_NAME=_gfortran_caf_ -I/home/pellegrini/.conda/envs/jupyterhub/include -I/home/pellegrini/tests/OpenCoarrays/src  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -fno-working-directory -O3 -DNDEBUG -fPIC   " -DNDEBUG" -o CMakeFiles/caf_mpi_static.dir/__/common/caf_auxiliary.c.o   -c /home/pellegrini/tests/OpenCoarrays/src/common/caf_auxiliary.c```

where you can see a quoted " -DNDEBUG" which messes up the build. Removing the quotes solves the problem. 

Here is my conda environment file:

```
name: test

channels:
  - anaconda
  - conda-forge

dependencies:

  - gfortran_linux-64
  - mpich
  - cmake
```

from there I build the `OpenCoarrays` in developer mode (git clone, mkdir build, cmake, make ...)

Would you have any idea for solving this ?

thanks

Eric

**Comment by ericpellegrini** [comment]
OK. I found the problem. `openmpi` was missing in my conda environment. Everything is OK from the OpenCoarrays side.

**Comment by zbeekman** [comment]
Glad to hear it!

**Comment by zbeekman** [comment]
Why was this reopened, @ericpellegrini?

**Comment by ericpellegrini** [comment]
sorry I reopened it and cancel the reopening. I close it for good.
