### ISSUE TITLE
RFE: Implement caf_init() and caf_finalize() in cpp

### ISSUE THREAD

**Issue by ktras** [sourceryinstitute/OpenCoarrays#667]
### To Do

- [ ] caf_init()
- [ ] caf-finalize()

**Comment by rouson** [comment]
@ktras I'm closing this and replacing this with issue #668 , which I'm incorporating into the new kanban board under the new OpenCoarrays 3.0 [project page], which in turn is replacing the like-named milestone.  Please click the links in this comment to see the new project structure.

[project page]: https://github.com/sourceryinstitute/OpenCoarrays/projects/5
