### ISSUE TITLE
RFE: Incorporate opencoarrays3.0 power subdirectory into CMake build system

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/OpenCoarrays#669]
The `src/power` subdirectory on the `opencoarrays3.0` branch contains a handful of stubs of the new interface and one test, all in one directory.  Let's replace the Makfile with CMake scripts and either mirror the current `src` directory structure under the new `src/power` subdirectory or move the stubs and tests into their counterpart locations in the current OpenCoarrays release, e.g., `src/mpi` and `src/tests/unit/`.

**Comment by zbeekman** [comment]
@rouson: I understand the part about using CMake, but I don't quite follow how you want to re-structure the directories.

**Comment by zbeekman** [comment]
be gone stale bot

**Comment by rouson** [comment]
It's not clear that this work will move forward anytime soon so I'm marking this as `wont-fix` and closing.
