### ISSUE TITLE
Defect: Scalar Coarrays Not Allowed in a Function 

### ISSUE THREAD

**Issue by evansste12432** [sourceryinstitute/OpenCoarrays#692]
- [ ] I am reporting a bug others will be able to reproduce and not asking a question or requesting a new feature.

## System information including:
  - OpenCoarrays Version: 2.8.0
  - Fortran Compiler: GNU Fortran 8.3.0
  - C compiler used for building lib: gcc 8.3.0
  - Installation method: Installed from downloaded tarball
  - All flags & options passed to the installer: make -j 8
  - Output of `uname -a`:  Linux Computer1 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  - MPI library being used: MPICH 3.3
  - Machine architecture and number of physical cores:  MSI 970 Gaming Desktop, AMD FX-8350 4.0 GHz 8-core processor, 32 GB RAM
  - Version of CMake: 3.13.4

### What you were trying to do (and why)

I am trying to compile a simple function that uses coarrays.

### What happened (include command output, screenshots, logs, etc.)

When trying to run `caf -c newprog.f08`, I get the following message:
`Error: Variable 'a' at (1) is a coarray and is not ALLOCATABLE, SAVE nor a dummy argument`

### What you expected to happen

I expected the program to compile with no errors.

### Step-by-step reproduction instructions to reproduce the error/bug

Try to compile the following program:
```fortran
module newprog_module
    implicit none
    private

    public :: newprog
contains

function newprog(input) result(output)

    integer, intent(in) :: input
    integer, codimension[*] :: A
    integer :: output

    output = 5
end function newprog
end module newprog_module
````
The above program produces an error.  However, the following program does not.

```fortran
program newprog2
    
    integer, codimension[*] :: A
    integer :: output

    output = 5
end program newprog2
```

**Comment by rouson** [comment]
@evansste12432 the submitted code is not standard-conforming.  Constraint C826 in the [Fortran 2018 standard] stipulates, "A coarray or an object with a coarray ultimate component shall be an associate name, a dummy argument, or have the ALLOCATABLE or SAVE attribute."  One way to make the submitted code would be to give `A` the `save` attribute:
```fortran
    integer, codimension[*], save :: A
```
I believe the reason for this restriction relates to parallel performance.  Were the standard to allow the submitted code, the coarray would have to be (re-)established anew every time the function is invoked, which essentially means there would be an implicit allocation.  Coarray allocations are synchronization points.  Frequent synchronization hinders parallel performance.  

I hope this explanation helps.  I'm closing this issue.  Feel free to reopen it if you think I'm misinterpreting something.  

[Fortran 2018 standard]: https://j3-fortran.org/doc/year/18/18-007r1.pdf

**Comment by evansste12432** [comment]
Your explanation does help.  Thank you.
