### ISSUE TITLE
Defect: "sync all" Doesn't Sync

### ISSUE THREAD

**Issue by evansste12432** [sourceryinstitute/OpenCoarrays#693]
- [ ] I am reporting a bug others will be able to reproduce and not asking a question or requesting a new feature.

## System information including:
  - OpenCoarrays Version: 2.8.0
  - Fortran Compiler: GNU Fortran 8.3.0
  - C compiler used for building lib: gcc 8.3.0
  - Installation method: I installed from a downloaded tarball
  - All flags & options passed to the installer: N/A (normall CMake build)
  - Output of `uname -a`:  `Linux Computer1 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
  - MPI library being used: `mpiexec --version` shows version 3.3
  - Machine architecture and number of physical cores: Dell PowerEdge R910 Server with 32 cores (4x 8-Core Xeon X7560 2.27GHz)
  - Version of CMake: 3.13.4

### What you were trying to do (and why)

I have written a short Fortran program which uses coarrays and the `sync all` statement.  The `sync all` statement doesn't appear to work as expected.

### What happened (include command output, screenshots, logs, etc.)

I compiled and ran the following program with the number of processors equal to three.
```fortran
program sync_issue
    implicit none

    integer :: n, noe

    noe = 3
    do n = 1,noe
        print *, 'red ', n, ' ', this_image()
        sync all
        print *, 'green ', n, ' ', this_image()
        sync all
    end do
end program sync_issue
```
It produces the following result on the screen:
```
 red            1             1
 green            1             1
 red            2             1
 green            2             1
 red            3             1
 green            3             1
 red            1             2
 green            1             2
 red            2             2
 green            2             2
 red            3             2
 green            3             2
 red            1             3
 green            1             3
 red            2             3
 green            2             3
 red            3             3
 green            3             3
```

### What you expected to happen
I expected it to print something like the following:
```
red            1             1
red            1             2
red            1             3
green            1             1
green            1             2
green            1             3
red            2             2
red            2             1
red            2             3
green            2             3
green            2             2
green            2             1
red            3             1
red            3             3
red            3             2
green            3             3
green            3             1
green            3             2
```

### Step-by-step reproduction instructions to reproduce the error/bug
Compile the short program with `caf sync_issue.f08 -o sync_issue`.  Then run it with `cafrun -np 3 sync_issue`.

**Comment by evansste12432** [comment]
Apparently, this isn't a bug.  The problem arises due to the fact that information is buffered when using the `print` command.

In order to solve the problem, place the following command after your `print` statements: `call execute_command_line('')`.  This will cause the buffered information to be released so that you can immediately see your printed results on the screen.

So, ultimately, my revised program now looks like this:
```fortran
program sync_issue
    implicit none

    integer :: n, noe

    noe = 3
    do n = 1,noe
        print *, 'red ', n, ' ', this_image()
        call execute_command_line('')
        sync all

        print *, 'green ', n, ' ', this_image()
        call execute_command_line('')
        sync all
    end do
end program sync_issue
```
It now wonderfully works as expected.

**Comment by shahmoradi** [comment]
How about

```fortran
flush(output_unit)
```

where output_unit is from

```fortran
use iso_fortran_binding, only: output_unit
```

instead of

```fortran
call execute_command_line('')
```

os is the `flush()` statement not applicable to stdout?

**Comment by evansste12432** [comment]
Thanks, shahmoradi.

`flush()` is applicable to `stdout`, and may very well work.  I learned about it while trying to get this program to function properly.  It's the suggestion that kept popping up, but I could never get it to work.

In all of my searches, no one mentioned the need for `iso_fortran_binding`, which, apparently, is why I couldn't get `flush()` to work.

I don't have `iso_fortran_binding` installed, so I still haven't been able to confirm.  You're probably right that it'll work.

Once I discovered that `call execute_command_line('')` works, I stopped looking for other solutions.

Thanks for shedding more light on `flush()`.  It's always helpful to understand the proper approach.

**Comment by rouson** [comment]
@evansste12432 `iso_fortran_binding` was a typo.  You want 
```fortran
use iso_fortran_env, only : output_unit
```
(On a historical note, I recently heard that the Oracle Fortran compiler used to have something called `iso_fortran_binding`, but it was never part of the Fortran standard.  I don't recall the purpose -- I think it had something to do with linking to legacy Fortran code that used some Oracle extension to the language.

**Comment by evansste12432** [comment]
Thanks for clearing that up, @rouson.  In that case, `flush()` still didn't work.

I've been using `iso_fortran_env` as I try to work with teams.  I'm assuming it was installed, by default, when I installed OpenCoarrays 2.8.0, since I have team functionality.  Am I wrong about that?

If I'm right, then the `flush()` approach still doesn't seem to work.

**Comment by rouson** [comment]
@evansste12432 `iso_fortran_env` is part of the Fortran standard and is installed automatically whenever `gfortran` is installed.  And yes, if you are using `team_type`, then you have `iso_fortran_env`.

**Comment by shahmoradi** [comment]
Damian is right, my apologies for the typo, I use `iso_fortran_env` and `iso_c_binding` intrinsic modules often, and I got confused for a moment. These two are intrinsic and should be available in at least Intel, Cray, and GFortran compilers by default, as far as I am aware (perhaps also including PGI, IBM, NAG, ... compilers). The statement `flush (output_unit)` has worked in applications that I have worked with so far. I'd be surprised if it is otherwise.

**Comment by evansste12432** [comment]
@shahmoradi , I don't know why it isn't working for me.  If the following program produces correct results for you, then there would have to be something wrong with my system:
```fortran
program sync_issue
    use iso_fortran_env, only : output_unit
    implicit none

    integer :: n, noe

    noe = 3
    do n = 1,noe
        print *, 'red ', n, ' ', this_image()
        flush(output_unit)
        sync all

        print *, 'green ', n, ' ', this_image()
        flush(output_unit)
        sync all
    end do
end program sync_issue
```

**Comment by shahmoradi** [comment]
Hi @evansste12432 , I tested your code and confirm the behavior. This was a very interesting post and counter-intuitive for me, so I decided to bring this up on Intel forum to get a response from the community as well, including the Fortran committee chair Steve Lionel,

https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/837101#comment-1948312

I'd suggest you get involved in the discussion and report any observations you have had there too. In sum, according to Steve, the observed behavior with flush() is correct, although I am not quite convinced yet, still waiting for his further clarifications in the discussion on the Intel forum.

**Comment by evansste12432** [comment]
Hello @shahmoradi.

While previously searching for solutions to this problem, I came across the following link:

https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/531146

You'll notice that this issue has, in deed, been discussed in the same Intel forum.  At that time, `flush 6` was suggested, and seemed to work for one person who was involved in the discussion -- Though, as previously stated, I could never get it to work.

During the conversation, more is explained from the developer, which may shed more light on the issue.  It was the last post in the conversation, which makes me think the explanation may have put all concern to rest.
