### ISSUE TITLE
RFE: Simple install instructions

### ISSUE THREAD

**Issue by robnagler** [sourceryinstitute/OpenCoarrays#708]
I was trying to install using install.sh, and it did nothing (see https://github.com/radiasoft/zgoubi/issues/90). @rouson suggested I build off master, which did work, but only after I figured that you can do things much more simply.

There are many different install instructions. [INSTALL.md](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md) starts off with [Developer Build and Install](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/INSTALL.md#developer-build-and-install) with these instructions:

```sh
mkdir opencoarrays-build
cd opencoarrays-build
export FC=/path/to/gfortran
export CC=/path/to/gcc
cmake /path/to/OpenCoarrays/source \
  -DCMAKE_INSTALL_PREFIX=/path/to/desired/installation/location
make
make test # optional; verify build works
make install
```

However, this is atypical and doesn't work with copy and past, especially for the "impatient" like me. I found that this works:

```sh
git clone https://github.com/sourceryinstitute/OpenCoarrays
cd OpenCoarrays
mkdir build
cd build
cmake ..
make
make test # optional; verify build works
sudo make install
```

You could add more advanced instructions after this, but on a typical distro, cmake will find everything automatically. If the user doesn't have sudo privs, you could have another section explaining how to change the install prefix and so on.

**Comment by rouson** [comment]
Thanks, @robnagler.  I'll make the suggested edits.
