### ISSUE TITLE
Add version information to GCC compile within install.sh

### ISSUE THREAD

**Issue by singleterry** [sourceryinstitute/OpenCoarrays#715]
- [X ] I am reporting a bug others will be able to reproduce and not asking a question or requesting a new feature.

## System information including:
  - OpenCoarrays Version: 2.9.0
  - Fortran Compiler: gcc 10.1.0
  - C compiler used for building lib: gcc 10.1.0
  - Installation method: ./install.sh
  - All flags & options passed to the installer: --num-threads 4 --yes-to-all --bootstrap
  - Output of `uname -a`: Linux hze.larc.nasa.gov 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
  - MPI library being used: MPICH 3.2
  - Machine architecture and number of physical cores: N/A
  - Version of CMake: N/A

## To help us debug your issue please explain:

All compiles and runs fine, but with the gcc compiled by install.sh, most other applications (firefox, emacs, etc...) complain that 

emacs: /users0/rsinglet/CAF/OpenCoarrays/prerequisites/installations/gnu/10.1.0/lib64/libgomp.so.1: no version information available (required by /usr/lib64/libMagickWand.so.5)

### What you were trying to do (and why)

Use other precompiled programs (firefox, emacs, etc...) with the gcc libraries pointed to by OpenCoarrays' version of GCC (10.1.0 in my case)

**Comment by rouson** [comment]
@singleterry if I recall correctly, @sameershende resolved this issue for you so I'm closing it.  Feel free to reopen it if the there is still something that needs to be fixed in OpenCoarrays.
