### ISSUE TITLE
Defect: `cafrun` should report an error if `-n #` argument is not provided

### ISSUE THREAD

**Issue by everythingfunctional** [sourceryinstitute/OpenCoarrays#717]
- [x] I am reporting a bug others will be able to reproduce and not asking a question or requesting a new feature.

## System information including:
  - OpenCoarrays Version: 2.9.0
  - Fortran Compiler: gfortran 10.2.0
  - C compiler used for building lib: Installed from AUR
  - Installation method: from AUR
  - All flags & options passed to the installer: N/A
  - Output of `uname -a`: Linux darter 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux
  - MPI library being used: MPICH 3.4
  - Machine architecture and number of physical cores: Intel 4 core (i7?)
  - Version of CMake: 3.18.4

## To help us debug your issue please explain:

executing `cafrun path_to_executable` simply exits with a 0 status, and does nothing

### What you were trying to do (and why)

I was simply trying to run my program

### What happened (include command output, screenshots, logs, etc.)

Nothing. No output was produced and the exit status was 0

### What you expected to happen

Either, the program was run with a single image, or an error was reported about the misuse of the command

### Step-by-step reproduction instructions to reproduce the error/bug

1. Compile a program with `caf main.f90 -o main`
2. Run the program with `cafrun main`

[links]:#
[fenced code blocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md

**Comment by vehre** [comment]
On a Linux it is usually required to use './' before main, i.e., try cafrun
./main
Andre Vehreschild * Kreuzherrenstr. 8 * 52062 Aachen
Tel.: +49 241 9291018 * vehre@gmx.de
Am 28. Oktober 2020 19:38:53 schrieb Brad Richardson
<notifications@github.com>:

**Comment by everythingfunctional** [comment]
That does not solve this particular issue, and in any case is only necessary if the **command** you're trying to run is in the current directory, and `.` is not in your `PATH` environment variable. For example running the command `main` may not work, and would need to be `./main`, but in this case `./cafrun` would not be appropriate because the `cafrun` executable is not in the current directory.
