### ISSUE TITLE
/usr/bin/mpiexec failed to run on Ubuntu WSL

### ISSUE THREAD

**Issue by apoorv-2-8** [sourceryinstitute/OpenCoarrays#732]
I am getting following error when trying to run my first coarray example on Ubuntu WSL

cafrun -n 8 ex01
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
[proxy:0:0@DESKTOP-P8SL3CQ] HYDU_create_process (utils/launch/launch.c:74): execvp error on file ex01 (No such file or directory)
Error: Command:
   `/usr/bin/mpiexec -n 8 ex01`
failed to run.

what could be the reason

**Comment by vehre** [comment]
use `/usr/bin/mpiexec -n 8 ./ex01` as it is needed on Unix!
