### ISSUE TITLE
Defect: Test cases use pre-F2018 co_reduce()-parameter operator, which is renamed in F2018 to operation

### ISSUE THREAD

**Issue by vehre** [sourceryinstitute/OpenCoarrays#745]
In gcc>=12 the Fortran Standard 2018's co_reduce(... operation=...) is implement. Code using pre-2018 Fortran (and still using operator=...) will stop compiling.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.**

- [x] I am reporting a bug others will be able to reproduce and not asking a question or requesting a new feature.

## System information including:
  - OpenCoarrays Version: 
  - Fortran Compiler: 
  - C compiler used for building lib: 
  - Installation method: 
  - All flags & options passed to the installer
  - Output of `uname -a`:
  - MPI library being used: 
  - Machine architecture and number of physical cores:
  - Version of CMake: 

### Step-by-step reproduction instructions to reproduce the error/bug

Compile testsuite with gcc>=12.

[links]:#
[fenced code blocks]: https://help.github.com/articles/creating-and-highlighting-code-blocks/
[CONTRIBUTING.md]: https://github.com/sourceryinstitute/OpenCoarrays/blob/master/CONTRIBUTING.md

**Comment by vehre** [comment]
Fix is available at: https://github.com/sourceryinstitute/OpenCoarrays/tree/issue-745-rename-co_reduce-operator-for-F2018

The fix uses the pre-processor to use the different identifiers depending on the gcc-version used. Therefore the files had to renamed to *.F90, i.e. with a capital F which by convention enables preprocessor-processing.

**Comment by rouson** [comment]
Thanks, @vehre!  Please open a pull request to merge this fix into the main branch.

@everythingfunctional please let me know if you can review and merge the PR

**Comment by everythingfunctional** [comment]
Sounds straightforward enough. Open a PR and I'll review it.

**Comment by vehre** [comment]
The pull reQuest is at: https://github.com/sourceryinstitute/OpenCoarrays/pull/746

**Comment by rouson** [comment]
PR #746 has been merged so I'm closing this issue.
