### ISSUE TITLE
CAF and MSMPI

### ISSUE THREAD

**Issue by SourcerersApprentice** [sourceryinstitute/opencoarrays#81]
It looks like the newest MSMPI (version 7) does not have the MPI3 support needed to build OpenCoarrays. The following functions (at least) seem to be missing:

`MPI_Compare_and_swap'
`MPI_Win_flush'
`MPI_Win_sync'
`MPI_Win_unlock_all'
`MPI_Fetch_and_op'
'MPI_Alloc_mem' (MPI3 flavor)

**Comment by rouson** [comment]
Does this mean the Windows build has reached dead end or do you have other options in mind?  I think Intel MPI supports Windows.  Intel compilers are now free for use in contributing to open-source projects as long as the developer is not compensated for his or her work.  Given that what you're working on right now is a port of OpenCoarrays, you might consider applying for a free license and listing OpenCoarrays as the project.

Walt Brainerd and @afanfa got OpenMPI to work on Windows at one point, but Walt's build later broke (executables hang for unclear reasons).  Walt plans to make another run at this when Cygwin releases its port of GCC 5.2.  And unfortunately, MPICH doesn't support Windows so Intel is the only current option of which I'm aware.

**Comment by SourcerersApprentice** [comment]
I have started out by asking the people at Microsoft if they would please add those functions to their next release of MPI. They do HPC and you do HPC so it seems like they would want to help. 
My next step was to start surveying the landscape again looking for the alternative. I will check out the Intel thing. If there is any joy, I will reopen this issue.

**Comment by zbeekman** [comment]
I'm going to make a new tag and issue to document these latest issues.

**Comment by zbeekman** [comment]
Actually, I just looked at the title here. I'm going to add a "blocked by vendor" and  "waiting" tag and reopen, if that's OK.

**Comment by SourcerersApprentice** [comment]
Thats OK. I closed it because it seemed there was nothing to do.

**Comment by zbeekman** [comment]
Any luck or updates @SourcerersApprentice? I think I'll close this if we're still waiting on windows, but feel free to reopen.

**Comment by AndreMikulec** [comment]
@SourcerersApprentice

I hate to bring up an old topic about the "Intel® MPI Library for Windows"

```
It looks like the newest MSMPI (version 7) 
does not have the MPI3 support needed to build OpenCoarrays. 
The following functions (at least) seem to be missing:

MPI_Compare_and_swap' MPI_Win_flush'
MPI_Win_sync' MPI_Win_unlock_all'
`MPI_Fetch_and_op'
'MPI_Alloc_mem' (MPI3 flavor)
```
On Windows 10, I Installed the most recent Intel MPI Library for Windows.

The following queries are returned and are query results are positive(found) hits . . . 
```
AstroGrep Search

Search Path
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2020.0.166\windows\mpi\intel64\include

File Types
*.h

Search Text (each individually tried and found)
[x] Regular expression
[ ] Case senstive
[x] Search subfolders

\bMPI_COMPARE_AND_SWAP
\bMPI_WIN_FLUSH
\bMPI_WIN_SYNC
\bMPI_WIN_UNLOCK_ALL
\bMPI_FETCH_AND_OP
\bMPI_ALLOC_MEM
```
Is it the case that?
```
1. No one or someone has deeply investigated "Intel® MPI Library for Windows"
2. No one or someone has tried "Intel® MPI Library for Windows"
3. Other [better? or simpler?] solutions exist: e.g. Windows Subsystem For Linux (WSL)
4. No one or someone has investigated "Intel® MPI Library for Windows" 
   and the software port is just not worth the effort/interest.
5. The new-changed "Intel Simplified Software License"  of  
   "Intel® MPI Library for Windows" software license is unacceptable (but may need a review?).
```
Thanks.
