### ISSUE TITLE
Add documentation to C headers

### ISSUE THREAD

**Issue by zbeekman** [sourceryinstitute/OpenCoarrays#82]
Doxygen documentation should be added to C headers to generate info like https://gcc.gnu.org/onlinedocs/gfortran/Coarray-Programming.html#Coarray-Programming

See discussion here: https://gitter.im/sourceryinstitute?at=567460cf091b6f9e0439bf1a

**Comment by zbeekman** [comment]
@rouson Here is the documentation for adding inline developer documentation to non-Fortran files using FORD: https://github.com/cmacmackin/ford/wiki/Writing-Documentation#non-fortran-source-files

Essentially, it will give you source highlighting and let you author documentation in markdown, but it doesn't know about function signatures, or any syntax of languages other than Fortran.

**Comment by zbeekman** [comment]
So, I guess that for C files and headers, embedding documentation would look like:

```c
//! # H1 Heading Here
//! [a linky link](http://www.example.com)
//! you can even embed latex formulae via MathJax support.
//!
//!    // code blocks must be indented by at least 4 spaces or a tab, since this is original markdown, not gh-flavored
//!
//!    :::fortran
//!    program foo
//!    implicit none
//!    print*, "hello world!"
//!    end program
//!
//! The python markdown extension CodeHilite is enabled by default... you can specify the language a number of ways...
//! But the source code should be included in the FORD output by default, so no need to duplicate it...
```

**Comment by rouson** [comment]
:clap:  Thanks, @zbeekman!

**Comment by rouson** [comment]
I've reached an impasse. The GCC web site exists as the de facto OpenCoarrays [ABI documentation](https://gcc.gnu.org/onlinedocs/gfortran/Coarray-Programming.html) but it is cumbersome to edit, contains compiler-specific names (e.g., _gfortran_caf_init that we generate by a C preprocessor macro), and it is governed by the GNU Free Documentation License, which I believe precludes our incorporating directly into our repository.  For now, I guess the best thing is to put commented hyperlinks in our source code as pointers to the documentation and reminders to keep the documentation current.  Unless anyone has another idea, I'll go this route.

**Comment by zbeekman** [comment]
hmmm I'll have to think about it a bit...

I'm in the process of adding the FORD project file, etc. right now. Ideally, we would get GCC to link to our documentation rather than vice-versa, then we update it in the source and it is current from the perspective of the GCC webpage (links or embeds <iframe>, or similar?) and our documentation.

For now, I'm going to make it so that Master always deploys via gh-pages. Then, I will add devel, also deploying to gh-pages. Eventually we should get Travis-CI to update the release documentation (linked from, say the landing page of the documentation) either via a direct commit or an automatic pull request...

However these are steps for down the road, for now, let's just get the API documentation up...

**Comment by zbeekman** [comment]
<iframe src="http://www.google.com"></iframe>
