### ISSUE TITLE
Refactor install.sh to also write setup.csh

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/opencoarrays#85]
A the end of a successful installation, install.sh writes a setup.sh file in the installation path and directs users to source that file in order to define environment variables required for proper execution of caf and cafrun.  

For users of C shell, install.sh should also create an alternative setup.csh with the C-shell translations of the bash shell statements in setup.sh.  Attached is a sample setup.csh provided by Bob Numrich.

[setup.csh.txt](https://github.com/sourceryinstitute/opencoarrays/files/70418/setup.csh.txt)

**Comment by zbeekman** [comment]
I would also like to examine ways to make sourcing setup scripts unnecessary. Part of this will inevitably depend on whether or not the user has root privileges, and where they select to install OpenCoarrays. Is this something you want to have done for the next release?
