### ISSUE TITLE
Build Failure for MPI with normal Makefile

### ISSUE THREAD

**Issue by naveen-rn** [sourceryinstitute/opencoarrays#9]
I tried to build using normal Makefile instead of CMake, inside src/ directory. I'm using Open MPI - 1.8.5 and GCC-5.1.

I did the following steps;
> module load openmpi-1.8.5
> module load gcc-5.1
> cd ~/opencoarrays/src
> make clean
> make mpi

And for the above build I'm getting the following errors;
> mpi_caf.c: At top level:
> mpi_caf.c:1745:16: error: conflicting types for ‘do_sum_int1’
> GEN_REDUCTION (do_sum_int1, int16_t, inoutvec[i] += invec[i])

> mpi_caf.c: At top level:
> mpi_caf.c:1746:16: error: conflicting types for ‘do_min_int1’
>  GEN_REDUCTION (do_min_int1, int16_t,

> mpi_caf.c: At top level:
> mpi_caf.c:1748:16: error: conflicting types for ‘do_max_int1’
> GEN_REDUCTION (do_max_int1, int16_t,

I can jump the errors and still build the files, by defining -DMPI_INTEGER2 during the make. I ran a couple of tests for confirming the build and it works perfectly. I did the following to compile and run some sample CAF programs;

> gfortran -fcoarray=lib sample.f90 -L/home/naveen/opt/opencoarrays/ -L/opt/packages/mpi/openmpi/1.8.5/lib/ -I/opt/packages/mpi/openmpi/1.8.5/include -lmpi -lcaf_mpi
> export LD_LIBRARY_PATH=/opt/packages/mpi/openmpi/1.8.5/lib/
> mpirun -n 4 ./a.out

I didn't have a look at the implementation and not sure for the reason behind these conflicts. Let me know, if you have something in mind. Is it related to some patch issues in GCC-5.1, I didn't update my GCC-5.1 with the recent July patch.

```
#ifndef MPI_INTEGER2
  GEN_REDUCTION (do_sum_int1, int16_t, inoutvec[i] += invec[i])
  GEN_REDUCTION (do_min_int1, int16_t, 
            inoutvec[i] = invec[i] >= inoutvec[i] ? inoutvec[i] : invec[i])
  GEN_REDUCTION (do_max_int1, int16_t, 
            inoutvec[i] = invec[i] <= inoutvec[i] ? inoutvec[i] : invec[i])
#endif
```

**Comment by rouson** [comment]
Hi Naveen,

Thanks for your interest and for the feedback.  Alessandro developed the Makefile so I'll let him respond to the specifics.

As you probably saw in our documentation, CMake is the preferred build system for several reasons.  The most important reason is that it also builds numerous tests and facilitates running the tests with a single "ctest" command.   Also, the CMake scripts will detect your compiler identity, compiler version number, and operating system and tailor the build to your system to some extent.  If you use CMake, we expect that you will see only one unique warning message of which we are aware and you should see no errors. Please report any that you do see if you try building with CMake.

Damian

**Comment by afanfa** [comment]
Hi Naveen,

unfortunately I cannot reproduce the problem you mentioned on my machines.
I downloaded a fresh openmpi-1.8.5, built and installed using gcc-5.1 and gcc-6.0. Using make, OpenCoarrays compiles and run just fine. As Damian suggested, please try to use CMake and let us know how it goes.

Alessandro

**Comment by afanfa** [comment]
Hi Naveen,

do you have any news about this issue? Have you tried with CMake?

**Comment by naveen-rn** [comment]
I tried with CMake and it works. I suppose the problem, is in the way I have built and configured OpenMPI. Let, me zero down to the exact location of the problem. Meanwhile, I think we can close this issue. Thanks for the time and effort to look into this.
